(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.sliderButton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(3,1,1).p("ACCAAQAAA2gmAmQgmAmg2AAQg1AAgngmQglgmAAg2QAAg1AlgmQAngmA1AAQA2AAAmAmQAmAmAAA1g");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#666666").s().p("AhcBcQglgmAAg2QAAg1AlgmQAngmA1AAQA2AAAmAmQAmAmAAA1QAAA2gmAmQgmAmg2AAQg1AAgngmg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#00FFFF").ss(3,1,1).p("ACMAAQAAA6gpApQgpApg6AAQg5AAgqgpQgogpAAg6QAAg5AogpQAqgpA5AAQA6AAApApQApApAAA5g");

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0000FF").s().p("AhjBiQgogoAAg6QAAg5AogoQAqgqA5AAQA6AAAoAqQAqAoAAA5QAAA6gqAoQgoAqg6AAQg5AAgqgqg");

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#FFFF00").ss(3,1,1).p("ACCAAQAAA2gmAmQgmAmg2AAQg1AAgngmQglgmAAg2QAAg1AlgmQAngmA1AAQA2AAAmAmQAmAmAAA1g");

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF0000").s().p("AhcBcQglgmAAg2QAAg1AlgmQAngmA1AAQA2AAAmAmQAmAmAAA1QAAA2gmAmQgmAmg2AAQg1AAgngmg");

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF00FF").s().p("AhpBpQgsgrAAg+QAAg9AsgrQAsgtA9AAQA+AAArAtQAtArAAA9QAAA+gtArQgrAtg+AAQg9AAgsgtg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_3},{t:this.shape_2}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).to({state:[{t:this.shape_6}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-15.5,-15.5,31,31);


(lib.sliderBGLine = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(5,1,1).p("ArtAAIXbAA");
	this.shape.setTransform(75,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.sliderBGLine, new cjs.Rectangle(-2.5,-2.5,155,5), null);


(lib.btnSquare = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFF00").ss(1,1,1).p("AnznzIPnAAIAAPnIvnAAg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF00FF").s().p("AnzH0IAAvnIPnAAIAAPng");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},3).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-51,-51,102,102);


(lib.btnPlus = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgxDIIAAiWIiWAAIAAhjICWAAIAAiWIBjAAIAACWICWAAIAABjIiWAAIAACWg");

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},3).wait(1));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#000066","#0066FF"],[0,1],30,30,30,-29.9).s("#00FFFF").ss(3,1,1).rr(-30,-30,60,60,10);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#000066","#00FFFF"],[0,1],30,30,30,-29.9).s("#00FFFF").ss(3,1,1).rr(-30,-30,60,60,10);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF00FF").s("#FF00FF").ss(3,1,1).rr(-30,-30,60,60,10);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2,p:{rotation:0}}]},1).to({state:[{t:this.shape_2,p:{rotation:180}}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-31.5,-31.5,63,63);


(lib.btnMinus = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnzBkIAAjHIPnAAIAADHg");
	this.shape.setTransform(0,0,0.4,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},3).wait(1));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#000066","#0066FF"],[0,1],30,30,30,-29.9).s("#00FFFF").ss(3,1,1).rr(-30,-30,60,60,10);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#000066","#00FFFF"],[0,1],30,30,30,-29.9).s("#00FFFF").ss(3,1,1).rr(-30,-30,60,60,10);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF00FF").s("#FF00FF").ss(3,1,1).rr(-30,-30,60,60,10);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2,p:{rotation:0}}]},1).to({state:[{t:this.shape_2,p:{rotation:180}}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-31.5,-31.5,63,63);


(lib.checker = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(8,1,1).p("AiLgIIA4AAIAfCFIDAj5");
	this.shape.setTransform(2.25,-4.25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.checker, new cjs.Rectangle(-15.7,-20.7,36,33), null);


(lib.mBtnSSlitD = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AGeBxIABgYQASAHAIABQAJADAHAAQADAAAHgEQABgEAAgEIAAiSIhEAAIAAgWIBEAAIAAgoIAXAAIAAAoIATAAIAAAWIgTAAIAACYQAAAQgMAHQgHAFgNAAQgRAAgcgJgAmRB5IAAgoIhsAAIAAgUIBsAAIAAgPIhUAAQgGgBAAgEIAAhQQAAgGAGAAIC+AAQAFAAAAAGIAABQQgBAFgEAAIhTAAIAAAPIBrAAIAAAUIhrAAIAAAogAl6AaIBBAAIABgBIAAgPIhCAAgAnVAZIABABIBDAAIAAgQIhEAAgAl6gIIBCAAIAAgQIgBgBIhBAAgAnVgYIAAAQIBEAAIAAgRIhDAAIgBABgAFFB1IAAgYQAbAJAHgEQAFgFAAgGIAAghIgRAOQgOALgRAJQgTALgPAGIgNgUQAwgRAdgYIADgDIhNAJIgDgWIAOgCIAAh5QABgGAEAAIAfAAQAFgLAAgJIAVAFIgDAPIAmAAQAGABAAAFIAABWIAKgdIAVAHQgKAdgVAhIAABCQgBAMgJAHQgIAEgNAAQgMAAgSgDgAEwAYIA8gGIAAgRIg8AAgAEwgTIA8AAIAAgUIg8AAgAEwhNIAAARIA8AAIAAgRQAAgBAAAAQAAAAAAgBQAAAAgBAAQAAAAAAAAIg5AAIgCACgAAoB4IAAhtIgbADIgEgSIALgCQAKgKAMgTQgRgSgSgJIAKgSIAIAFQAKgTAJgZIASAJQgHATgPAcIANALQAIgTAGgSIAUAFQgHAcgjAuIAZgDIgEgQIASgEQAGAUADAbIgTADIgBgLIgMACIAABwgAi1BmQARgGAHgIQAFgFABgJIAAg+QAAAAAAgBQAAAAAAAAQAAAAgBgBQAAAAgBAAIgLAAIAAgRIAeAAQAEABAAAEIAABIIAAACIACACQAHAaArgBIACAAIAAgaIgqAAIAAgSIAqAAIAAgOIgoAAIAAgTIAoAAIAAgQIgqAAIAAgRIAqAAIAAgTIAVAAIAAATIAoAAIAAARIgoAAIAAAQIAnAAIAAATIgnAAIAAAOIAuAAIAAASIguAAIAAAZIAvgEIgGAXIhMABQgkgDgLgSQgFAHgKAHQgMAIgJABgABYBkQAMgCAJgFQAWgLADgbIgmAAIAAgUICaAAIAAAUIg1AAIAAAeQAAAEACAEQAEAEAEAAIANAAIAGgDQACgDABgTIAVAEQgEAegDADQgIAIgGAAIggAAQgIgBgHgGQgGgHAAgGIAAgqIgWAAQgCAagNAQQgOAQgbAGgAjaB1IAAhtIgbAEIgGgSIARgCQAJgLAJgQQgRgSgTgKIAKgSIAIAFQAKgUAKgZIARAJQgHAUgPAcIANAMQAJgTAHgSIATAFQgHAdgfArIATgDIgEgLIASgEQAGATADAYIgTADIgCgMIgJABIAABwgAAIBlQAGgfACgrIASACQgFAygEAagAj7BlQAGgtABgcIASABQABAggJArgABFAgIASgEIAFA3IgTABgAi6BRIgEg0IASgBQAEAjAAASgAGhgLIAWgGQARA4ADAQIgWAEQgHgmgNgggABgAIIAWgCIAAgTIgVAAIAAgTIAVAAIAAgPIAUAAIAAAPIAWAAIAAATIgWAAIAAARIAYgEIACASQgqAIgZABgACvAYIAAgSIAYAAIAAgTIgYAAIAAgSIAYAAIAAgSIAVAAIAAASIAYAAIAAASIgYAAIAAATIAaAAIAAASgAhAgtQgTANghANIgLgSQAdgJATgMQgJgJgJgMQgJALgKAJIgMgNQALgJAHgJQAHgLAGgSIASAAIgBAHIAvAAIANAJQgMAbgTATQARALAaAJIgNASQgYgKgTgQgAhAhEIAAgBQAHgGALgPQAAgBAAgBQAAAAAAAAQAAgBgBAAQAAAAAAAAIgnAAQAMAPAKAKgAitgvIAMgQQANAJAQAPIgMAQQgTgRgKgHgABfg1IAAgUIA/AAIAAgNIg5AAIAAgUIA5AAIAAgOIAVAAIAAAOIA3AAIAAAUIg3AAIAAANIBBAAIAAAUgAl5g5QAAAAAAAAQgBAAAAAAQAAgBAAAAQAAgBAAgBIAAgxIABgCIBaAAQABABAAAAQABAAAAAAQABABAAAAQAAAAAAAAIAAAxQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAgAlmhLIA1AAIABgBIAAgQIg2AAgAnug5QgBAAAAAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAgxIACgCIBaAAQAAABABAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAAxQAAABAAABQAAAAAAABQgBAAAAAAQgBAAAAAAgAnchLIA1AAIABgBIAAgQIg2AAgAirhgIAMgRQAOAJARARIgOAPQgRgRgMgHg");
	this.shape.setTransform(-0.05,-0.1301);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(4));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#00FFFF").ss(3,1,1).p("Anzj5IPnAAQBkAAAABkIAAErQAABkhkAAIvnAAQhkAAAAhkIAAkrQAAhkBkAAg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#000066","#0066FF"],[0,1],0,35,0,-24.9).s().p("AnzD6QhkAAAAhkIAAkrQAAhkBkAAIPnAAQBkAAAABkIAAErQAABkhkAAg");

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#000066","#00FFFF"],[0,1],0,35,0,-24.9).s().p("AnzD6QhkAAAAhkIAAkrQAAhkBkAAIPnAAQBkAAAABkIAAErQAABkhkAAg");

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#FF00FF").ss(3,1,1).p("Anzj5IPnAAQBkAAAABkIAAErQAABkhkAAIvnAAQhkAAAAhkIAAkrQAAhkBkAAg");

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF00FF").s().p("AnzD6QhkAAAAhkIAAkrQAAhkBkAAIPnAAQBkAAAABkIAAErQAABkhkAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1,p:{rotation:0}}]}).to({state:[{t:this.shape_3,p:{rotation:0}},{t:this.shape_1,p:{rotation:0}}]},1).to({state:[{t:this.shape_3,p:{rotation:180}},{t:this.shape_1,p:{rotation:180}}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-61.5,-26.5,123,53);


(lib.mBtnPhasor = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ah+BpQAVgQAPgSQAJgNAKgTIgVAAQgjA1gxAZIgMgSQAagOATgQQANgLANgTIgYAAQgSAZgfATIgOgRQAWgNASgSQAKgMALgTIgjAAIAAgTICoAAIAAATIhvAAIgGAOIBsAAQABAAABAAQAAAAABABQAAAAABAAQAAAAAAAAQAFADAAAHQAABBgKANQgGAIgKADQgMAEgYgEIgBgZQAHAEAHABQAMACAJgKQAFgFAAgMQADgdgDgEIgCgBIgNAAQgWAzgqAfgACjBzIgBgaQAZAIAMAAQAHAAADgEQAHgEAAgHIAAiYQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAAAgBAAIirAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAAAAAABIAAC7IgXAAIAAjKQABgIAHAAIBPAAIAPgbIATAMIgHAPIBjAAQAIABAAAHIAACvQABARgMAHQgIAGgRAAQgQAAgYgFgAl+B1QgIgBgGgGQgHgHAAgHIAAgNIhWAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAgBIAAhMIACgCIDBAAQABAAAAABQABAAAAAAQABAAAAABQAAAAAAAAIAABMQAAABAAABQAAAAgBAAQAAABgBAAQAAAAgBAAIhWAAIAAABQABAFADAEQAEAEAEAAIBJAAIAGgDQACgCAAgPIAUAEIgFAcQgIAIgGAAgAl+BBIBEAAIAAgBIAAgNIhEAAgAnWBBIBDAAIAAgOIhDAAgAl+AiIBEAAIAAgOIhEAAgAnWAiIBDAAIAAgOIhDAAgAEPB0IAAgUIBrAAIAAgLIhaAAIAAgSIBaAAIAAgLIhQAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAgBAAAAIAAhAQAAgBAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIC3AAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAABIAABAQAAAAAAABQAAABgBAAQAAAAgBABQAAAAgBAAIhTAAIAAALIBcAAIAAASIhcAAIAAALIBsAAIAAAUgAGOAnIBAAAIABgBIAAgKIhBAAgAE8AnIA+AAIAAgLIg+AAgAGOAMIBBAAIAAgJIgBgBIhAAAgAE8ADIAAAJIA+AAIAAgKIg+AAQAAAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAgAj7A8IAcgRIAAhZIgbAAIAAgVIAbAAIAAgwIAXAAIAAAwIAYAAIAAAVIgYAAIAABKIAMgKIANASQgSAQguAZgABFBEQgEAAAAgEIAAhnQAAgBABAAQAAgBAAAAQABAAAAgBQABAAABAAIB2AAQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABIAABnQAAAEgDAAgABYgSIAAA/IABABIBOAAIABgBIAAg/IgBgBIhOAAIgBABgAmSgGIAAg3IhRAAQAAAAgBAAQAAAAgBAAQAAAAAAABQAAAAAAABIAAAiIgVAAIAAg0QAAgEAEAAIBkAAIAAgLIhWAAIAAgUIDDAAIAAAUIhXAAIAAALIBdAAIASAJQgBAUgHAcIgUgGIAFgcQAAgBAAAAQAAgBgBAAQAAAAgBgBQAAAAgBAAIhVAAIAAA3gAlwgIIAAgRIBCAAIAAARgAndgIIAAgRIBBAAIAAARgAENgVIAAgTIDuAAIAAATgAihgbQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBIAAhPQAAAAAAgBQAAgBABAAQAAAAABgBQAAAAABAAICFAAQABAAAAAAQABABAAAAQABAAAAABQAAABAAAAIAABPQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAgAiPgwIABABIBfAAIABgBIAAgMIhhAAgAiPhbIAAAMIBhAAIAAgMIgBgBIhfAAIgBABgAlwgjIAAgRIBAAAIAAARgAncgjIAAgRIBAAAIAAARgAEsgvQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAgBIAAg8IACgCICzAAQABAAAAABQABAAAAAAQABAAAAABQAAAAAAAAIAAA8QAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAgAE+g/ICOAAIABgBIAAgHIiPAAgAE+hXICPAAIAAgIIiPAAg");
	this.shape.setTransform(-0.05,-0.125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(4));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#00FFFF").ss(3,1,1).p("Anzj5IPnAAQBkAAAABkIAAErQAABkhkAAIvnAAQhkAAAAhkIAAkrQAAhkBkAAg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#000066","#0066FF"],[0,1],0,35,0,-24.9).s().p("AnzD6QhkAAAAhkIAAkrQAAhkBkAAIPnAAQBkAAAABkIAAErQAABkhkAAg");

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#000066","#00FFFF"],[0,1],0,35,0,-24.9).s().p("AnzD6QhkAAAAhkIAAkrQAAhkBkAAIPnAAQBkAAAABkIAAErQAABkhkAAg");

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#FF00FF").ss(3,1,1).p("Anzj5IPnAAQBkAAAABkIAAErQAABkhkAAIvnAAQhkAAAAhkIAAkrQAAhkBkAAg");

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF00FF").s().p("AnzD6QhkAAAAhkIAAkrQAAhkBkAAIPnAAQBkAAAABkIAAErQAABkhkAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1,p:{rotation:0}}]}).to({state:[{t:this.shape_3,p:{rotation:0}},{t:this.shape_1,p:{rotation:0}}]},1).to({state:[{t:this.shape_3,p:{rotation:180}},{t:this.shape_1,p:{rotation:180}}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-61.5,-26.5,123,53);


(lib.mBtnNSlit = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AFHB5IgEgYQBMAEAlgYQAlgaAJgwIAWAGQgHAegNATQgHALgIAHQgrAtheAAIgFAAgAi1BmQARgGAHgHQAFgFABgJIAAg+QAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAgBAAIgLAAIAAgSIAeAAQAEABAAAEIAABJIAAACIACACQAHAZArgBIACAAIAAgZIgqAAIAAgTIAqAAIAAgOIgoAAIAAgSIAoAAIAAgQIgqAAIAAgSIAqAAIAAgTIAVAAIAAATIAoAAIAAASIgoAAIAAAQIAnAAIAAASIgnAAIAAAOIAuAAIAAATIguAAIAAAYIAvgDIgGAWIhMABQgkgDgLgSQgFAHgKAHQgMAIgJABgAnpBfQBOACArgPQgSgRghgZQgWAIgdAEIgKgVQBLgJAcgnQgwAUhMAHIgHgXQBCgCApgPQgZgVgdgRQgNAGgRAEIgJgXQA5gKAWgcIAYAIIgDADIBZAAIAQAMQgKATgYAZQgPAPgnATIAWAGIgDAGIBJAAIAPAIQgJAhgTAVIgBACQgTAWgcAQQgsAWhcABgAmMAdIARAPQATAOANAOQAigUAQgkQAAgBAAAAQAAAAAAAAQgBAAAAAAQgBAAgBAAIhNAAQgIAIgLAGgAmuhOIARANQAVANAPAMQAlgUAQgWQABgFgDAAIhbAAIgNAJgAB1B2IAAhsIhqAAIAAgXIBqAAIAAhLIhaAAIAAgXIDNAAIAAAXIhbAAIAABLIBpAAIAAAXIhpAAIAABsgAjaB1IAAhsIgbAEIgGgTIARgCQAJgLAJgPQgRgSgTgKIAKgTIAIAFQAKgUAKgYIARAJQgHATgPAdIANAMQAJgUAHgSIATAFQgHAegfAqIATgDIgEgLIASgEQAGATADAZIgTADIgCgMIgJABIAABvgAEMBqQAegtAGgxIAVAEQgLBAgZAigAj7BlQAGgtABgbIASABQABAfgJArgAi6BSIgEg0IASgBQAEAjAAASgAF7BDIAAgYQAdAKAHgGQACgDAAgEIAAg3IhSAAIAAgVIAZAAIAAhDIAVAAIAABDIAkAAIAAhSIAXAAIAAAdIA6AAIAAAVIg6AAIAAAgIBEAAIAAAVIhEAAIAAA9QAAAPgNAIQgGADgJAAQgNAAgUgFgAFHAxQAQgLAKgNQAJgMAJgSIASALQgVAngbAWQgGgMgIgGgAEMgjIALgUQAUAIAZASIgLATQgbgSgSgHgAhAgsQgTAMghANIgLgRQAdgJATgMQgJgKgJgMQgJALgKAKIgMgOQALgJAHgJQAHgKAGgSIASAAIgBAHIAvAAIANAJQgMAagTAUQARALAaAJIgNARQgYgKgTgPgAhAhEIAAgBQAHgGALgPQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAIgnAAQAMAPAKAKgAitguIAMgQQANAJAQAPIgMAPQgTgQgKgHgAEVheIALgTQAWAKAZATIgMAUQgcgVgSgJgAirhgIAMgQQAOAJARAQIgOAPQgRgRgMgHg");
	this.shape.setTransform(-0.05,-0.1739);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(4));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#00FFFF").ss(3,1,1).p("Anzj5IPnAAQBkAAAABkIAAErQAABkhkAAIvnAAQhkAAAAhkIAAkrQAAhkBkAAg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#000066","#0066FF"],[0,1],0,35,0,-24.9).s().p("AnzD6QhkAAAAhkIAAkrQAAhkBkAAIPnAAQBkAAAABkIAAErQAABkhkAAg");

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#000066","#00FFFF"],[0,1],0,35,0,-24.9).s().p("AnzD6QhkAAAAhkIAAkrQAAhkBkAAIPnAAQBkAAAABkIAAErQAABkhkAAg");

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#FF00FF").ss(3,1,1).p("Anzj5IPnAAQBkAAAABkIAAErQAABkhkAAIvnAAQhkAAAAhkIAAkrQAAhkBkAAg");

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF00FF").s().p("AnzD6QhkAAAAhkIAAkrQAAhkBkAAIPnAAQBkAAAABkIAAErQAABkhkAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1,p:{rotation:0}}]}).to({state:[{t:this.shape_3,p:{rotation:0}},{t:this.shape_1,p:{rotation:0}}]},1).to({state:[{t:this.shape_3,p:{rotation:180}},{t:this.shape_1,p:{rotation:180}}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-61.5,-26.5,123,53);


(lib.mBtnDSlitD = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Al2BiIgBAAQgYALgbAGQgcAHguAAIgGgWQAzgBAbgIIAbgIQgTgMgVgPIAHgJIgnAAIAAgVICoAAIAQAOQgYAbgkATQAhALAvADIgIAWQg4gGgpgSgAl4BKQAggOAQgNIhZAAQAWARATAKgAGgBxIABgYQASAHAIABQAJADAHAAQADAAAHgEQABgEAAgEIAAiSIhEAAIAAgWIBEAAIAAgoIAXAAIAAAoIATAAIAAAWIgTAAIAACYQAAAQgMAHQgHAFgNAAQgRAAgcgJgAFHB1IAAgYQAbAJAHgEQAFgFAAgGIAAghIgRAOQgOALgRAJQgTALgPAGIgNgUQAwgRAdgYIADgDIhNAJIgDgWIAOgCIAAh5QABgGAEAAIAfAAQAFgLAAgJIAVAFIgDAPIAmAAQAGABAAAFIAABWIAKgdIAVAHQgKAdgVAhIAABCQgBAMgJAHQgIAEgNAAQgMAAgSgDgAEyAYIA8gGIAAgRIg8AAgAEygTIA8AAIAAgUIg8AAgAEyhNIAAARIA8AAIAAgRQAAgBAAAAQAAAAAAgBQAAAAgBAAQAAAAAAAAIg5AAIgCACgAAqB4IAAhtIgbADIgEgSIALgCQAKgKAMgTQgRgSgSgJIAKgSIAIAFQAKgTAJgZIASAJQgHATgPAcIANALQAIgTAGgSIAUAFQgHAcgjAuIAZgDIgEgQIASgEQAGAUADAbIgTADIgBgLIgMACIAABwgAizBmQARgGAHgIQAFgFABgJIAAg+QAAAAAAgBQAAAAAAAAQAAgBgBAAQAAAAgBAAIgLAAIAAgRIAeAAQAEABAAAEIAABIIAAACIACACQAHAaArgBIACAAIAAgaIgqAAIAAgSIAqAAIAAgOIgoAAIAAgTIAoAAIAAgQIgqAAIAAgRIAqAAIAAgTIAVAAIAAATIAoAAIAAARIgoAAIAAAQIAnAAIAAATIgnAAIAAAOIAuAAIAAASIguAAIAAAZIAvgEIgGAXIhMABQgkgDgLgSQgFAHgKAHQgMAIgJABgABaBkQAMgCAJgFQAWgLADgbIgmAAIAAgUICaAAIAAAUIg1AAIAAAeQAAAEACAEQAEAEAEAAIANAAIAGgDQACgDABgTIAVAEQgEAegDADQgIAIgGAAIggAAQgIgBgHgGQgGgHAAgGIAAgqIgWAAQgCAagNAQQgOAQgbAGgAjYB1IAAhtIgbAEIgGgSIARgCQAJgLAJgQQgRgSgTgKIAKgSIAIAFQAKgUAKgZIARAJQgHAUgPAcIANAMQAJgTAHgSIATAFQgHAdgfArIATgDIgEgLIASgEQAGATADAYIgTADIgCgMIgJABIAABwgAAKBlQAGgfACgrIASACQgFAygEAagAj5BlQAGgtABgcIASABQABAggJArgABHAgIASgEIAFA3IgTABgAi4BRIgEg0IASgBQAEAjAAASgAGjgLIAWgGQARA4ADAQIgWAEQgHgmgNgggABiAIIAWgCIAAgTIgVAAIAAgTIAVAAIAAgPIAUAAIAAAPIAWAAIAAATIgWAAIAAARIAYgEIACASQgqAIgZABgACxAYIAAgSIAYAAIAAgTIgYAAIAAgSIAYAAIAAgSIAVAAIAAASIAYAAIAAASIgYAAIAAATIAaAAIAAASgAlvAOQgHgBgBgGIAAhMIgGAGQgHgKgGgEQASgPAJgcIATAJIgEAJIAcAAIAHgSIATAIIgEAKIAdAAIAAATIggAAIAAAOIAeAAIAAARIgeAAIAAAPIAeAAIAAASIgeAAIAAAQIAgAAIAAARgAligGQAAABABAAQAAABAAAAQAAAAABABQAAAAAAAAIAaAAIAAgQIgcAAgAliglIAcAAIAAgPIgcAAgAlihRIAAAMIAcAAIAAgOIgaAAIgCACgAnhAOQgHgBAAgGIAAhEIgIAJQgIgKgGgDQAUgWAJgiIAUAHIgEAMIAbAAIAJgTIASAIQgBAFgDAGIAaAAIAAATIgeAAIAAAOIAaAAIAAARIgaAAIAAAPIAaAAIAAASIgaAAIAAAQIAgAAIAAARgAnTgGQAAABAAAAQAAABABAAQAAAAAAABQAAAAABAAIAaAAIAAgQIgcAAgAnTglIAcAAIAAgPIgcAAgAnThRIAAAMIAcAAIAAgOIgaAAIgCACgAg+gtQgTANghANIgLgSQAdgJATgMQgJgJgJgMQgJALgKAJIgMgNQALgJAHgJQAHgLAGgSIASAAIgBAHIAvAAIANAJQgMAbgTATQARALAaAJIgNASQgYgKgTgQgAg+hEIAAgBQAHgGALgPQAAgBAAgBQAAAAAAAAQAAgBgBAAQAAAAAAAAIgnAAQAMAPAKAKgAirgvIAMgQQANAJAQAPIgMAQQgTgRgKgHgABhg1IAAgUIA/AAIAAgNIg5AAIAAgUIA5AAIAAgOIAVAAIAAAOIA3AAIAAAUIg3AAIAAANIBBAAIAAAUgAiphgIAMgRQAOAJARARIgOAPQgRgRgMgHg");
	this.shape.setTransform(-0.25,-0.125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(4));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#00FFFF").ss(3,1,1).p("Anzj5IPnAAQBkAAAABkIAAErQAABkhkAAIvnAAQhkAAAAhkIAAkrQAAhkBkAAg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#000066","#0066FF"],[0,1],0,35,0,-24.9).s().p("AnzD6QhkAAAAhkIAAkrQAAhkBkAAIPnAAQBkAAAABkIAAErQAABkhkAAg");

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#000066","#00FFFF"],[0,1],0,35,0,-24.9).s().p("AnzD6QhkAAAAhkIAAkrQAAhkBkAAIPnAAQBkAAAABkIAAErQAABkhkAAg");

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#FF00FF").ss(3,1,1).p("Anzj5IPnAAQBkAAAABkIAAErQAABkhkAAIvnAAQhkAAAAhkIAAkrQAAhkBkAAg");

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF00FF").s().p("AnzD6QhkAAAAhkIAAkrQAAhkBkAAIPnAAQBkAAAABkIAAErQAABkhkAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1,p:{rotation:0}}]}).to({state:[{t:this.shape_3,p:{rotation:0}},{t:this.shape_1,p:{rotation:0}}]},1).to({state:[{t:this.shape_3,p:{rotation:180}},{t:this.shape_1,p:{rotation:180}}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-61.5,-26.5,123,53);


(lib.mBtnBG = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0000FF").s("#FFFF00").ss(3,1,1).rr(-66,-31,132,62,10);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.mBtnBG, new cjs.Rectangle(-67.5,-32.5,135,65), null);


(lib.btnZoom = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgtB/IBKj+IASAAIhKD+gAG9B5IAAg0Ig2AAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAAAAAAAIAAAnIgWAAIAAgzQgLAGgLAEIgKgUQAegIAZgPIg1AAIAAgTIBPAAIAMgLIhAAAQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIAAhDQAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAIAiAAIAAgJIg+AAIAAgVIA+AAIAAgMIAVAAIAAAMIBIAAIAAgMIAVAAIAAAMIA+AAIAAAVIg+AAIAAAJIAjAAQABAAABAAQAAAAABABQAAAAAAABQABAAAAABIAABDQAAABgBAAQAAABAAAAQgBABAAAAQgBAAgBAAIheAAIgKALICEAAIAAATIg3AAIACAAQAVAQAiAHIgMATIgUgIIAAAeQAAAMgLAHQgPAJgjgGIgCgXQAdAFAHgEQAFgEAAgGIAAgJIgBAAIg4AAIAAA0gAINAwQgUgMgOgMIhFAAQgPAMgVAMIA7AAIAAgSIAVAAIAAASIA7AAIAAAAgAF+gYIABABICRAAIABgBIAAgKIiTAAgAF+g9IAAALICTAAIAAgLIgBgBIiRAAIgBABgAGjhPIBIAAIAAgJIhIAAgAB9BmQALgDAJgGQATgNAEgUIgqAAIAAgVIArAAIAAgkIgiAAIAAgVIAiAAQgGgMgKgKIAOgJIgwAAIAAAvQAAAngJAkQgGAfgJAQIgWgKQAYgxgBhIIAAhhQABgHAHgBIDBAAQAJACAAAGIAAAyQAAAIgJABIggAAIANAJIgQAWIAqAAIAAAVIgiAAIAAAkIAqAAIAAAVIgqAAIAAA8IgWAAIAAg8Ig5AAQgHAoguAVgADAAnIA4AAIAAgkIg4AAgAD4gSIgIgGQAGgHAMgSIhVAAQAHAHANATIgJAFIBAAAgAB3haIAAASICiAAQADAAABgEIAAgOQgBgDgDAAIifAAQgBAAAAAAQgBAAAAABQgBAAAAABQAAAAAAABgAmiAmQgWA1gzAbIgQgQQA/geAMhBIgQAIQgGgOgKgPQgJAYgKANIgSgIIABAHQAAAmgIAaQgHAVgNAHQgMAFgcgKIABgXQAXAJAHgEQAHgDAEgSQAFgXgBghQgSAWgUAMIgQgQQAfgTAUgbQgDgTgGgQQgLAOgQAMIgPgPQAUgPANgRQgLgRgNgQIASgOQALAOAIANIABgCQAFgKAGgSIAUAHQgJAZgMATQAOAmAEArQAXgnAHgpIAVADIgGAcIAYAmQACgJABgKIAAg7Ig+AAIAAgWIA+AAIAAgUIAVAAIAAAUIBFAAIAAAWIhFAAIAAA7IAAAAIAAAFIAAALQAGA9BGAvIgTAOQg3gqgMgogAj1BlQARgGAIgHQAEgFABgKIAAg9QABgBAAAAQAAgBgBAAQAAAAAAAAQgBgBgBAAIgLAAIAAgRIAeAAQAFABAAAEIAABIIAAACIABACQAIAaArgBIACAAIAAgaIgrAAIAAgSIArAAIAAgOIgoAAIAAgSIAoAAIAAgQIgrAAIAAgSIArAAIAAgTIAUAAIAAATIApAAIAAASIgpAAIAAAQIAoAAIAAASIgoAAIAAAOIAuAAIAAASIguAAIAAAZIAvgDIgFAWIhNABQgjgDgMgSQgEAHgLAHQgMAIgJABgAkaB0IAAhtIgbAFIgGgTIARgCQAKgLAIgQQgRgRgTgLIAKgSIAIAFQALgUAJgYIASAJQgHATgPAcIANAMQAJgTAGgSIATAFQgGAdggArIATgDIgDgLIASgEQAFATAEAZIgTACIgCgLIgKABIAABvgAk7BkQAHgtAAgcIASABQACAggKArgAj5BQIgFg0IASgBQAEAkABARgAl0gOQgGARgGAMIgUgGQAVgjABgoIAUABQgBAOgCAOQASAXAQAYIgTANIgWglgAiAguQgTANghANIgLgRQAegJATgMQgKgKgJgMQgIALgLAKIgMgOQAMgJAGgJQAIgLAFgRIATAAIgCAHIAwAAIAMAJQgMAagSAUQAQALAaAJIgMARQgZgKgTgQgAiAhFIAAgBQAIgGAKgPQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAgBAAIgmAAQALAPAKAKgAjtgvIAMgRQANAKARAPIgNAPQgTgRgKgGgAjrhhIANgQQAOAIAQARIgNAPQgRgRgNgHg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(4));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#00FFFF").ss(3,1,1).p("AolkrIRLAAQBkAAAABkIAAGPQAABkhkAAIxLAAQhkAAAAhkIAAmPQAAhkBkAAg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#000066","#0066FF"],[0,1],-5,30,-5,-29.9).s().p("AolEsQhkAAAAhkIAAmPQAAhkBkAAIRLAAQBkAAAABkIAAGPQAABkhkAAg");

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#000066","#00FFFF"],[0,1],-5,30,-5,-29.9).s().p("AolEsQhkAAAAhkIAAmPQAAhkBkAAIRLAAQBkAAAABkIAAGPQAABkhkAAg");

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#FF00FF").ss(3,1,1).p("AolkrIRLAAQBkAAAABkIAAGPQAABkhkAAIxLAAQhkAAAAhkIAAmPQAAhkBkAAg");

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF00FF").s().p("AolEsQhkAAAAhkIAAmPQAAhkBkAAIRLAAQBkAAAABkIAAGPQAABkhkAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1,p:{rotation:0}}]}).to({state:[{t:this.shape_3,p:{rotation:0}},{t:this.shape_1,p:{rotation:0}}]},1).to({state:[{t:this.shape_3,p:{rotation:180}},{t:this.shape_1,p:{rotation:180}}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-66.5,-31.5,133,63);


(lib.btnEEII = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgvCAIBKj+IASAAIhKD+gAHTBfQguATgvAGIgIgVQAtgFAYgKIAHgBQgZgMgWgOIAIgVQAhAYAfANQAhgSARgTQACgCgEAAIh+AAIAAgWICSAAIAQAOQgTAggoAZQAmAKArAEIgLAXQg2gKgpgPgAEfBoIh9ANIgFgVIBDgHIAAgmIg7AAQAAAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhLQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAAAAAIA7AAIAAgWIg8ADIgGgWIAcgBQAMgXAJgaIAUAIQgHARgKAWIBBgDIgRgZIASgLQAaAkANAZIgSAJIgIgPIgrAEIAAAYIA2AAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAABLQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAIg2AAIAAAiIAggCQgJgPgBgEIAVgJQAUAqAEAQIgVAHIgFgQgAD2AfIAjAAIABgBIAAgoIgkAAgAC4AeIABABIAnAAIAAgpIgoAAgAjABoQAVgPAPgSQAKgOAKgTIgWAAQgiA1gxAZIgMgSQAagNATgRQAMgLANgTIgXAAQgSAZggAUIgNgRQAVgOASgSQALgLAKgUIgiAAIAAgTICnAAIAAATIhuAAIgHAPIBsAAQABAAABAAQABAAAAAAQABAAAAAAQABAAAAABQAEACAAAIQAABBgKAMQgFAIgLADQgMAEgYgEIgBgZQAIAEAHABQALACAJgJQAFgGABgLQACgegCgEIgDgBIgNAAQgVAzgqAfgABPBtIAAgZQAiALAKgEQAFgDABgFQACgHAAg3QAAAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBABIgbAAIAAADIgXgBIAAhJIABgFIAEgBIAvAAIAAggQAAgDgEAAIgwAAIAAgWIBGAAQAFAAAAACIAABQIgXAAIAAgCIgcAAIgBADIAAAbIAtAAQAFAAABAGIgDBXQgCANgKAHQgGAEgMADQgMAAgcgHgAm/B0QgIgBgHgGQgGgHAAgHIAAgMIhXAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAIAAhNIABgBIDBAAQABAAABAAQAAAAABAAQAAABAAAAQABAAAAAAIAABNQAAAAgBABQAAAAAAABQgBAAAAAAQgBABgBAAIhVAAIAAAAQAAAFADAEQAEAEAEAAIBJAAIAGgDQACgCAAgPIAVAFIgFAbQgIAIgHAAgAm/BBIBDAAIABgBIAAgOIhEAAgAoYBBIBEAAIAAgPIhEAAgAm/AhIBEAAIAAgNIhEAAgAoYAhIBEAAIAAgNIhEAAgAFLBoQANgVAEgWQAFgSAAgcIAAhxQgBgGAHgBIBYAAIAAgRIAWAAIAAARIBhAAIAAAWIgmAAIAAAXIAmAAIAAAUIgmAAIAAAfQgBAKgKAAIhoAAQgLAAAAgKIAAgfIgcAAIAAA9QgBA2gVAmgAGpgXQAAABAAAAQAAABAAAAQABABAAAAQABAAAAAAIBKAAQAFAAAAgDIAAgRIhRAAgAGpg8IBRAAIAAgXIhRAAgAF2hQIAAAUIAcAAIAAgXIgZAAQgBAAAAAAQgBAAAAABQgBAAAAABQAAAAAAABgAk9A7IAdgRIAAhZIgbAAIAAgVIAbAAIAAgvIAWAAIAAAvIAZAAIAAAVIgZAAIAABLIAMgKIAOARQgTAQgtAZgAnTgHIAAg2IhRAAQgBgBAAAAQgBAAAAABQAAAAAAAAQgBABAAAAIAAAiIgVAAIAAg0QABgEAEAAIBkAAIAAgLIhXAAIAAgUIDEAAIAAAUIhYAAIAAALIBdAAIATAJQgBAVgHAbIgVgGIAGgcQAAAAgBgBQAAAAAAgBQgBAAAAAAQgBAAAAAAIhWAAIAAA2gAmygJIAAgRIBDAAIAAARgAofgJIAAgRIBCAAIAAARgAjjgcQAAAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIAAhPQAAAAABgBQAAAAAAgBQABAAAAAAQABgBAAAAICFAAQABAAABABQAAAAABAAQAAABAAAAQABABAAAAIAABPQAAABgBAAQAAABAAAAQgBABAAAAQgBAAgBAAgAjQgxIABABIBeAAIABgBIAAgLIhgAAgAjQhcIAAAMIBgAAIAAgMIgBgBIheAAIgBABgAmygjIAAgRIBBAAIAAARgAoegjIAAgRIBBAAIAAARg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(4));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#00FFFF").ss(3,1,1).p("AolkrIRLAAQBkAAAABkIAAGPQAABkhkAAIxLAAQhkAAAAhkIAAmPQAAhkBkAAg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#000066","#0066FF"],[0,1],-5,30,-5,-29.9).s().p("AolEsQhkAAAAhkIAAmPQAAhkBkAAIRLAAQBkAAAABkIAAGPQAABkhkAAg");

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#000066","#00FFFF"],[0,1],-5,30,-5,-29.9).s().p("AolEsQhkAAAAhkIAAmPQAAhkBkAAIRLAAQBkAAAABkIAAGPQAABkhkAAg");

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#FF00FF").ss(3,1,1).p("AolkrIRLAAQBkAAAABkIAAGPQAABkhkAAIxLAAQhkAAAAhkIAAmPQAAhkBkAAg");

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF00FF").s().p("AolEsQhkAAAAhkIAAmPQAAhkBkAAIRLAAQBkAAAABkIAAGPQAABkhkAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1,p:{rotation:0}}]}).to({state:[{t:this.shape_3,p:{rotation:0}},{t:this.shape_1,p:{rotation:0}}]},1).to({state:[{t:this.shape_3,p:{rotation:180}},{t:this.shape_1,p:{rotation:180}}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-66.5,-31.5,133,63);


(lib.btn3D = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF00FF").s().p("Eh8/BGUMAAAiMnMD5/AAAMAAACMng");
	this.shape.setTransform(800,450);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,1600,900);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AMKEEQg5gigOgSQgCA2gGAQQgKAggdAAQgQAAgMgFQg+AAgXAGQgbAFgSAAQgyAAgXgXQgZggAAg5QAAhFADghQACglAAhBQAAgpgGggQgIgYAAgbQAAghBHgzQAcgTAAgNQAAgLgLgLQgJgKAAgNQAAgGANgJQAKgKAeAAQAuAAAlARQAmAUAAAZQAAAag7AQQiJAkAAAuIAAADIAIACQAEAAARgIQA/gfAiAAQA5AAAoAnQAjAnAABMQAAB9gDBHIADAAQAKAAAUAHQBdApBBAAQARAAAGgQQAFgYAAg7IAAjDQAAgcgNAAQgNAAgVAKQhEAgghAAQgkAAgVgUQgUgSAAgYQAAgxBFg6QAbgTAAgRQAAgNgLgMQgLgOAAgHQAAgJAKgIQALgLAVAAQAxAAAqAWQAkATAAASQAAAdgtAVQiHBBAAAaQAAAGAFAAQALAAAagOQBog2AqAAQAtAAAWAgQAUAkAABKIAACyQgCB5gTAkQgUAogjAAQhCAAh3hMgAH2DMQAAAZAwAAQALAAATgGIAUgEIADhuIAAgDQgTAEgUAGQgdAJgQAAIgPgBQgCAiAAAugAHxg0QALAYAAAcIAAA0IAUgLQAagPASAAQASAAAQADIAAhTQAAgcgiAAQgSAAg5AegA4HEvQgggiAAggQAAgUAOAAQAFAAAGAHQALAFAOAAQAiAABIgiIAqgXQgagOgmgZQgXgPgOgMIgWAdQgcAjgWAAQgMAAgIgOQgKgQgGgPIACBlQAAAwgTAfQgUAZgaAAQglAAgigqQg1hCAAhBQAAghAoguQAcgdAAgUQAAgFgVgPQgsgfABgeQAAgjArgtQAjghAAgQQAAgIgTgRQgxgmAAgVQAAgzA0AAQAmAAA4AzQAmAkAAAlQAAANgOAPIABBhQAJgEAJAAIAHACIAHABQAGAAAVgFQgCgHAAgIIgDhSQAAgrgQgVQgJgLAAgGQAAgZAcAAQAjAAAfAaQAWATgBBRIAAA2IAmgMIgBgLIAAhlQAAgvgSgWQgKgMAAgGQAAgcAfAAQAmAAAiAdQAQANAEAqQAMAAAkgLQAQgFAEgJQAGgPARAAQAmAAAYAVQAZARAAATQAAAVg7AMQg/AOg1ADIgCA0QAngHAfAAQA1AAAvAYQAeASAAAUQAAAcg8AAQhEAEhFAKQARArACBiIAFgFQAugrAAgVQAAgGgDgFQgCgEgBgEQAAgTAgAAQAZAAAWAKQARAKAAAQQAAAogxBFQgwBEhbA8QhTA9gyAAQgrAAgfgegA5zBUQg2AvAAAaQAAAsAiAAQAtAAAAgzIAChcIgbAagA2+gJIAHAFQAOASAAAXQAAAVgRAdQAYAKAQAAQAbAAAAgoIAAhOIhHAMgA4yBaQAFgIALgJQAxgsAMgkIgKABQgpAAgYgNIgEgCgA5sh7QgkAWABANQAAANAXASQAXAPAOAOQAEhCAFgzIgiAWgEAkmAEoQgigVgggSQh3A7hVAAQglAAgjgbQgpgcAAgSQAAgOAOAAIASACIAeABQBAAABRgdQgRgHgRgGQhNgcgtgJIgGgCQgcgGAAgdQgBgSAMgMQAMgMANAAIAJAAQAEAAAagFQCvgoBUAAQAsAAAqAbQApAgAAAnQAAAfg8AqQBYAnAAAjQAAA1g4AAQghAAgigfgEAi8ABoIhrAcQBEAJBFATQA9gfAAgVQABgRgXAAQgVAAgwANgAaSEVIgEgUQgUAQgfAPQhTAnhFAAQg1AAgkgUQgjgVABgrQAAg2BygIQAfgEAJgTQgYADgMAAQhQAAABg4IAAg6QgBgggKgPQgJgLAAgPQAAgcAiAAQAZAAAPANQAOgBAVgGQANgDAMgDQgBgKgCgEIgCgHIgTABQgrAAgigbQgcgXAAglQAAggBEg1QAXgSgBgJIgCgUQAAgiAnAAQAgAAAlAUQAbAOAAAZQAAAPghAOQh8A3AAAXQAAATAQAAQAkAABHgfQAwgUAZgPQgMgfgHgOQgGgHAAgFQAAgOARAAQAcAAA4AxQAoAkAAAhQAABGgzAAQgYAAgLgdIgNAHQgeAMgdAJIADAPQAngIARAAQAwAAAZAYQAaAYAABBQAAAcgFASQAHAKABANQAAAhgtADIgtABQAdAJAgAlQAiAoAAAoQAABDgwAAQgSAAgOgygAWGDkQgYAEABAFQAAARAtAAQAeAABEgUIARgFIgmgCIgYgBQgxAAgaACgAZHCNIAAABQABA3gVAUQAjgMAfgQIABAAIgIgTQgIgPAAgNQAAgDADgCQgRABgRADgAXYALIggAFQACAXAAAdQAAAaAdAAIANgCIAAhUIgMADgAZFgLIACBKIAtgJIAAgtQABgVgaAAIgWABgASLD6Qgwg/AAgLQAAgFAFgBQACAAAaAUQAiAZAOAAQAUAAAhhAQAag2AAgXQAAgGgNAAQgHAAglAPQgsATgLAAQgtgBAAgpQAAgOAhg5IARgfQgTgDgNgJQgSgKAAgNQAAgMAMgJQAPgPAMAAIALACQAGAAAdgQQAYgPAZgHQAag5AAgGQAAgUgLAAQgKAAgYATQgpAegPAAQgaAAgWgTQgTgRAAgVQAAgPANgJQAOgJAMAAIAOAFQAJAAA2gcQAfgRAYAAQAkAAAfAWQAaATAAAVQAAAZgcBVIABACQAVAQAAASQAAAcghAAIhSAVQgGARgRAhQABAFAFAAQA5gUAQAAQA9AAABBJQAAAugoBpQgyB8gqAAQgTAAg5hNgABqEBQhHg7AAgUQAAgCAFAAQADAAAHAEQBdAuAKAAQARAAAAgZIAAkgIgQADIgmAGIAHATQAeBNAABJQAABSg7AAQgRAAgJhGQgOh2gKg9QgQgCgNgEIAABLIABABQAWAUAAAaQAAAVgXAWIAACoQAAAogPARQgUATglAAQgrAAhDghIgogWIgKAJQgjAdgPAAQg5AAAAhAQAAgMALgHIAKgDQAMgEBRg+QghAMgQAAQgYAAgUgPQgSgNAAgMQAAghAfAAIAOgCIAAisQAAgigKg2QgEgVAAgUQAAgTAQgPQANgOAzgSQAMgEAAgGQAAgEgLgCIgYgCQgKgCAAgHQAAgJAOgHQAQgHAgAAQA3AAAZAPQAWAJAAAQQAAAWgwAKIhCAPQgpAIAAAVQAAAFACAFIACAAQAKAAAagLQBYghAmAAQApAAAXAgQALAVAFApIAGgBIAHABIAHACQAAgXAcAAQAHAAAKAMIAsgPQAagJAWgDQgDgvgMgkQgGgRAAgLQgBgaAjAAQAiAAAhAmQAUAZAGBRIAaALQAeARgBAUQABAag2ACIAAFHQAABjg1AAQgmAAhQhGgAi9EBQARADATAAQBSAAAAglIAAhCgAiCAWQgfAJgUABIAAAlQAlgMAugSQAQgHALAAIAAgXQgdAEgeAJgAiFhAQgeAJgSABIAAAfIAegKQAigNAXAAIAXABIAAghQgfAEgfAKgAi3iRIgKADQAGAOADARIAcgJQAggNAWAAQAQAAAPADQgBgTgDgJQgFgJgHAAQgWAAhKAWgAo/EyQgcgUAAgoQABgOADgSQACgNAAgLIgXAGIABAKQAAAogjAoQgnApgfAAQgfAAgUgVQgVgWAAgYQgBgXAOAAQAJADAFAAQAPAAAegSQAQgJAGgHQgjgBgWgLQgIgEgFgEIABADQAAAlgfAAQggAAgdgrQgggwAAgpIAAgBQgTANgTAFQAYAoA0BAQANARAAAOQAAAngfAAQgeAAgcgzQgeg5AAgyIACgOQhWgBAAhIQAAggA4hMQgFADgGAAQglAAAAg2QAAgbAKgiQAKgoAAgcQABgFgFgNQgEgLAAgIQAAgWAZAAQAiAAAWAiQAHALAFAAQADAAAJgNQAkgsAZAAQAcAAAWAcQATAXgCAiQAAAogXArQgMAVgXAdQARAOAYAjQAcArAAAmIAAAGIAEgEQAPgMAYgEQATgDAEgKIgPACQgYAAgOgIQgNgIAAgJQABgHAHgHQAMgLAJAAIAFADQAFAAAUgPIADgDIgDgIQgHgNgBgJIABgFQgVgDgNgIQgagNAAgQQAAgKANgKQANgIAOAAIAHABIAKACQAMAABKgTIAAgQQgTAEgOAAQgoAAgWgLQgWgLAAgPQAAgKAMgIQAJgHAMAAIAHABIAIACQAIAAAygRQgIgQAAgJQAAgaAhAAQAmAAAXATIAFAEQASgDAPAAQAqAAAhARQAYANAAAPQgBAWgqAAQgjAEgjAHIAAASQAXgDATAAQAuAAAmATQAaAPAAARQAAAYgwABIgYACQAPAKAEAMQAQAEANAJQATAPAAAPQAAAaggAAIgLADIAAAZQAOAEAMAHQATAOAAAQQAAAZgfAAIhzALQgWAAgOgIQgMgGAAgIQAAgHAHgGQAKgJAIAAIAJAAQAEAAAVgPIAAgWIgCABQgaAAgPgKQgNgGAAgJQAAgJAJgGQAKgLAJAAIAJAAQADAAAOgMIgHgVQgHgNgDgHIgqAHQghAIgYAEQAJAHAGAKQANAEAMAIQATAPAAAQQAAAZgfAAIgGABIAAAIQAAATgGANIAdgOQAMgGACAAQAFAAAAAGQAAAKgRAaQgYAggjAYQgdAUgVAAQggAAgWgSQgUgPgDgVQgMAPgUAAQgUAAgIghIgLALIgFAEQAYAkA8A5IABACQACgJAMgHQAMgHAOAAIAOAAQANAABbgnQA7gaAqAAQA2AAAtAYQAfARAAAVQAAAYgvADQAJAOAJATQAXAqAAAVQAAAdgSATQgQARgrAAQhDAAgfgVgAnxCsQACAFAAAHQAAAKgEAKIgCAWQAAAJAEAEQAFAEAPAAQAJAAAAgDIAAhIIgdAEgAr4A0QAAALARAAQAMAAAdgJIAXgIIghgCIgcgBQgUAAAAAJgAuzAAQgKAMAAAJQAAAOAMAAQATAAA6gnQgKgngHgVQgaAegkAigAvFhoIgCADQAegmAqgwQAlgmgBgMQAAgLgOAAQgWAAhGCQgEgirAEBIAAi0QhsALhGAAQhXAAAAhDQAAgoAfgkQAjgoCDhHIAEgCQglAEgaAAQg2AAgegPQgcgPgBgSQABgNAQgLQAPgJAQAAIAHABIAKABQAYAAClgqQBrgcBMAAQBAAAA2AcQAkAUAAAZQAAAhhDABQhcAEhcALQAdAcAABvQA3gIAjAAQBQAAAvAgQAkAZAAAdQAAAognAAQgcAAg6gFIhLgBQgSAAgjADIAAC5QAABPhHAAQg6AAAAhGgEglKgBOQg3AzgBAaQAAAKAPAAQAnAAA3gNQA5gOAxgKIAAg0QgBgxgQgbQhSAag8A0gAc0EdQAAgNAFgYQAcibAAjrQABgWgNgVQgNgUAAgJQAAglAoAAQAXAAAWAQQAIAGAEAIIAHABQAMAAAmgNIA+gUQgKgOgBgJQAAgwAzAAQAeAAAnAYQALAHAJAHQBEgNA2AAQBMAAAuAaQAsAYAAAXQAAAiglAAQgcAAghgFIgrgDQAMAOACAQQAwACApAUQAeAQAAATQAAAbg2ABIhCAEIgCApQABAIgCAGQAMANAAAOQAAATgTABQhLAAg6ADIhwACQg7AAAAgvIACgWQABgCAAgEQghgCgWgKQgQgIgFgKQgBBhgGBYQgHB6gIAuQgOAzgqAAQgwAAAAgogEAiZgA/IhFAJIgCAUQABANAOAAQAIAAAfgHQAngIAigEIACgfQgdADgdAFgAeyiWIAAAIIAAAuQADgGAIgFQALgGAOAAIAPAAQAHAAASgDQgEgYgKgTQgsAJgSAAgEAhGgC0QAMARAEAcIA3gMQAkgJAggFIgEgNQgKgPAAgKQg8AFhBAOgAv8ELQgYg7AAg0QAAgwAOAAQALAAAJAOQASAuAwBMQAKARAAAQQAAAtglAAQgZAAgYg3gAMlCVQgnhRgUgYQgIgFAAgEQAAgaAfAAQAdAAA4AwQAnAjAAAhQAAA4gnAAQgiAAgPggg");
	this.shape.setTransform(0,0.025);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFF00").ss(5,1,1).p("Ai1lCQA3AAAZAPQAWAJAAAQQAAAWgwAKIhCAPQgpAIAAAVQAAAFACAFIABAAQALAAAagLQBYghAmAAQApAAAWAgQAMAVAFApQAEgBACAAQADAAAEABQAFACADAAQAAgXAcAAQAHAAAKAMQARgGAagJQAagJAXgDQgEgvgMgkQgGgRAAgLQAAgaAiAAQAiAAAhAmQAUAZAGBRQANAFANAGQAeARAAAUQAAAag2ACIAAFHQAABjg1AAQgmAAhQhGQhHg7AAgUQAAgCAGAAQACAAAIAEQBdAuAJAAQARAAAAgZIAAkgQgIACgIABQgVAEgQACQADAKAEAJQAdBNAABJQAABSg7AAQgRAAgJhGQgOh2gKg9QgQgCgMgEIAABLQAAAAAAABQAWAUAAAaQAAAVgWAWIAACoQAAAogQARQgUATglAAQgsAAhCghQgYgNgQgJIgKAJQgjAdgQAAQg4AAAAhAQAAgMAKgHIALgDQALgEBSg+QghAMgQAAQgYAAgVgPQgRgNAAgMQAAghAfAAQAGAAAIgCIAAisQAAgigKg2QgEgVAAgUQAAgTAPgPQAOgOAzgSQAMgEAAgGQAAgEgLgCIgYgCQgKgCAAgHQAAgJANgHQARgHAgAAgAIQk2QAtAAAlARQAmAUAAAZQAAAag7AQQiJAkAAAuQAAABAAACIAIACQAFAAARgIQA+gfAiAAQA6AAAnAnQAjAnAABMQAAB9gCBHQACAAAAAAQALAAATAHQBdApBCAAQAQAAAGgQQAGgYAAg7IAAjDQAAgcgOAAQgNAAgVAKQhDAggiAAQgjAAgWgUQgTgSAAgYQAAgxBFg6QAbgTAAgRQAAgNgMgMQgLgOAAgHQAAgJAKgIQAMgLAUAAQAxAAArAWQAjATAAASQAAAdgtAVQiHBBAAAaQAAAGAFAAQAMAAAagOQBng2AqAAQAtAAAWAgQAUAkAABKIAACyQgCB5gTAkQgUAogjAAQhCAAh3hMQg5gigOgSQgCA2gFAQQgKAggeAAQgQAAgMgFQg+AAgXAGQgbAFgSAAQgyAAgWgXQgaggAAg5QAAhFADghQACglAAhBQAAgpgGggQgIgYAAgbQAAghBHgzQAcgTAAgNQAAgLgKgLQgKgKAAgNQAAgGANgJQAKgKAfAAgAH8A0QAIgFAMgGQAagPATAAQARAAAQADQAAgoAAgrQAAgcghAAQgTAAg5AeQALAYAAAcQAAAdAAAXgAR9kRIAOAFQAJAAA2gcQAfgRAYAAQAkAAAgAWQAZATAAAVQAAAZgcBVQABABAAABQAVAQAAASQAAAcghAAIhSAVQgFARgRAhQAAAFAFAAQA5gUAQAAQA+AAAABJQAAAugoBpQgxB8grAAQgTAAg5hNQgwg/AAgLQAAgFAGgBQABAAAaAUQAiAZAPAAQATAAAihAQAag2AAgXQgBgGgNAAQgHAAglAPQgsATgLAAQgtgBAAgpQAAgOAhg5QALgSAHgNQgUgDgNgJQgSgKAAgNQAAgMAMgJQAQgPAMAAIALACQAFAAAdgQQAYgPAZgHQAag5AAgGQAAgUgLAAQgKAAgYATQgpAegPAAQgaAAgWgTQgTgRAAgVQAAgPANgJQAOgJAMAAgAXflHQAhAAAkAUQAbAOAAAZQAAAPghAOQh8A3AAAXQAAATAQAAQAkAABHgfQAwgUAZgPQgMgfgHgOQgGgHAAgFQAAgOARAAQAcAAA4AxQAoAkAAAhQAABGgzAAQgXAAgMgdQgGAEgHADQgeAMgdAJQACAHABAIQAngIARAAQAxAAAYAYQAaAYAABBQAAAcgFASQAIAKAAANQAAAhgtADQgXAAgWABQAeAJAfAlQAiAoAAAoQAABDgwAAQgSAAgNgyQgDgKgCgKQgUAQgfAPQhTAnhFAAQg1AAgkgUQgigVAAgrQAAg2BzgIQAegEAJgTQgYADgMAAQhPAAAAg4IAAg6QAAgggLgPQgJgLAAgPQAAgcAiAAQAZAAAPANQAOgBAVgGQAOgDALgDQgBgKgBgEQgBgEgBgDQgKABgJAAQgsAAgigbQgbgXAAglQAAggBDg1QAXgSAAgJQAAgGgDgOQAAgiAnAAgAf+h0QgEgYgJgTQgsAJgTAAQAAAEAAAEQAAAYAAAWQAEgGAHgFQAMgGAOAAIAOAAQAHAAASgDgEAg8gFEQAeAAAnAYQAMAHAIAHQBEgNA2AAQBNAAAtAaQAsAYAAAXQAAAiglAAQgcAAghgFQgTgCgYgBQAMAOACAQQAwACAqAUQAdAQAAATQAAAbg2ABQghABghADIgBApQAAAIgCAGQANANAAAOQAAATgUABQhKAAg7ADQhSACgdAAQg8AAAAgvQAAgKACgMQABgCAAgEQghgCgWgKQgQgIgFgKQgBBhgGBYQgHB6gIAuQgOAzgqAAQgwAAAAgoQAAgNAFgYQAdibAAjrQAAgWgNgVQgNgUAAgJQAAglAoAAQAXAAAWAQQAIAGAFAIQADABADAAQANAAAlgNQAhgLAegJQgLgOAAgJQAAgwAyAAgEAjSgChQgCgHgDgGQgJgPgBgKQg8AFhBAOQAMARAEAcQAZgFAegHQAlgJAggFgEAjRgAoIACgfQgdADgcAFQgmAGgfADQgCANAAAHQAAANAOAAQAJAAAegHQAngIAigEgAZ1A2IAAgtQAAgVgaAAQgJAAgNABQACAgABAqQAbgGASgDgAfdBKIAIAAQAFAAAZgFQCvgoBVAAQArAAAqAbQApAgAAAnQAAAfg8AqQBYAnAAAjQAAA1g4AAQggAAgjgfQghgVgggSQh4A7hVAAQgkAAgkgbQgpgcAAgSQAAgOAOAAQAGAAAMACQAQABAOAAQBAAABRgdQgQgHgRgGQhOgcgtgJQgDgBgCgBQgdgGAAgdQAAgSAMgMQAMgMANAAgEAhSACEQBDAJBFATQA+gfAAgVQAAgRgXAAQgVAAgvANQg+AQgtAMgAZ3C9QgFgLgEgIQgIgPAAgNQAAgDADgCQgRABgQADQAAABAAAAQAAA3gVAUQAjgMAggQgAXkBcQAAgyAAgiQgGABgGACQgUAEgLABQACAXAAAdQAAAaAcAAQAEAAAJgCgAWcD+QAeAABEgUQAIgCAJgDQgRgBgVgBQgWgBgCAAQgxAAgaACQgXAEAAAFQAAARAtAAgAMBAJQAdAAA4AwQAnAjAAAhQAAA4gnAAQgiAAgPggQgnhRgTgYQgJgFAAgEQAAgaAfAAgAJZDbQAAgsAChCQAAgCAAgBQgTAEgUAGQgdAJgQAAQgIAAgHgBQgCAiAAAuQAAAZAwAAQALAAAUgGQAKgDAKgBgEglrgD1QADAAAEABQAGABAEAAQAXAACmgqQBrgcBLAAQBBAAA2AcQAkAUAAAZQAAAhhDABQhdAEhcALQAeAcAABvQA2gIAkAAQBQAAAvAgQAkAZAAAdQAAAogoAAQgbAAg6gFQgpgBgiAAQgSAAgjADIAAC5QAABPhHAAQg7AAAAhGIAAi0QhrALhGAAQhXAAAAhDQAAgoAegkQAjgoCEhHQACgBABgBQgkAEgaAAQg2AAgegPQgdgPAAgSQAAgNARgLQAOgJARAAgEgisgAcIAAg0QAAgxgRgbQhRAag8A0Qg4AzAAAaQAAAKAPAAQAnAAA3gNQA5gOAwgKgA6sk8QAnAAA4AzQAmAkAAAlQAAANgPAPIACBhQAIgEAKAAQACAAAEACQAEABAEAAQAGAAAVgFQgCgHAAgIIgDhSQAAgrgQgVQgJgLAAgGQAAgZAcAAQAjAAAfAaQAVATAABRIAAA2QARgFAVgHQgBgFAAgGIAAhlQAAgvgSgWQgKgMAAgGQAAgcAfAAQAmAAAiAdQAPANAFAqQAMAAAkgLQAQgFAEgJQAGgPARAAQAmAAAYAVQAZARAAATQAAAVg7AMQhAAOg0ADIgCA0QAmgHAgAAQA1AAAuAYQAeASAAAUQAAAcg7AAQhEAEhFAKQARArACBiQACgCACgDQAvgrAAgVQAAgGgDgFQgDgEAAgEQAAgTAfAAQAaAAAVAKQASAKAAAQQAAAogxBFQgwBEhcA8QhTA9gxAAQgrAAgfgeQgggiAAggQAAgUANAAQAFAAAHAHQALAFAOAAQAiAABHgiQAWgLAVgMQgagOgmgZQgYgPgNgMQgLAOgMAPQgbAjgWAAQgMAAgIgOQgLgQgFgPIACBlQAAAwgTAfQgUAZgaAAQglAAgigqQg1hCAAhBQAAghAoguQAcgdAAgUQAAgFgWgPQgrgfAAgeQAAgjAsgtQAjghAAgQQAAgIgTgRQgxgmAAgVQAAgzAzAAgA5TgcQADhCAGgzQgOAKgVAMQgjAWAAANQAAANAYASQAXAPAOAOgA4yBaQAFgIALgJQAwgsAMgkQgFABgEAAQgqAAgXgNQgCgBgCgBgA2+gJQADACADADQAPASAAAXQAAAVgRAdQAYAKAPAAQAcAAAAgoIAAhOQgnAHggAFgAvqkzQAiAAAWAiQAHALAFAAQADAAAIgNQAkgsAaAAQAcAAAWAcQATAXgCAiQAAAogYArQgMAVgWAdQARAOAYAjQAcArAAAmQAAAEAAACQACgCACgCQAPgMAYgEQATgDAEgKIgPACQgYAAgPgIQgMgIAAgJQAAgHAIgHQAMgLAJAAIAFADQAEAAAUgPQACgCACgBQgBgEgCgEQgIgNAAgJQAAgDABgCQgVgDgNgIQgagNAAgQQAAgKANgKQANgIANAAQACAAAFABQAGACAEAAQAMAABLgTIAAgQQgTAEgOAAQgoAAgXgLQgVgLAAgPQAAgKALgIQAKgHAMAAQACAAAEABQAFACADAAQAJAAAygRQgIgQAAgJQAAgaAhAAQAlAAAXATQADACADACQASgDAPAAQApAAAiARQAXANAAAPQAAAWgqAAQgjAEgjAHIAAASQAWgDAUAAQAuAAAmATQAaAPAAARQAAAYgwABQgMABgMABQAOAKAFAMQAPAEANAJQATAPAAAPQAAAagfAAIgLADIAAAZQAOAEALAHQAUAOAAAQQAAAZgfAAIhzALQgXAAgNgIQgMgGAAgIQAAgHAHgGQAKgJAIAAIAJAAQAEAAAVgPIAAgWIgDABQgZAAgPgKQgNgGAAgJQAAgJAIgGQALgLAJAAIAIAAQAEAAAOgMQgDgKgEgLQgIgNgCgHQgVADgVAEQghAIgZAEQAKAHAGAKQANAEAMAIQATAPAAAQQAAAZgfAAIgGABIAAAIQAAATgHANQAOgGAPgIQAMgGADAAQAFAAAAAGQAAAKgRAaQgYAggjAYQgeAUgUAAQggAAgXgSQgTgPgDgVQgMAPgVAAQgTAAgJghQgFAFgFAGQgDACgCACQAYAkA8A5QABACAAAAQACgJAMgHQAMgHAOAAIAOAAQAMAABcgnQA7gaAqAAQA2AAAtAYQAfARAAAVQAAAYgvADQAJAOAJATQAXAqAAAVQAAAdgSATQgRARgqAAQhDAAgfgVQgcgUAAgoQAAgOADgSQADgNAAgLQgMAEgLACQABAFAAAFQAAAogkAoQgmApgfAAQgfAAgUgVQgWgWAAgYQAAgXAOAAQAJADAFAAQAPAAAegSQAQgJAGgHQgkgBgVgLQgIgEgFgEQABACAAABQAAAlgfAAQggAAgdgrQgggwAAgpIAAgBQgTANgTAFQAYAoA0BAQANARAAAOQAAAngfAAQgeAAgcgzQgeg5AAgyQAAgHABgHQhVgBAAhIQAAggA4hMQgFADgGAAQglAAAAg2QAAgbAKgiQAKgoAAgcQAAgFgEgNQgEgLAAgIQAAgWAZAAgAvHhlQAegmApgwQAlgmAAgMQAAgLgOAAQgWAAhGCQQgBACgBABgAtkgEQgKgngHgVQgaAegkAiQgKAMAAAJQAAAOAMAAQATAAA6gngAi4hvQAMgEAQgFQAggNAWAAQAQAAAPADQgBgTgDgJQgGgJgHAAQgVAAhKAWQgFACgFABQAGAOADARgAi1gXQAMgFARgFQAjgNAXAAQAMAAALABIAAghQggAEgfAKQgdAJgSABgAhHCdIh2BkQARADATAAQBSAAAAglgAi1BFQAkgMAvgSQAQgHALAAIAAgXQgeAEgeAJQgfAJgTABgAnxCsQACAFAAAHQAAAKgEAKQgCAOAAAIQAAAJAEAEQAFAEAPAAQAJAAAAgDIAAhIQgOACgPACgArnA/QAMAAAdgJQALgEALgEQgOgBgSgBQgSgBgKAAQgUAAAAAJQAAALARAAgAwGBsQALAAAJAOQASAuAwBMQAKARAAAQQAAAtglAAQgZAAgYg3QgYg7AAg0QAAgwAOAAgA6HDJQAtAAAAgzQABgxABgrQgMAMgQAOQg1AvAAAaQAAAsAiAAg");
	this.shape_1.setTransform(0,0.025);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AMKEEQg5gigOgSQgCA2gGAQQgKAggdAAQgQAAgMgFQg+AAgXAGQgbAFgSAAQgyAAgXgXQgZggAAg5QAAhFADghQACglAAhBQAAgpgGggQgIgYAAgbQAAghBHgzQAcgTAAgNQAAgLgLgLQgJgKAAgNQAAgGANgJQAKgKAeAAQAuAAAlARQAmAUAAAZQAAAag7AQQiJAkAAAuIAAADIAIACQAEAAARgIQA/gfAiAAQA5AAAoAnQAjAnAABMQAAB9gDBHIADAAQAKAAAUAHQBdApBBAAQARAAAGgQQAFgYAAg7IAAjDQAAgcgNAAQgNAAgVAKQhEAgghAAQgkAAgVgUQgUgSAAgYQAAgxBFg6QAbgTAAgRQAAgNgLgMQgLgOAAgHQAAgJAKgIQALgLAVAAQAxAAAqAWQAkATAAASQAAAdgtAVQiHBBAAAaQAAAGAFAAQALAAAagOQBog2AqAAQAtAAAWAgQAUAkAABKIAACyQgCB5gTAkQgUAogjAAQhCAAh3hMgAH2DMQAAAZAwAAQALAAATgGIAUgEIADhuIAAgDQgTAEgUAGQgdAJgQAAIgPgBQgCAiAAAugAHxg0QALAYAAAcIAAA0IAUgLQAagPASAAQASAAAQADIAAhTQAAgcgiAAQgSAAg5AegA4HEvQgggiAAggQAAgUAOAAQAFAAAGAHQALAFAOAAQAiAABIgiIAqgXQgagOgmgZQgXgPgOgMIgWAdQgcAjgWAAQgMAAgIgOQgKgQgGgPIACBlQAAAwgTAfQgUAZgaAAQglAAgigqQg1hCAAhBQAAghAoguQAcgdAAgUQAAgFgVgPQgsgfABgeQAAgjArgtQAjghAAgQQAAgIgTgRQgxgmAAgVQAAgzA0AAQAmAAA4AzQAmAkAAAlQAAANgOAPIABBhQAJgEAJAAIAHACIAHABQAGAAAVgFQgCgHAAgIIgDhSQAAgrgQgVQgJgLAAgGQAAgZAcAAQAjAAAfAaQAWATgBBRIAAA2IAmgMIgBgLIAAhlQAAgvgSgWQgKgMAAgGQAAgcAfAAQAmAAAiAdQAQANAEAqQAMAAAkgLQAQgFAEgJQAGgPARAAQAmAAAYAVQAZARAAATQAAAVg7AMQg/AOg1ADIgCA0QAngHAfAAQA1AAAvAYQAeASAAAUQAAAcg8AAQhEAEhFAKQARArACBiIAFgFQAugrAAgVQAAgGgDgFQgCgEgBgEQAAgTAgAAQAZAAAWAKQARAKAAAQQAAAogxBFQgwBEhbA8QhTA9gyAAQgrAAgfgegA5zBUQg2AvAAAaQAAAsAiAAQAtAAAAgzIAChcIgbAagA2+gJIAHAFQAOASAAAXQAAAVgRAdQAYAKAQAAQAbAAAAgoIAAhOIhHAMgA4yBaQAFgIALgJQAxgsAMgkIgKABQgpAAgYgNIgEgCgA5sh7QgkAWABANQAAANAXASQAXAPAOAOQAEhCAFgzIgiAWgEAkmAEoQgigVgggSQh3A7hVAAQglAAgjgbQgpgcAAgSQAAgOAOAAIASACIAeABQBAAABRgdQgRgHgRgGQhNgcgtgJIgGgCQgcgGAAgdQgBgSAMgMQAMgMANAAIAJAAQAEAAAagFQCvgoBUAAQAsAAAqAbQApAgAAAnQAAAfg8AqQBYAnAAAjQAAA1g4AAQghAAgigfgEAi8ABoIhrAcQBEAJBFATQA9gfAAgVQABgRgXAAQgVAAgwANgAaSEVIgEgUQgUAQgfAPQhTAnhFAAQg1AAgkgUQgjgVABgrQAAg2BygIQAfgEAJgTQgYADgMAAQhQAAABg4IAAg6QgBgggKgPQgJgLAAgPQAAgcAiAAQAZAAAPANQAOgBAVgGQANgDAMgDQgBgKgCgEIgCgHIgTABQgrAAgigbQgcgXAAglQAAggBEg1QAXgSgBgJIgCgUQAAgiAnAAQAgAAAlAUQAbAOAAAZQAAAPghAOQh8A3AAAXQAAATAQAAQAkAABHgfQAwgUAZgPQgMgfgHgOQgGgHAAgFQAAgOARAAQAcAAA4AxQAoAkAAAhQAABGgzAAQgYAAgLgdIgNAHQgeAMgdAJIADAPQAngIARAAQAwAAAZAYQAaAYAABBQAAAcgFASQAHAKABANQAAAhgtADIgtABQAdAJAgAlQAiAoAAAoQAABDgwAAQgSAAgOgygAWGDkQgYAEABAFQAAARAtAAQAeAABEgUIARgFIgmgCIgYgBQgxAAgaACgAZHCNIAAABQABA3gVAUQAjgMAfgQIABAAIgIgTQgIgPAAgNQAAgDADgCQgRABgRADgAXYALIggAFQACAXAAAdQAAAaAdAAIANgCIAAhUIgMADgAZFgLIACBKIAtgJIAAgtQABgVgaAAIgWABgASLD6Qgwg/AAgLQAAgFAFgBQACAAAaAUQAiAZAOAAQAUAAAhhAQAag2AAgXQAAgGgNAAQgHAAglAPQgsATgLAAQgtgBAAgpQAAgOAhg5IARgfQgTgDgNgJQgSgKAAgNQAAgMAMgJQAPgPAMAAIALACQAGAAAdgQQAYgPAZgHQAag5AAgGQAAgUgLAAQgKAAgYATQgpAegPAAQgaAAgWgTQgTgRAAgVQAAgPANgJQAOgJAMAAIAOAFQAJAAA2gcQAfgRAYAAQAkAAAfAWQAaATAAAVQAAAZgcBVIABACQAVAQAAASQAAAcghAAIhSAVQgGARgRAhQABAFAFAAQA5gUAQAAQA9AAABBJQAAAugoBpQgyB8gqAAQgTAAg5hNgABqEBQhHg7AAgUQAAgCAFAAQADAAAHAEQBdAuAKAAQARAAAAgZIAAkgIgQADIgmAGIAHATQAeBNAABJQAABSg7AAQgRAAgJhGQgOh2gKg9QgQgCgNgEIAABLIABABQAWAUAAAaQAAAVgXAWIAACoQAAAogPARQgUATglAAQgrAAhDghIgogWIgKAJQgjAdgPAAQg5AAAAhAQAAgMALgHIAKgDQAMgEBRg+QghAMgQAAQgYAAgUgPQgSgNAAgMQAAghAfAAIAOgCIAAisQAAgigKg2QgEgVAAgUQAAgTAQgPQANgOAzgSQAMgEAAgGQAAgEgLgCIgYgCQgKgCAAgHQAAgJAOgHQAQgHAgAAQA3AAAZAPQAWAJAAAQQAAAWgwAKIhCAPQgpAIAAAVQAAAFACAFIACAAQAKAAAagLQBYghAmAAQApAAAXAgQALAVAFApIAGgBIAHABIAHACQAAgXAcAAQAHAAAKAMIAsgPQAagJAWgDQgDgvgMgkQgGgRAAgLQgBgaAjAAQAiAAAhAmQAUAZAGBRIAaALQAeARgBAUQABAag2ACIAAFHQAABjg1AAQgmAAhQhGgAi9EBQARADATAAQBSAAAAglIAAhCgAiCAWQgfAJgUABIAAAlQAlgMAugSQAQgHALAAIAAgXQgdAEgeAJgAiFhAQgeAJgSABIAAAfIAegKQAigNAXAAIAXABIAAghQgfAEgfAKgAi3iRIgKADQAGAOADARIAcgJQAggNAWAAQAQAAAPADQgBgTgDgJQgFgJgHAAQgWAAhKAWgAo/EyQgcgUAAgoQABgOADgSQACgNAAgLIgXAGIABAKQAAAogjAoQgnApgfAAQgfAAgUgVQgVgWAAgYQgBgXAOAAQAJADAFAAQAPAAAegSQAQgJAGgHQgjgBgWgLQgIgEgFgEIABADQAAAlgfAAQggAAgdgrQgggwAAgpIAAgBQgTANgTAFQAYAoA0BAQANARAAAOQAAAngfAAQgeAAgcgzQgeg5AAgyIACgOQhWgBAAhIQAAggA4hMQgFADgGAAQglAAAAg2QAAgbAKgiQAKgoAAgcQABgFgFgNQgEgLAAgIQAAgWAZAAQAiAAAWAiQAHALAFAAQADAAAJgNQAkgsAZAAQAcAAAWAcQATAXgCAiQAAAogXArQgMAVgXAdQARAOAYAjQAcArAAAmIAAAGIAEgEQAPgMAYgEQATgDAEgKIgPACQgYAAgOgIQgNgIAAgJQABgHAHgHQAMgLAJAAIAFADQAFAAAUgPIADgDIgDgIQgHgNgBgJIABgFQgVgDgNgIQgagNAAgQQAAgKANgKQANgIAOAAIAHABIAKACQAMAABKgTIAAgQQgTAEgOAAQgoAAgWgLQgWgLAAgPQAAgKAMgIQAJgHAMAAIAHABIAIACQAIAAAygRQgIgQAAgJQAAgaAhAAQAmAAAXATIAFAEQASgDAPAAQAqAAAhARQAYANAAAPQgBAWgqAAQgjAEgjAHIAAASQAXgDATAAQAuAAAmATQAaAPAAARQAAAYgwABIgYACQAPAKAEAMQAQAEANAJQATAPAAAPQAAAaggAAIgLADIAAAZQAOAEAMAHQATAOAAAQQAAAZgfAAIhzALQgWAAgOgIQgMgGAAgIQAAgHAHgGQAKgJAIAAIAJAAQAEAAAVgPIAAgWIgCABQgaAAgPgKQgNgGAAgJQAAgJAJgGQAKgLAJAAIAJAAQADAAAOgMIgHgVQgHgNgDgHIgqAHQghAIgYAEQAJAHAGAKQANAEAMAIQATAPAAAQQAAAZgfAAIgGABIAAAIQAAATgGANIAdgOQAMgGACAAQAFAAAAAGQAAAKgRAaQgYAggjAYQgdAUgVAAQggAAgWgSQgUgPgDgVQgMAPgUAAQgUAAgIghIgLALIgFAEQAYAkA8A5IABACQACgJAMgHQAMgHAOAAIAOAAQANAABbgnQA7gaAqAAQA2AAAtAYQAfARAAAVQAAAYgvADQAJAOAJATQAXAqAAAVQAAAdgSATQgQARgrAAQhDAAgfgVgAnxCsQACAFAAAHQAAAKgEAKIgCAWQAAAJAEAEQAFAEAPAAQAJAAAAgDIAAhIIgdAEgAr4A0QAAALARAAQAMAAAdgJIAXgIIghgCIgcgBQgUAAAAAJgAuzAAQgKAMAAAJQAAAOAMAAQATAAA6gnQgKgngHgVQgaAegkAigAvFhoIgCADQAegmAqgwQAlgmgBgMQAAgLgOAAQgWAAhGCQgEgirAEBIAAi0QhsALhGAAQhXAAAAhDQAAgoAfgkQAjgoCDhHIAEgCQglAEgaAAQg2AAgegPQgcgPgBgSQABgNAQgLQAPgJAQAAIAHABIAKABQAYAAClgqQBrgcBMAAQBAAAA2AcQAkAUAAAZQAAAhhDABQhcAEhcALQAdAcAABvQA3gIAjAAQBQAAAvAgQAkAZAAAdQAAAognAAQgcAAg6gFIhLgBQgSAAgjADIAAC5QAABPhHAAQg6AAAAhGgEglKgBOQg3AzgBAaQAAAKAPAAQAnAAA3gNQA5gOAxgKIAAg0QgBgxgQgbQhSAag8A0gAc0EdQAAgNAFgYQAcibAAjrQABgWgNgVQgNgUAAgJQAAglAoAAQAXAAAWAQQAIAGAEAIIAHABQAMAAAmgNIA+gUQgKgOgBgJQAAgwAzAAQAeAAAnAYQALAHAJAHQBEgNA2AAQBMAAAuAaQAsAYAAAXQAAAiglAAQgcAAghgFIgrgDQAMAOACAQQAwACApAUQAeAQAAATQAAAbg2ABIhCAEIgCApQABAIgCAGQAMANAAAOQAAATgTABQhLAAg6ADIhwACQg7AAAAgvIACgWQABgCAAgEQghgCgWgKQgQgIgFgKQgBBhgGBYQgHB6gIAuQgOAzgqAAQgwAAAAgogEAiZgA/IhFAJIgCAUQABANAOAAQAIAAAfgHQAngIAigEIACgfQgdADgdAFgAeyiWIAAAIIAAAuQADgGAIgFQALgGAOAAIAPAAQAHAAASgDQgEgYgKgTQgsAJgSAAgEAhGgC0QAMARAEAcIA3gMQAkgJAggFIgEgNQgKgPAAgKQg8AFhBAOgAv8ELQgYg7AAg0QAAgwAOAAQALAAAJAOQASAuAwBMQAKARAAAQQAAAtglAAQgZAAgYg3gAMlCVQgnhRgUgYQgIgFAAgEQAAgaAfAAQAdAAA4AwQAnAjAAAhQAAA4gnAAQgiAAgPggg");
	this.shape_2.setTransform(0,0.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(-251,-36,502,72.1), null);


(lib.theSlider = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//老師寫的slider，不要修改
		//外部使用變數名稱
		//maximum    最大值number
		//minimum    最小值number
		//value      現在值number
		var sl=this;
		//內部變數
		sl.len = 150;
		sl.min = 0;
		sl.max = 100;
		sl.val = 0;
		sl.btnS.alpha=0;
		sl.digitN=0;
		//event
		sl.on('mousedown',function(e){
									//按下設值
									var localX = e.stageX - sl.x;
									setValue(sl,localX);
								});
		sl.on('pressmove',function(e){
									//拖曳設值
									var localX = e.stageX - sl.x;
									setValue(sl,localX);
								});
		//setValue from localX
		var setValue = function(who,localX){
			var lx=localX;
			if(lx<0){lx=0;}
			else if(lx>who.len){lx=who.len;}
			who.btn.x=lx;
			who.val = who.min+lx/who.len*(who.max-who.min);
			who.valueText.text = digitN(who.val , who.digitN);
		}
		//digitN 將數字取到小數點第N位，變成文字傳回
		var digitN = function( num, n){
			var pn=num<0?"-":"";
			num=Math.abs(num);
			if(n>0){
				var str = String(Math.round(num*Math.pow(10,n)));
				if(str.length<(n+1)){//補位數
					var tempN=n+1-str.length;
					for(var i=0;i<tempN;i++){
						str = "0"+str;
					}
				}
				str = pn+str.substr(0, str.length-n) + "." + str.substr(str.length-n);
			}else{
				var str = pn+String(Math.round(num));
			}
			return str;
		}
		//set value form js
		Object.defineProperty(sl, 'value', {
										    get: function() {
													return sl.val;
											    },
											set: function(_val) {
											        sl.val=_val;
												    if(sl.val>sl.max){sl.val=sl.max;}
												    else if(sl.val<sl.min){sl.val=sl.min;}
												    sl.btn.x=sl.len*(sl.val-sl.min)/(sl.max-sl.min);
													sl.valueText.text = digitN(sl.val , sl.digitN);
												}
									});
		//set length
		Object.defineProperty(sl, 'length', {
										    get: function() {
										        return sl.len;
										    },
										    set: function(_len) {
										        sl.len=_len;
										        sl.bgLine.scaleX=sl.len/150;
										        sl.btn.x=sl.len*(sl.val-sl.min)/(sl.max-sl.min);
										        //btnS
										        sl.btnS.scaleX=(sl.len+30)/100;
												sl.btnS.x=sl.len/2;
												sl.valueText.x = sl.len+20;
										    }
							});
		//set maximum
		Object.defineProperty(sl, 'maximum', {
										    get: function() {
										        return sl.max;
										    },
										    set: function(_max) {
										        sl.max=_max;
										        if(sl.val>sl.max){sl.val=sl.max;}
										        sl.btn.x=sl.len*(sl.val-sl.min)/(sl.max-sl.min);
												sl.valueText.text = digitN(sl.val , sl.digitN);
										    }
							});
		//set minimum
		Object.defineProperty(sl, 'minimum', {										
										    get: function() {
										        return sl.min;
										    },
										    set: function(_min) {
										        sl.min=_min;
										        if(sl.val<sl.min){sl.val=sl.min;}
										        sl.btn.x=sl.len*(sl.val-sl.min)/(sl.max-sl.min);
												sl.valueText.text = digitN(sl.val , sl.digitN);
										    }
							});
		//set valueText visible
		Object.defineProperty(sl, 'isValueText', {										
										    get: function() {
										        return sl.valueText.visible;
										    },
										    set: function(is) {
										        sl.valueText.visible=is;
										    }
							});
		//set label visible
		Object.defineProperty(sl, 'isLabel', {										
										    get: function() {
										        return sl.label.visible;
										    },
										    set: function(is) {
										        sl.label.visible=is;
										    }
							});
		//set label
		sl.setLabel = function(_text , _outline){
					sl.label.text = _text;
					sl.label.outline = _outline||0;
					}
		//sl help
		sl.help=function(){
			var str1="老師寫的slider，不要修改，\n外部使用變數名稱：\n maximum最大值number，\n minimum最小值number，\n value現在值number";
			var str2="\n length線長度 \n digitN顯示到小數點第N位(預設0) \n isLabel是否顯示文字標籤 \n isValueText是否顯示數字";
			var str3="\n 修改文字標籤：setLabel('文字',outline數字)"
			
			console.log(str1+str2+str3);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// text
	this.label = new cjs.Text("文字標籤", "26px 'Microsoft JhengHei'", "#FFFFFF");
	this.label.name = "label";
	this.label.textAlign = "right";
	this.label.lineHeight = 37;
	this.label.lineWidth = 146;
	this.label.parent = this;
	this.label.setTransform(-27,-17.25);

	this.valueText = new cjs.Text("0", "26px 'Arial'", "#FFFFFF");
	this.valueText.name = "valueText";
	this.valueText.lineHeight = 31;
	this.valueText.lineWidth = 100;
	this.valueText.parent = this;
	this.valueText.setTransform(172,-14.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.valueText},{t:this.label}]}).wait(1));

	// btn
	this.btn = new lib.sliderButton();
	this.btn.name = "btn";
	this.btn.parent = this;
	new cjs.ButtonHelper(this.btn, 0, 1, 2, false, new lib.sliderButton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn).wait(1));

	// btnS
	this.btnS = new lib.btnSquare();
	this.btnS.name = "btnS";
	this.btnS.parent = this;
	this.btnS.setTransform(74.95,0,1.8,0.3);
	new cjs.ButtonHelper(this.btnS, 0, 1, 2, false, new lib.btnSquare(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btnS).wait(1));

	// line
	this.bgLine = new lib.sliderBGLine();
	this.bgLine.name = "bgLine";
	this.bgLine.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.bgLine).wait(1));

}).prototype = getMCSymbolPrototype(lib.theSlider, new cjs.Rectangle(-175,-19.2,449,38.5), null);


(lib.theCheckbox = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//老師寫的checkBox，不要修改
		//外部可用變數：checked
		//修改文字標籤：setLabel("文字",outline數字)
		var ch=this;
		ch.stop();
		ch.ched=false;
		ch.checker.visible=ch.ched;
		ch.btnS.alpha=0;
		//click
		ch.on('click',function(e){
								//按下設值
								ch.ched=!ch.ched;
								ch.checker.visible=ch.ched;
							});
		//set label
		ch.setLabel = function(_text , _outline){
					ch.label.text = _text;
					ch.label.outline = _outline||0;
					
					var rect=ch.label.getBounds();
					ch.btnS.scaleX=(ch.label.x+rect.width+20)/100;
					ch.btnS.x=(ch.label.x+rect.width-20)/2;
					}
		
		//checked
		Object.defineProperty(this, 'checked', {
										    get: function() {
									        return ch.ched;
										    },
										    set: function(_ched) {
										        ch.ched=_ched;
										        ch.checker.visible=ch.ched;
										    }
								});
		//ch help
		ch.help = function(){
			var str="老師寫的checkBox，不要修改\n 外部可用變數：checked \n 修改文字標籤：setLabel('文字',outline數字)";
			console.log(str);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// btnS
	this.btnS = new lib.btnSquare();
	this.btnS.name = "btnS";
	this.btnS.parent = this;
	this.btnS.setTransform(59.2,0,1.6384,0.3399,0,0,0,0.1,0);
	new cjs.ButtonHelper(this.btnS, 0, 1, 2, false, new lib.btnSquare(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btnS).wait(1));

	// checker
	this.checker = new lib.checker();
	this.checker.name = "checker";
	this.checker.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.checker).wait(1));

	// box
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#CCCCCC").ss(3,1,1).p("AiViVIErAAIAAErIkrAAg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AiVCWIAAkrIErAAIAAErg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// label
	this.label = new cjs.Text("文字標籤", "26px 'Microsoft JhengHei'", "#FFFFFF");
	this.label.name = "label";
	this.label.lineHeight = 37;
	this.label.lineWidth = 132;
	this.label.parent = this;
	this.label.setTransform(24,-18.6);

	this.timeline.addTween(cjs.Tween.get(this.label).wait(1));

}).prototype = getMCSymbolPrototype(lib.theCheckbox, new cjs.Rectangle(-23.8,-20.7,181.9,38.7), null);


(lib.controlPhasor = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AEWJ+QgYAlgmAbIgXgWQAogYAegxQgZg5gCgbIgEAJIgZgHIAAAyQAAAEgFABIhHAAIgKARIBmAAIAAAZIgoAAQgVAdgRAOIAuAPIgSAZIg7gUIgiALQgVAHgmACIgIgeQAQAAArgFIgegKIgEgUQAOgKAIgIIgvAAIAAgZIBJAAIALgRIhBAAQgDgBAAgEIAAg8QACgFABAAIBHAAIAAgMIhBAAQgEAAAAgFIAAgoIgVAAIAAgaIAVAAIAAgoQAAgEAEgBIBBAAIAAgPIAdAAIAAAPIA/AAQAFABAAAEIAAAoIAWAAIAAAaIgWAAIAAAoQAAAFgFAAIg/AAIAAAMIBGAAQAFAAAAAFIAAACQAghHgBhJIAdAAIgDAoIBTAAIAAAeIgTAAIAAALQAABPgiBMQAYAqAfAmIgbAQQgng1gFgOgABPKCQgBAAAAAAQAAAAAAABQAAAAAAAAQAAABABAAIAhAKQAUgMARgUIgxAAQgJAJgMALgAEHINQAHAbAIAXQAUg1AAhEIAAgLIgmAAQgHAjAKAvgACEIrIAtAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAgBAAAAIAAgSQAAAAAAgBQAAAAAAAAQAAAAAAAAQgBAAAAAAIgtAAgAA6IYIAAATIAtAAIAAgUIgtAAQgBAAAAAAQAAAAAAAAQAAAAAAAAQAAABABAAgACEHYIAlAAIABgBIAAgSIgmAAgAA/HXQAAAAAAABQAAAAABAAQAAAAAAAAQAAAAABAAIAmAAIAAgTIgoAAgACEGrIAmAAIAAgTIgmAAgAA/GrIAoAAIAAgTIgoAAgAh3KgQg1AYg/AJIgKgeQA1gHAfgKIAQgEQgRgOgagfQgTASgiARIgSgYQARgIAOgIQAggXASgfIgTAAQgFAAAAgFIAAhpQAAgEAFAAIChAAQAFAAAAAEIAABpQAAAFgFAAIhtAAIgJARIB4AAIATAQQgVAoguAdQgDADgEACQAmAOAnAEIgLAeQg+gMgigVgAiDJ0QAHAIAIAEQAHgDAGgEQAZgOARgVQADgEgGABIhhAAQAQAUAOANgAisIKQAAAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIBtAAIABgBIAAgRIhvAAgAisHQIAAARIBvAAIAAgRQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAAAAAAAIhtAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAABAAAAgAkyK+IAAiOIgSAbIgYgWQA2g1AQg5QACgIgGAAIg3AAIAAgdIAeAAIAAgyIAdAAIAAAyIATAAIAPAJQgKAtgWArIAAALQAcAXAZAZIgTAVIgigjIAACOgAkKINQASgZAIgQIAYAPQgKAUgSAXgAj0GxQAXgbAIgmIAeAJIgFANICwAAIAAAcIi7AAQgKAVgMANQgNgNgKgGgAiICFIAJgTIhhAAIAHATQg0AWg0AKIgGgcIBPgXIg3AAQgDAAAAgEIAAh0QABgBAAgBQAAAAABgBQAAAAABgBQAAAAAAAAID5AAQAEAAAAAEIAAB0QAAAEgEAAIg3AAQAtASAeAGIgKAcQhFgWgXgLgAkWBaIDHAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAgBIAAgJIjIAAgAkWA6IDIAAIAAgNIjIAAgAkWAOIAAAKIDIAAIAAgKQAAAAAAgBQAAAAAAAAQAAAAgBAAQAAAAAAAAIjHAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAABAAAAgADUCiIAAk9QAAgGAGABIBmAAIAUAPIggBqQgDAFAEAEQAYAhAJAZQAOAzgTAeQgIANgNAFQgYAJgngQIAEgiQAhARAMgFQAVgGgEgoQgGgfgjguIgDgJIAehhIg6AAQgEAAAAAEIAAEhgACfCfIAAgQIhnAAIAAAQIgdAAIAAiEQAAgEAFgBICXAAQAFABAAAFIAACDgAA4A3IAAA8IBnAAIAAg+QAAgDgEAAIhfAAQgEABAAAEgAASgDIAAgcIBsAAQATgyAFgaIAaAKIgVBCIAuAAIAAAcgAkrgWQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAAAIgCgGIAEgZIgrAAIAAgYIAwAAIAFgcQABgBAAAAQAAgBABAAQAAgBAAAAQAAAAABAAIAEgCIDXAAQABAAABABQAAAAABAAQAAAAABAAQAAABABAAIACAEIgCAbIAuAAIAAAYIgwAAIgDAcIgCADQgCACgEAAgAirgsIBJAAQAFAAAAgEIABgHIhMAAgAkPgxQgCADAEACIBGAAIACgLIhKAAgAikhPIBJAAIACgFQAAgFgGAAIhCAAgAkJhVIgBAGIBKAAIACgKIhFAAQgGAAAAAEgAAqhhIAbgHQAOAmAEAUIgbAGQgIgjgKgWgAgwheQAHgYgCgCQACgEgFAAIkEAAIgBADIAAAeIgcAAIAAg2QAAgGAFAAICJAAIAAgUIAfAAIAAAUICAAAIAYANQgCAVgKAegAAZhzIAAgdIBFAAIAAgbIAfAAIAAAbIBFAAIAAAdgAC5mPQAegUAVgaQANgSAOgbIgeAAQgwBLhEAhIgQgZQAjgSAbgWQARgQASgbIggAAQgaAkgrAaIgSgYQAdgSAZgaQAPgPAOgaIgwAAIAAgcIDoAAIAAAcIiYAAIgKATICXAAQAEAAABABQAGAFAAAKQAABZgNARQgIALgOAFQgRAFgigFIgBgiQALAEAKACQAPACANgMQAHgHAAgRQAEgogEgHIgDgBIgSAAQgeBIg7AqgAiml+QgMgBgKgIQgIgKAAgKIAAgRIh4AAQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAhpQAAgBAAgBQABAAAAgBQAAAAABAAQAAgBAAAAIEMAAQAEACAAACIAABpQAAAEgEAAIh2AAIAAABQAAAHAEAGQAFAEAGABIBlAAIAJgDQACgDAAgVIAdAGIgHAmQgMALgIgBgAimnFIBcAAIACgBIAAgTIheAAgAkinFIBeAAIAAgUIheAAgAimnxIBeAAIAAgSIheAAgAkinxIBeAAIAAgSIheAAgAANnMIAngYIAAh8IglAAIAAgdIAlAAIAAhDIAfAAIAABDIAiAAIAAAdIgiAAIAABoQALgIAGgGIASAYQgZAWhAAkgAjDopIAAhMIhwAAQgDgBAAAEIAAAuIgdAAIAAhIQABgFAEAAICLAAIAAgPIh3AAIAAgbIEOAAIAAAbIh5AAIAAAPICBAAIAaANQgCAbgKAmIgcgIQAHggAAgGQAAgEgEAAIh2AAIAABMgAiUosIAAgYIBbAAIAAAYgAkrosIAAgYIBaAAIAAAYgACKpGQgFAAAAgFIAAhsQAAgFAFABIC4AAQAEgBAAAFIAABsQAAAFgEAAgACjpiQAAAAAAAAQAAAAAAAAQAAAAABAAQAAABAAAAICDAAQABAAAAgBQAAAAAAAAQABAAAAAAQAAAAAAAAIAAgRIiGAAgACjqfIAAARICGAAIAAgRQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAAAgBAAIiDAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAABAAAAgAiUpQIAAgYIBYAAIAAAYgAkppQIAAgYIBYAAIAAAYg");
	this.shape.setTransform(1481.075,485.55);

	this.chEEZZ = new lib.theCheckbox();
	this.chEEZZ.name = "chEEZZ";
	this.chEEZZ.parent = this;
	this.chEEZZ.setTransform(1478.95,537.45,1,1,0,0,0,67.2,-1.4);

	this.chEERR = new lib.theCheckbox();
	this.chEERR.name = "chEERR";
	this.chEERR.parent = this;
	this.chEERR.setTransform(1478.95,482.45,1,1,0,0,0,67.2,-1.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.chEERR},{t:this.chEEZZ},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.controlPhasor, new cjs.Rectangle(1388.1,415.1,181.70000000000005,141.69999999999993), null);


(lib.controlNSlit = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層_1
	this.textNN = new cjs.Text("20", "36px 'Arial'", "#FFFFFF");
	this.textNN.name = "textNN";
	this.textNN.textAlign = "center";
	this.textNN.lineHeight = 42;
	this.textNN.lineWidth = 50;
	this.textNN.parent = this;
	this.textNN.setTransform(1464,518.05);

	this.btnPlus = new lib.btnPlus();
	this.btnPlus.name = "btnPlus";
	this.btnPlus.parent = this;
	this.btnPlus.setTransform(1513.3,533.8,0.6,0.6,0,0,0,0.1,0);
	new cjs.ButtonHelper(this.btnPlus, 0, 1, 2, false, new lib.btnPlus(), 3);

	this.btnMinus = new lib.btnMinus();
	this.btnMinus.name = "btnMinus";
	this.btnMinus.parent = this;
	this.btnMinus.setTransform(1414.8,533.8,0.6,0.6,0,0,0,0.1,0);
	new cjs.ButtonHelper(this.btnMinus, 0, 1, 2, false, new lib.btnMinus(), 3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.btnMinus},{t:this.btnPlus},{t:this.textNN}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.controlNSlit, new cjs.Rectangle(1395.7,514.8,136.5999999999999,45.5), null);


// stage content:
(lib.myAnimate = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// helper
	this.logo = new lib.logo();
	this.logo.name = "logo";
	this.logo.parent = this;
	this.logo.setTransform(799.95,450,3,3);

	this.timeline.addTween(cjs.Tween.get(this.logo).wait(1));

	// controlPhasor
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AFnDFQgGgKAAgZQAAgYAGgJQAEgHAJAAQAHABAGAGQAGAIAAAYQAAAZgGAKQgFAJgIAAQgJAAgEgIgAFtCGQgEAHAAAVQAAAXAEAHQADAEAEAAQAEAAACgEQAFgIgBgXQAAgTgEgIQgCgDgEAAQgEAAgDADgACcDFQgGgKAAgZQAAgYAGgJQAEgHAJAAQAIABAFAGQAGAIAAAYQAAAZgGAKQgFAJgIAAQgJAAgEgIgACiCGQgEAHAAAVQAAAXAEAHQADAEAEAAQAEAAADgEQADgIAAgXQAAgTgDgIQgDgDgEAAQgFAAgCADgAGSDMIAAgHQAAgOARgPQAQgOAAgKQAAgFgDgFQgDgDgEAAQgGgBgCAEQgFAFAAAJIgIAAQAAgOAGgGQAFgGAKAAQAIAAAFAGQAFAGAAAKQAAAOgSARQgPANAAAHIAhAAIAAAJgAD6DMIAAgHQAAgOAQgPQAQgOABgKQgBgFgCgFQgDgDgEAAQgHgBgCAEQgEAFAAAJIgJAAQABgOAFgGQAHgGAJAAQAIAAAFAGQAFAGAAAKQAAAOgSARQgOANgBAHIAhAAIAAAJgADIDMIAAgHQAAgOAQgPQAQgOAAgKQAAgFgDgFQgDgDgEAAQgGgBgDAEQgEAFAAAJIgIAAQAAgOAGgGQAFgGAKAAQAIAAAFAGQAFAGAAAKQAAAOgSARQgOANAAAHIAgAAIAAAJgABiDMIAAgHQAAgOAQgPQAQgOABgKQgBgFgCgFQgEgDgDAAQgGgBgDAEQgFAFAAAJIgHAAQAAgOAFgGQAGgGAKAAQAHAAAFAGQAGAGAAAKQgBAOgRARQgPANAAAHIAhAAIAAAJgAE5DGIAAgMIANAAIAAAMgAGaBVQgHgLAAgZQABgZAFgIQAFgHAIAAQAIABAGAGQAFAIABAZQgBAXgFAMQgFAIgJAAQgIAAgEgHgAGgAWQgEAHAAAUQAAAXAEAHQACAEAEABQAFAAACgFQAEgIABgWQgBgUgEgHQgDgEgEAAQgEAAgCAEgAD+BZIACgHQAFADAEAAQAHgBAFgHIAFgQQgGAGgIAAQgIAAgFgHQgGgIAAgLQAAgNAGgJQAFgJALgBQAKAAAFAKQAFAJAAASIAAAAQgBAVgGAMQgHANgMAAQgIAAgDgDgAEFAXQgDAHgBALQAAAIAFAGQADAEADAAQAHAAAEgGQADgEABgEIAAgBQAAgOgDgGQgEgHgFAAQgHAAgDAGgADPBVQgGgLAAgZQAAgZAFgIQAFgHAJAAQAHABAFAGQAHAIAAAZQAAAXgHAMQgEAIgIAAQgJAAgEgHgADVAWQgEAHAAAUQAAAXAEAHQADAEAEABQADAAAEgFQADgIAAgWQAAgUgEgHQgDgEgDAAQgEAAgDAEgACcBVQgGgLAAgZQAAgZAGgIQAEgHAJAAQAIABAFAGQAGAIAAAZQAAAXgGAMQgFAIgIAAQgJAAgEgHgACiAWQgEAHAAAUQAAAXAEAHQADAEAEABQAEAAADgFQADgIAAgWQAAgUgDgHQgDgEgEAAQgFAAgCAEgAFjBbIAAgJIAMAAIAAg8IgNAGIAAgIIAWgKIAABIIANAAIAAAJgABiBbIAAgGQAAgPAQgPQAQgNABgKQgBgHgCgDQgEgEgDAAQgGAAgDAEQgFAEAAAIIgHAAQAAgMAFgGQAGgGAKgBQAHABAFAGQAGAFAAALQgBANgRARQgPANAAAHIAhAAIAAAJgAE5BWIAAgNIANAAIAAANgAEqgjIAAhcIgHALIgQgHQAcglAFgqIAQADIgLAoIAAB8gAB4gyIATgCIAAgMQgUAHgRABIgFgPQAjgDAggOIhCAAIAAgOIBMAAIAAgIQgEgCgDAAIgBgQQAPAFADgDQAEgCAAgEIAAgDIgBgBIgbAAIAAAYIgOAAIAAgYIgZAAIgBABIAAAUIgOAAIAAgfQgBgDAFAAIAkAAIAAgIIgqAAIAAgNIAqAAIAAgIIghAAIgKAIQgEgJgEgDQANgJAJgNIAMAJQgBACgDACIAVAAIAAgLIAOAAIAAALIAoAAIAAANIgoAAIAAAIIArAAIAAANIgrAAIAAAIIAnAAQABAAABAAQAAABABAAQAAABAAAAQAAABAAAAIAAATQABAJgIAEQgCADgDABIAAAIIBIAAIAAAOIgWAAIAHAKIgYAQQAQAIAZAEIgFANQg1gGgZgoQgOAJgMAFIAAAQQAWgDAPgEIACAPQgeAHgqADgADIhQIAKAJIAcgRIgrAAIAFAIgAFygkIAAiIIgQAAQgIAfgKAUIgRgFQAVglABgmIAPABIAAAMIBXAAIAAAQIg6AAIAAAjIA1AAIAAAQIg1AAIAAAhIA3AAIAAAPIg3AAIAAAlgAAWgmIgBgRQAZAGAGgFQAEgEAAgDIAAg6IhGAAIAAgPIBgAAIAAAPIgLAAIAAA+QgBAFgDAFQgEAGgEACQgIACgMAAIgRgBgAkHgvQAYgUABgxIAAgFIgSAAIAAgQIBKAAIAAAQIgMAAIAAA4QAAAEACACQAEACADABIBFAAQAAAAABgBQABAAAAAAQABAAAAgBQABAAAAAAQABgBAAgRIAQACQgBAZgDACQgFAGgGAAIhUAAQgHgBgEgFQgEgEgBgFIAAhBIgNAAIAAAFQAAAygbAcgAksgmIAAgGIhIAAIAAAGIgPAAIAAhHIgEADIgJgNQAggLARgOIgtAAIAAgOIAZAAIgLgNIALgKQAIAIAIAKIgHAFIARAAIAAgZQgYABgRgBIgCgQQA7ACAkgGIACAOQgMAEgaABIAAAAIAAAaIAJAAIAOgZIANAHIgJASIAXAAIAAAOIgtAAQATAPAeAIIgIANIgCgBIAABHgAlJg5IAdAAIAAgNIgdAAgAl0g5IAbAAIAAgNIgbAAgAlJhTIAdAAIAAgMQAAgBAAAAQAAAAgBgBQAAAAAAAAQgBAAAAAAIgbAAgAl0hfIAAAMIAbAAIAAgOIgZAAQAAAAgBAAQAAAAAAABQgBAAAAAAQAAAAAAABgAklhvQgTgIgRgMIAAAUIAkAAIAAAAgAljh9QgCACgWAMIAiAAIAAgVIgKAHgAm6gvQALgLAGgNQAIgOAFgRIAPADQgMAogTAVgAhTg6IAcgDIAAg5IgXAAIAAgNIAXAAIAAgOIgQAAIAAgOIAxAAIAAAOIgSAAIAAAOIATAAIAAANIgTAAIAAA3IAXgGIAFAOQgZAIgqAEgAimhAIAAgRQAWAHAGgEIABgFIAAg2IgoAAIAAgPIAoAAIAAgSIAQAAIAAASIAWAAIAAAPIgWAAIAAA6QAAALgJAEQgEADgIAAQgKAAgOgDgAgDg/QgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgrQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIAwAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAArQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAgAAHhfIAAATIAZAAIABAAIAAgTIgBAAIgZAAIAAAAgAhLhDQgBgWgCgRIAMgCQAFAYAAARgAgkhNQAGgSAAgOIAOADIgGAggAiuh5IAOgHQALATAFAPIgNAFQgGgOgLgSgADchxIAAgPQARAEAEgDQABgBAAgDIAAhHIAPAAIAABKQAAALgIAEQgDACgIAAQgHAAgLgCgAm6iHIAJgMQAMAGASANIgJANQgSgNgMgHgADViJIAAg7IAOAAIAAA7gAAgiqQgLAUgbAMIgKgNIAGgDQAXgLAHgLIgfAAIAAgOIAiAAIAAgLIAQgBIgBAMIAoAAIAAAOIgjAAQANASAYAHIgIANQgbgKgNgWgAjtiZIAAgPIA0AAIAAAPgAh2ijIAFgRQAAAAAAAAQAAgBgBAAQAAAAAAAAQgBgBAAAAIh+AAQAAAAgBAAQAAAAAAABQAAAAAAAAQgBABAAAAIAAAWIgPAAIAAgkQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAICSAAIAOAHQgBANgGATgAhTirQAagQAHgMIANAAIAAADIAZASIgMAMIgTgTQgMAMgPAMgAm3i3IAKgNQAMAJAQAOIgKALQgRgPgLgGg");
	this.shape.setTransform(1542.6,30.4);

	this.controlPhasor = new lib.controlPhasor();
	this.controlPhasor.name = "controlPhasor";
	this.controlPhasor.parent = this;
	this.controlPhasor.setTransform(0,-48.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.controlPhasor},{t:this.shape}]}).wait(1));

	// controlNSlit
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AlSCmIAAgZIBBAAIAAhYQAAgIAIAAICwAAQAKAAAAAIIAABYIBBAAIAAAZgAj1CNICKAAIAAgMIiKAAgAj1BvICKAAIAAgOIiKAAgAj1BGIAAAJICKAAIAAgJQAAgEgEAAIiDAAQgBAAgBABQAAAAAAAAQgBABAAAAQAAABAAABgAE1CiIAAgRIhDAAIAAARIgfAAIAAkvQAAgEAEAAIB2AAQAHAAAAAFIAAEugADyhuIAADgIBDAAIAAjgQAAgEgEAAIg7AAQgFAAABAEgABPCZIgDgkQAZAHANABQAOACAEgFQAHgIAGgSQAEgXAAgwQAChxgCgFQAAgBAAAAQAAAAgBAAQAAgBgBAAQgBAAgBAAIgwAAQAAAlgIA+QgQBogZAwIgggHQAIgRAGgRQAmhtAAhlIgvAAIAAgfIAvAAIAAgnIAeAAIAAAnIBIAAQAGAAABACQAGADAAAMQAABPgCA8QgEBmgaAVQgJAHgSAAQgSAAgbgHgAgvBQQAKgfAAgKQAAgCgEAAIkNAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAAAAAABIAAAqIgcAAIAAhBQAAgEAEAAIExAAIAXALQAAAdgNAmgAihABQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIAAhFQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAAAAAICNAAQAEACAAABIAABFQAAADgEAAgAhMgOIAhAAIACgCIAAgLIgjAAgAiKgOIAkAAIAAgNIgkAAgAhMgsIAjAAIAAgNIgjAAgAiKgsIAkAAIAAgNIgkAAgAlMABQgDAAAAgDIAAhFQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAICMAAQAFACAAABIAABFQAAADgFAAgAj5gOIAjAAIABgCIAAgLIgkAAgAk2gOIAjAAIAAgNIgjAAgAj5gsIAkAAIAAgNIgkAAgAk2gsIAjAAIAAgNIgjAAgAkmhWQgBAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAhEQAAAAAAgBQABgBAAAAQABAAAAgBQAAAAABAAIDpAAQAEACAAABIAABEQAAAEgEAAgAiihnIBMAAIABgBIAAgMIhNAAgAkNhnIBPAAIAAgNIhPAAgAiiiFIBNAAIAAgLIhNAAgAkNiFIBPAAIAAgLIhPAAg");
	this.shape_1.setTransform(1482.125,596.825);

	this.chSum = new lib.theCheckbox();
	this.chSum.name = "chSum";
	this.chSum.parent = this;
	this.chSum.setTransform(1412.95,598.15);

	this.chAuto = new lib.theCheckbox();
	this.chAuto.name = "chAuto";
	this.chAuto.parent = this;
	this.chAuto.setTransform(1412.95,545.05);

	this.controlNSlit = new lib.controlNSlit();
	this.controlNSlit.name = "controlNSlit";
	this.controlNSlit.parent = this;
	this.controlNSlit.setTransform(0,-48.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.controlNSlit},{t:this.chAuto},{t:this.chSum},{t:this.shape_1}]}).wait(1));

	// UI
	this.btnZoom = new lib.btnZoom();
	this.btnZoom.name = "btnZoom";
	this.btnZoom.parent = this;
	this.btnZoom.setTransform(1465,667.35);
	new cjs.ButtonHelper(this.btnZoom, 0, 1, 2, false, new lib.btnZoom(), 3);

	this.btnEEII = new lib.btnEEII();
	this.btnEEII.name = "btnEEII";
	this.btnEEII.parent = this;
	this.btnEEII.setTransform(1465,749.3);
	new cjs.ButtonHelper(this.btnEEII, 0, 1, 2, false, new lib.btnEEII(), 3);

	this.mBtnSSlitD = new lib.mBtnSSlitD();
	this.mBtnSSlitD.name = "mBtnSSlitD";
	this.mBtnSSlitD.parent = this;
	this.mBtnSSlitD.setTransform(1335.9,102.6);
	new cjs.ButtonHelper(this.mBtnSSlitD, 0, 1, 2, false, new lib.mBtnSSlitD(), 3);

	this.mBtnPhasor = new lib.mBtnPhasor();
	this.mBtnPhasor.name = "mBtnPhasor";
	this.mBtnPhasor.parent = this;
	this.mBtnPhasor.setTransform(1067.8,102.6);
	new cjs.ButtonHelper(this.mBtnPhasor, 0, 1, 2, false, new lib.mBtnPhasor(), 3);

	this.mBtnNSlit = new lib.mBtnNSlit();
	this.mBtnNSlit.name = "mBtnNSlit";
	this.mBtnNSlit.parent = this;
	this.mBtnNSlit.setTransform(1201.85,102.6);
	new cjs.ButtonHelper(this.mBtnNSlit, 0, 1, 2, false, new lib.mBtnNSlit(), 3);

	this.mBtnDSlitD = new lib.mBtnDSlitD();
	this.mBtnDSlitD.name = "mBtnDSlitD";
	this.mBtnDSlitD.parent = this;
	this.mBtnDSlitD.setTransform(1470,102.6);
	new cjs.ButtonHelper(this.mBtnDSlitD, 0, 1, 2, false, new lib.mBtnDSlitD(), 3);

	this.slCameraRR = new lib.theSlider();
	this.slCameraRR.name = "slCameraRR";
	this.slCameraRR.parent = this;
	this.slCameraRR.setTransform(1350,850);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.slCameraRR},{t:this.mBtnDSlitD},{t:this.mBtnNSlit},{t:this.mBtnPhasor},{t:this.mBtnSSlitD},{t:this.btnEEII},{t:this.btnZoom}]}).wait(1));

	// UIbg
	this.mBtnBG = new lib.mBtnBG();
	this.mBtnBG.name = "mBtnBG";
	this.mBtnBG.parent = this;
	this.mBtnBG.setTransform(1067.8,102.6);

	this.timeline.addTween(cjs.Tween.get(this.mBtnBG).wait(1));

	// btn3D
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AD0CkIgFgjQAmAKAJgJQAGgHAGgQQAFgWABguQABhqgBgEQgBgBgBAAQAAgBgBAAQAAAAgBgBQAAAAgBAAIghAAIgFAwQgFA2gKAwQgOA/gOAbIgfgGQAnhgAKiKIgeAAIAAgdIAgAAIAAgXIAAgkIAfAAIAAAkQgCAKAAANIA4AAIAIABQADADAAAMQAABKgBA6QgDBfgaAVQgJAHgTAAQgNAAgTgEgAhJCjIAAgOIjmAAIAAAOIgfAAIAAkWQAAgJAKAAIBnAAQALgaAFgRIAdAMIgKAfICEAAQALAAAAAJIAAEWgAkvB2IDmAAIAAgvIjmAAgAkvAoIDmAAIAAgzIjmAAgAkvhZIAAAvIDmAAIAAgvQgBgFgEAAIjcAAQgGAAABAFgAANCFIBQgFIAAgYIhLAAIAAgbIBLAAIAAgVIhKAAQAAAAgBgBQAAAAAAAAQgBgBAAgBQAAAAAAgBIAAhsQAAAAABgBQAAAAAAgBQAAAAABAAQAAAAAAAAIBKAAIAAgVIhNAAIAAgbIBNAAIAAgUQgrADgaAAIgFgbQBpAAA7gMIAEAaQgVAEgrAFIgCAAIAAAVIBJAAIAAAbIhJAAIAAAVIBDAAQABAAABAAQABABABAAQAAAAAAABQABAAAAAAIAABsQgBAEgEAAIhDAAIAAAVIBDAAIAAAbIhDAAIAAAVIA+gEIABAcIinAMgAB5AfIAqAAIABgCIAAgSIgrAAgAAtAfIAwAAIAAgUIgwAAgAB5gNIArAAIAAgUIgrAAgAAtgNIAwAAIAAgUIgwAAg");
	this.shape_2.setTransform(1481.55,545.1306);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ACVCWQgWAAgbgNIAEgaQAZAOAXAAQANgEAEgJQACgKgFgQIiLAAIAAgaIB+AAIgQgUIAQAAIAsgTIh0AAIAAgYICRAAIAUAbIhCAeIAEAGIBsAAIAAAaIhhAAQACAEABAEQADAegQAPQgOALgSAAIgEAAgAGDCVIAAhaIgqARIgPgZQAjgLAWgLIAAhZIgUAAQgHApgFAPIgagEQAPgyAAg9IAAgSIAaAAIAAASIgBAfIASAAIAAg8IAcAAIAAA8IAbAAIAAAcIgbAAIAABMQAPgJAJgHIAQAWQgSAMgWALIAABogAmeCRIgFgfQAiAIAIgHQAFgGAFgPQAFgTABgpQABhegBgEIgEgDIgeAAIgEArQgFAwgJAqQgMA4gNAYIgbgFQAjhVAJh7IgbAAIAAgaIAcAAIAAgUIAAggIAbAAIAAAgQgBAJAAALIAyAAIAGABQAEADAAALIgBB1QgDBVgXASQgIAGgQAAQgMAAgRgDgArFBbQgPAagfAeIgXgRQAigYAXgtQgSgugFgsQgGAagFAMIgYgFIAACHIgaAAIAAgOIgoAAIAAAOIgbAAIAAikQAAgFAGAAIAaAAIAAg0IglAAIAAgZIAlAAIAAgoIAaAAIAAAoIAmAAIAAAZIgmAAIAAA0IAeAAQAFABAAAFIAAAYQAWg6ABhDIAAgWIAZAAIAAAWIgCAMIBRAAIAAAcIgPAAIAAAIQgCBFgaBIQASAjAZAmIgZAKIggg4gAtNAAIAABjIAoAAIAAhjQAAgEgEAAIghAAQgDAAAAAEgArFAZQAAABAAAAQAAABAAAAQABABAAAAQAAABAAAAQAOguACg8IAAgIIgeAAQABBEAMAqgAIKCMIgCghQAsAPALgIQAKgFAFgTQAGgVABgrQAChlgCgFIgDgCIgOAAQgBBAgcBAQgaA3g1AmIgVgUQBjg7AEiOIgUAAQgCATgDATQgOBAhABBIgYgPQAugtATglQAKgZAFgtIgWAAQgPArgQAYIgbgKQAmg5AHhBIAbAEQgCATgEAPIB6AAIAGABQAEADAAALIgBB8QgCBbgeAUQgKAGgQAAQgSAAgagHgAuVCSIAAifQgFAGgCAFIgZgIQAohDAFhEIAZACQgFAngHAbIAADfgAkwCOIAAgWIEhAAIAAAWgApsB1IBHgFIAAgVIhCAAIAAgYIBCAAIAAgSIhBAAQgBAAAAAAQgBgBAAAAQAAgBAAAAQgBgBAAgBIAAhfIADgDIBBAAIAAgTIhFAAIAAgXIBFAAIAAgSQglADgYAAIgEgYQBcAAA1gLIAEAXQgTAEgmAEIgCAAIAAATIBBAAIAAAXIhBAAIAAATIA8AAQABABABAAQAAAAABABQAAAAABAAQAAABAAAAIAABfQAAAEgEAAIg8AAIAAASIA8AAIAAAYIg8AAIAAATIA3gEIACAZIiWALgAoMAaIAmAAIABgBIAAgQIgnAAgApQAaIArAAIAAgRIgrAAgAoMgNIAnAAIAAgRIgnAAgApQgNIArAAIAAgRIgrAAgALrCLIAAgZIBYAAIAAgmIhIAAIAAgZIBIAAIAAgfIhGAAQgBAAgBAAQAAgBgBAAQAAAAAAgBQAAgBAAgBIAAiWQAAgBAAgBQAAAAAAgBQABAAAAAAQABgBABAAICoAAQADAAAAAEIAACWQAAAEgDAAIhHAAIAAAfIBLAAIAAAZIhLAAIAAAmIBYAAIAAAZgANegEIAvAAIABgBIAAgoIgwAAgAMTgFQAAAAABAAQAAABAAAAQAAAAAAAAQABAAAAAAIAuAAIAAgpIgwAAgANehGIAwAAIAAgrIgwAAgAMThGIAwAAIAAgrIgwAAgAKKBjIAogNIAAhfIghAAIAAgZIAhAAIAAhPIgjAAIAAgZIBgAAIAAAZIgiAAIAABPIAgAAIAAAZIggAAIAABWIAhgNIAMAZIgpAQQglAOgYAFgAkMBtQAAAAgBAAQAAgBAAAAQgBgBAAAAQAAgBAAgBIAAhRQAAgBABgBQAAgBAAAAQAAgBABAAQAAAAAAAAIDaAAQAEAAAAAEIAABRQAAAEgEAAgAiUBXIBMAAIABgBIAAgLIhNAAgAj1BXIBHAAIAAgMIhHAAgAiUA3IBNAAIAAgNIgBgBIhMAAgAj1AqIAAANIBHAAIAAgOIhHAAQAAAAgBAAQAAABAAAAQAAAAAAAAQABAAAAAAgAEQAYQAIgcAAgIQAAAAAAgBQAAgBgBAAQAAgBgBAAQgBAAAAAAIjqAAQgDgCAAAEIAAAnIgaAAIAAg9QABgFAEAAIAPAAIAAhhQABgGAFAAQAlABAegHIAIAWQgZAHgfAAQAAAAgBAAQAAABAAAAQAAAAAAABQABAAAAAAIAAAKIAtAAIAAAXIgtAAIAAALIAuAAIAAAWIguAAIAAAMIB9AAQgJgJgLgIQgTAKgUAFIgKgVIAcgHIgOgJIALgPQgJABgFAEIgLgUIAbgLQgNgHgEgBIALgUIAaAPQAMgHAIgJIAQAQIgOALIAPAKIgMATIAMAPIgPAKIARANIgNAPIBIAAIAAgNIgvAAIAAgWIAvAAIAAgKIgvAAIAAgXIAvAAIAAgKQAAAAAAgBQAAAAgBAAQAAgBgBAAQgBAAgBAAIgpAAIAAgXIBAAAQAGAAAAAFIAABiIACAAIAWALQgBAagLAigACQhhIAVAPQAKgGAJgHIgUgNQgEAEgQAHgAksALIAAgVIB+AAIAAgKIhrAAIAAgUIBrAAIAAgKIhlAAIAAgUIBlAAIAAgKIiCAAIAAgWICCAAIAAgIIhlAAIAAgUIBlAAIAAgRIAaAAIAAARIBjAAQAHABAAAFIAAAWIAbAAIAAAWIgbAAIAAAWQAAAIgHAAIhjAAIAAAKIBwAAIAAAUIhwAAIAAAKICBAAIAAAVgAiUhGIBPAAIACgDIAAgHIhRAAgAiUhmIBRAAIAAgHIgCgBIhPAAg");
	this.shape_3.setTransform(101.2,875.708);

	this.btn3D = new lib.btn3D();
	this.btn3D.name = "btn3D";
	this.btn3D.parent = this;
	new cjs.ButtonHelper(this.btn3D, 0, 1, 2, false, new lib.btn3D(), 3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.btn3D},{t:this.shape_3},{t:this.shape_2}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(800,450,824,450);
// library properties:
lib.properties = {
	id: '98EA1A955B63F6489D0F00F6BFD1C4DE',
	width: 1600,
	height: 900,
	fps: 30,
	color: "#000000",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['98EA1A955B63F6489D0F00F6BFD1C4DE'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;