(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.title = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFF00").s().p("AQaFvQgghOAAhDQAAhMAWAAQARAAANAXQAZA7A/BhQAOAXAAATQAABIg8AAQggAAgehIgEgj7AFkIAAgVQg4AHgyAAQg9AAgfgbQgggbAAghQABgkBZgtQAPgGAGgFQgQgJgLgLQgcgcgDgsQgDiJgIgeQgIgXAAgWQABgpAqAAQAVAAARATQABAAAAAAQAAAAABgBQAAAAAAAAQAAAAAAAAIAPAAQAOAAAagHQCqgqA4AAQBFAAA8AmQAsAjAAAvQgBB1gVA3QAHALAAAMQABAmg2AGQhIAAg+AGIgBAxQBHgKA1AAQAkAAAbAVQAbASAAAhQAAAzhEABIiVAHIAAAbQAABShIAAQg/AAAAhLgEgmZADsQAAATAXAAQAdAAA7gQQAagHAYgEIACg6QghAHgRAAQgGAAgDgCQhoArAAASgEglDAAlQADAmA9AAIARAAIABgwQgoAHgbAAIgPAAIAAADgEghtAADIAAAUIAAATQAegHAWgBIACgHQAFgQACgOQgfACgeAEgEglNgBLIAEAnIBTgTQgFgWgKgPQguAMgaAFgEgiQgB8IADACQANAMAIAcQAagDAXAAQAQAAARACIAAgCQAAgwgtAAQgaAAgjAJgEgrMAFNQg9hSAAgPQAAgDAEgBQACAAAjAbQAtAeATAAQAWAAAnhXQAdhLAAgdQgCgIgRAAQgKAAgyAWQg7AfgQAAQg0gCAAgvQAAgTAmhMQAOgcAIgUQgRgEgNgIQgXgMAAgQQABgPAQgLQAUgSAQAAIALAAQAIAAAmgYQApgZApgIIAEgJQAahVAAgIQAAgagPAAQgPAAgeAkQg1A6gTAAQghAAgegZQgbgXAAgaQABgVASgMQARgNARAAIATAIQALAABGg6QApghAfAAQAtAAAoAdQAgAXAAAbQAAAmgmCKQAbAWAAAXQAAAmgtAAIiaAkQgHAZgTArQAAAIADAAQBtgkAeAAQBUAAACBQQABA9g1CKQhAClg4AAQgYAAhJhigEAmqAF5IgXgPQgbAjgSAAQgpAAgkgbQgkgYAAgQQAAgLANgEQA1gVA6hPQApg3AAgRQAAgIgHAAQgFAAgWAMQgtAWgLAAQgtAAAAgqQAAgSANgXQARgTALAAQAMAEAHAAQAHAAAcgHQAcgHAUAAQAlAAAYAUIAGAEQgCgggUgaQgnAHgdAAQg1AAgYgaQgcggAAg9QAAglAGgTQAFgTAAglQAAgegXgWIgHgEQgHAcgTAeQgQAbgfAkQAYATAfArQApA7AAA0QAABPg5AAQgbAAgOgxIgQARIgGAGQAhAtBXBMQASASABAPQAAA5gtAAQguAAgrg5Qgvg8ABg1IAAgIQgZAQgYAGQAgA1BPBWQAQAUAAASQABA5guAAQgrAAgphBQgrhHAAg+QAAgTABgMQhxgCAAhgQgBgrBPhjQgLAIgLAAQgxAAAAhHQAAgnAPgwQASg3AAgpQABgGgGgSQgFgOgBgLQABgeAhAAQAtAAAeAtQAIAPAHAAQAGAAANgPQA1gwAlAAQAlAAAeAkQAWAbABAlQAfgPA+gSQAygNAAgJQAAgMgKgKQgJgJAAgLQAAgGALgJQAKgIAbAAQApAAAiAQQAiASAAAXQAAAThCAKQh7AWgZAYIAIAEQAJAAAlgOQCEgrBJAAQBLAAAzAbQAwAZgBA1QABB2gLAvQAOAMAAAWQAAAtgqAAIglAAQAPAHAXAOQApAgAAAYQgBAcg+AcQgpATgfAMQAeASAhAcQBPBCAABMQAABGg8AAQgXAAgYguQghg8gdgvIAABiQAABGhEAAQgoAAhWgygEAnEAEZIgXAqIAhADQAXAAAAgZIAAhZQgMAggVAlgEApMgADQAZAWAFA8IAVgPQAcgWAAgcQABgRAHgGQgzABgkAFgEAg+AAAQgPARgBAJQABATAPAAQAdAABTg4QgMgwgKgbQgnAngzAvgEAmmgBZQAAAbA/AAQAlAABDgUQAegJAcgFIgBguQg7AIg7ANQg/ARgkAAIgHAAIAAAPgEAgkgCEIgGALQAug2BBhGQAzgyAAgPQAAgPgSAAQghAAhpDBgEAmmgDoQALAPAAAQIAAALIBDgUQBCgWAvAAQAPAAAOACIAAgRQABgeguAAQgpAAiGAtgAfWFnQgghLABhCQgBhLAXAAQAQAAAOAWQAYA5BABeQANAVAAATQAABHg8AAQggAAgehEgAJnGFQgrgpAAhSIAAiWQAAgYgJgRIgQADQAGAQAAAWQAABcg6B1QgxBjgzAAQgnAAgageQgYgfAAgwQABghAWgGIANgEQAZgGAhgzQAhgzAAgwQAAgVgEgOQgbgHgQgRQgggmABhHQgBgSACgPQgLADgNAAIgmAMIAADJQAABPhKAAQgZAAgfgEQgcgEgOAAQgLAAAAAQQAAASAhAAQAVAAAzgQQBSgbBSgrQAWgLAFAAQAIAAgBAHQAAARggAtQgrA6hBArQg3AlglAAQg1AAgmghQgpggAAgtQAAghAVgVQAUgXAfgFQAlgGAAgkIAAiNQgyAAgggUQgbgPAAgSQABgRARgOQAYgUATAAIAOAAQAGAAAcgVIAAiGQABgVgQgcQgLgVAAgMQAAgmAtAAQAjAAAmAWQArAcAAA8IAABmQAgAFAbARQAJAIAHAHIAAgPQABghgMgbQgPgTAAgYQAAgVBwgjQAtgNAAgJQABgNgLgLQgMgMAAgNQAAgIAOgKQALgMAjAAQAzAAAqAUQAqAWAAAdQAAAThBALQiYAYgBAgIAAAEIAIAAQAKAAAlgMQCBgsBHAAQBPAAA1AhQAxAggBBAQAADLgPAhQgRAcguAAIgHAAIATAIQAVAMAAAWIgBAEQAQAKAWARQAjAdAAAhQAAA4gtAAIALAQQAmA1AAAiQgBAfghARQglAVhlAAQhhAAglgmgAK4EKQAAAxA1AAQAkAAAYgLQAVgMABgQQAAgPgEgMIgPAKQgmAWghAAQgWAAgSgXIgFgNgALsDKQAAAUAPAAQAKAAAWgWQANgMAHgKIgSgcQgxAkAAAQgAKhA0QAWAYABAoIAAA4QAIgUAVgbQAMgPAAgIQAAgFgEgLQAAgdAiAAIAMABQgIgFgEgEQg1AAgpADgAHig0QAAAfA8AAQAJAAAKgDIAAgBIABgpQgUAEgPAAQgZAAgUgEIAAAOgAKthbIAAAnQAegFAbgBIABgqIg6AJgAIAjIIgRAGQACAKAAAKIgBAUQAYgGAsgOQgBgVgHgUIgsAPgALsjKIAAgWQAAgagxAAQgJAAgOACQAMASAAAZIAPAAQAXAAAWADgAqYFRQgigUgXgQQgsBOg5AAQhPAAAAheQAAglASgQIAOgNQAcgXA8ihQAdhCAOg2QhCgDgogVQgtgWgBgdQAAgTAYgRQAXgNAYAAIAOACQAKACAHAAQAeAADUg9QgKgxgagoQgPgWAAgQQAAgpA4AAQA9AAA6AxQAZAYALA4QA5gJAvAAQBhAABRApQA2AfABAlQAAAyhqACQgWABgWACQBDBiAuCDQAsB6AABkQAABVhPAAQg6AAgcg8Qg4k5g9iXQgYADgYAEIAAGqQAACEhSAAQhDAAiPhagApshcQAEAUAAAYQAAB9hSCyQBxAeAOAAQAeAAAAgiIAAljQgrAIgkAEgAzLGGQhIgshHAAQhbAAhkApQhlAohEAAQgnAAgagWQgZgXAAgaQAAgWAIgRQALgWAYgIIgBgKIAAgwQAAgagHgNQgFgIAAgNQABgtA5AAQAaAAAUAJIA+gFQFSgiBZAAQBEAAAiAYQAlAaAABGQgBA3gTASQgOARgiAAIgMAAQAJABAHADQBSAYABAcQgBBDhSAAQgpAAhAglgA6hFCQgCACgFABQgbACgLAHQgGAJgBANQABATAsAAQAVAAAegSQAugZApgRQhUAGgvABgA5yD6QAEAQAoAAQAYAABVgJIAAgTQhcAKg9ACgA1KDhIAAARQBegJA4gDIABgQIiXALgA5BCxIg4AFIAEAUQA2gDBlgLQgDgFgHgJIgHgFIhWAIgA1ZCfQAHAIAEAIQBZgGBEAAQgEgPghAAQgwAAhTAFgAWVF2QgfgkgEg1QgJAeghAAQglAAgjg+QglhCAAg8IAAgKQgcARgbAJIADADQAaA2BEBaQAPAVAAATQAAA8gyAAQgjAAgihCQgihGAAg/QAAgaACgPIgLAAQh/AAAAhiQgBgwBmh5QgMAJgLAAQgwAAgBhDQABgmAPguQASg1ABgoQAAgFgIgQQgHgNgBgLQABgeAhAAQAtAAAdAuQAJAOAHAAQAGAAALgNQAygvAiAAQAmAAAfAmQAJAMAFAOQAHgOAXAAQAqAAAhAeIAHAHIAcgMQB/gwBHAAQBLAAAzBEQAuBDAACEQAAGjgPBHQgNA3goAAQgdAAgRgSQiXAXhUAAQg5AAgqgrgAXaEOQAAAlAeAAIAYAAIgBgGIADjXIgDAAQgdAAgWgHgAaKBCIgDDfQApgKAegDIAAjegAUSBLIgKAIQAbA0BDBXQAIAJADAJIAAioQgOAWgbAAQgaAAgMgkIgQARgAR7gIQgQAQgBALQABASAQAAQAjAABphFQgQg1gKgXIgDgEQguAuhBA6gAXwgHQAHAAAdgLIACi0QAAgcgFgUIgsASIgEACIgDDYIAFAAgAVek6QABA0glA5QgPAXgbAeQAaAHAuA/QAQAYAJAWIAAjWQAAgegSgnIgBgBIAAAGgAbOgxIAAjGQAAgpgtAAQgMAAgWAFQAPAjAABMIgCB2IAYgBQAWAAAUAGgAR0ibIgKARQAsg0A7g9QA3gyAAgRQAAgPgTAAQgfAAhiCygA85BtQgTgPAAgIQAAgRAUgMQAXgMAQAAQAEAAAEACQAGACAFAAQAXAAA/gKQFNgxDXAAQBJAAAsAWQAoAWAAAXQABAdgiAAQgdAAgegFQgjgCg1AAQjAAAjhAdQiEAQgvAAQgyAAgYgPgA6lgMQgLgNgGgRIgmACQgxAAgZgOQgTgQAAgIQAAgRATgMQAYgMAQAAIAHACQAHACAFAAQAOAAAigGQgBgNgCgGQgDgIgBgFQAAglAxAAQAkAAAVAQQANAKAJATQCjgeCBgLQgEgHAAgJQAAghAqAAQAmAAAfAQIgCgNIAAgHQAAgLgEgJIhIALQhBANgjAAQgjAAgUgTQgUgTAAgTIAAgDQgKADgNAAIg5AKQAjAWAAAVQAABLg0AAQgdAAgUgkQgWgngXgaIgpAIIgEAAQgFAJgHAKQgqA4ggAAQgmAAgXgaQgagcAAgdQAAgbATAAQAJAEAGAAQAKAAAXgdQATgXABgPQAAgKgDgKIgBgSQAAgdApAAQAcAAAbAWQASAOACAiIAFgDQBCgiBEAAQAmAAAcAUQAbAVAAAXIAAAJIAZgPQAYgLAAgKQAAgNgWgKQgWgLgBgOQABgSASgLQARgJAWAAQBAAAAqAbQAfAUAAAVIgBAEQAygTApAAQA6AAAuAbQAfAVAAAXQABAgg5AFIgPACIAAACQAAAbggAdQgVATgaAAQgKAAgJgCIAIAKQA7ADAmAWQAqAXAAAXQAAAigiAAQgdAAgggEIg0gDQgGAOgIALIgEAGQALAKAAAOQAAAWgeACQjRAEiYAPQgoAFgXAAQgnAAgWgXgA4rg9QALAGASAAQATAAAxgFQBygOBCgDIAAgMIAAgCQiEAGiRAYgAz6lfQg6AGgiAMQgeALAAAMQAAAPAYAAQAJAAAZgQQAkgYAggRIgEABgEgkMgDNQgaABgcADQgeADgMAAQg7gGgFgxQAAgJADgWIABgxQAAgWgLgPQgEgMAAgHQAAgaAWAAQAXAAAUAOIALgFQAkgVATAAQA0AAAkAUQAgASAAAlQAAB2gLAVQgMAPghAAQgPAAgJgHgEglWgFOIgEAyQAAAPAPAAQALAAANgGIAYgHIABgoQAAgageAAQgIAAgWAOgEggOgDcQgYABgcAEIgrACQg7gGgFgyIACgbQACgXAAgVQAAgUgIgPQgDgLAAgHQgBgZAUAAQAPAAAOAGIALAAQAEAAAKgFQAlgVAVAAQA1AAAjAUQAgASAAAlQAAB2gMAUQgKAQgjAAQgRAAgLgLgEghbgFVIgDArQAAAOAPAAQALAAAPgFIAcgIQACgRAAgTQAAgageAAQgKAAgcASg");
	this.shape.setTransform(0,0.025);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FF0000").ss(8,1,1).p("Af2mfQAtAAAeAtQAJAPAGAAQAGAAANgPQA1gwAlAAQAmAAAeAkQAVAbABAlQAfgPA/gSQAxgNAAgJQAAgMgKgKQgJgJAAgLQAAgGALgJQAKgIAcAAQAoAAAjAQQAhASAAAXQAAAThCAKQh7AWgYAYIAHAEQAJAAAmgOQCDgrBJAAQBLAAA0AbQAvAZAAA1QAAB2gLAvQAOAMAAAWQAAAtgqAAQgTAAgRAAQAPAHAWAOQApAgAAAYQAAAcg/AcQgpATgfAMQAeASAhAcQBPBCAABMQAABGg8AAQgXAAgYguQghg8gdgvIAABiQAABGhDAAQgpAAhWgyQgNgJgKgGQgbAjgSAAQgpAAgjgbQglgYAAgQQAAgLANgEQA1gVA6hPQApg3AAgRQAAgIgHAAQgFAAgWAMQgsAWgMAAQgtAAAAgqQAAgSANgXQARgTAMAAQAMAEAGAAQAIAAAcgHQAbgHAVAAQAkAAAZAUQACACADACQgCgggTgaQgoAHgdAAQg1AAgYgaQgcggAAg9QAAglAGgTQAGgTAAglQAAgegYgWQgEgCgCgCQgIAcgTAeQgQAbgfAkQAYATAfArQApA7AAA0QAABPg4AAQgcAAgOgxQgIAJgIAIQgDADgDADQAiAtBWBMQATASAAAPQAAA5gtAAQgtAAgsg5Qgug8AAg1QAAgFAAgDQgZAQgYAGQAhA1BOBWQARAUAAASQAAA5gtAAQgsAAgphBQgrhHAAg+QAAgTACgMQhygCAAhgQAAgrBOhjQgKAIgMAAQgxAAAAhHQAAgnAPgwQATg3AAgpQAAgGgGgSQgFgOAAgLQAAgeAhAAgEAgfgB5QAtg2BBhGQA0gyAAgPQAAgPgTAAQghAAhpDBQgDAGgCAFgARFmrQAtAAAdAuQAKAOAGAAQAGAAALgNQAygvAjAAQAlAAAfAmQAJAMAFAOQAIgOAWAAQAqAAAhAeQAEADADAEQAKgEASgIQB/gwBHAAQBLAAAzBEQAuBDAACEQAAGjgOBHQgNA3goAAQgeAAgQgSQiXAXhVAAQg5AAgpgrQgggkgEg1QgJAeghAAQglAAgjg+QglhCAAg8QAAgFAAgFQgcARgaAJQABACABABQAaA2BEBaQAPAVAAATQAAA8gxAAQgkAAgihCQgihGAAg/QAAgaADgPQgHAAgFAAQh/AAAAhiQAAgwBmh5QgMAJgLAAQgxAAAAhDQAAgmAPguQATg1AAgoQAAgFgIgQQgHgNAAgLQAAgeAhAAgAXegKQACAAADAAIAOADQAGAAAdgLIACi0QAAgcgEgUQgWAJgWAJQgCABgDABgAZ/kbQAPAjAABMIgCB2QANgBAMAAQAVAAAUAGIAAjGQAAgpgtAAQgMAAgWAFgAbOEUIAAjeIhDAMIgEDfQApgKAegDgAYQEzQgBgDAAgDIAEjXIgEAAQgcAAgXgHIgCC/QAAAlAeAAQALAAANAAgEAiugALQgMgwgKgbQgnAngzAvQgPARAAAJQAAATAPAAQAdAABTg4gAfNCPQARAAANAWQAYA5BABeQANAVAAATQAABHg8AAQggAAgehEQgfhLAAhCQAAhLAWAAgEAmxgC+QAbgIAogMQBCgWAvAAQAQAAAOACQAAgIAAgJQAAgegtAAQgqAAiGAtQALAPAAAQQAAAGAAAFgEAqHgBgQAAgTgBgbQg7AIg7ANQg+ARglAAQgEAAgDAAQAAAHAAAIQAAAbA/AAQAmAABCgUQAegJAcgFgEAnlADUQgMAggVAlQgNAYgKASQAcADAGAAQAWAAAAgZgEApqABPQALgHAKgIQAcgWAAgcQABgRAHgGQgyABglAFQAZAWAFA8gEgrYgFYIATAIQALAABGg6QAoghAgAAQAtAAAoAdQAgAXAAAbQAAAmgnCKQAbAWAAAXQAAAmgtAAIiZAkQgIAZgTArQAAAIAEAAQBtgkAeAAQBUAAACBQQAAA9g0CKQhAClg4AAQgZAAhIhiQg9hSAAgPQAAgDAEgBQACAAAiAbQAtAeAUAAQAWAAAmhXQAehLAAgdQgCgIgRAAQgKAAgyAWQg8AfgPAAQg0gCAAgvQAAgTAnhMQANgcAIgUQgRgEgNgIQgXgMAAgQQAAgPARgLQAUgSAQAAIALAAQAIAAAmgYQAqgZAogIQABgEACgFQAbhVAAgIQAAgagPAAQgPAAgeAkQg1A6gTAAQghAAgegZQgbgXAAgaQAAgVATgMQARgNARAAgEgiigGiQAPAAAPAGIALAAQADAAAKgFQAmgVAVAAQA0AAAkAUQAgASAAAlQAAB2gMAUQgLAQgiAAQgSAAgKgLQgYABgcAEQgfACgMAAQg7gGgFgyQAAgHACgUQACgXAAgVQAAgUgIgPQgEgLAAgHQAAgZATAAgEggZgEpQACgRAAgTQAAgageAAQgLAAgcASIgCArQAAAOAPAAQALAAAPgFQASgGAKgCgEgmUgC2QAVAAARATQACAAAAgBIAPAAQAOAAAagHQCqgqA4AAQBFAAA8AmQArAjAAAvQAAB1gVA3QAIALAAAMQAAAmg2AGQhIAAg+AGIgBAxQBGgKA2AAQAjAAAbAVQAcASAAAhQAAAzhEABQhVAEhAADIgBAbQAABShHAAQhAAAAAhLIAAgVQg3AHgyAAQg+AAgegbQgggbAAghQAAgkBagtQAOgGAHgFQgQgJgLgLQgcgcgDgsQgDiJgIgeQgIgXAAgWQAAgpArAAgA7NmmQAcAAAcAWQARAOACAiQACgCACgBQBDgiBEAAQAlAAAeAUQAaAVAAAXQAAAFgBAEQALgHAPgIQAYgLAAgKQAAgNgWgKQgXgLAAgOQAAgSATgLQARgJAWAAQBAAAApAbQAgAUAAAVQAAACAAACQAxgTApAAQA6AAAtAbQAhAVAAAXQAAAgg5AFQgIABgHABQAAABAAABQAAAbggAdQgWATgZAAQgKAAgJgCQAEAFAEAFQA7ADAmAWQAqAXAAAXQAAAigiAAQgdAAgggEQgXgCgdgBQgGAOgJALQgBADgCADQALAKAAAOQAAAWgeACQjRAEiYAPQgoAFgXAAQgnAAgVgXQgMgNgFgRQgZACgOAAQgxAAgZgOQgUgQAAgIQAAgRAUgMQAZgMAPAAQACAAAFACQAGACAGAAQAOAAAigGQgBgNgCgGQgEgIAAgFQAAglAxAAQAkAAAUAQQAPAKAIATQCjgeCBgLQgEgHAAgJQAAghAqAAQAmAAAfAQQgCgGAAgHIAAgHQAAgLgEgJQgjAGgmAFQg/ANgkAAQgiAAgWgTQgTgTAAgTQAAgBAAgCQgJADgOAAIg6AKQAkAWAAAVQAABLg1AAQgcAAgUgkQgWgngXgaIgqAIQgBAAgCAAQgFAJgIAKQgoA4giAAQglAAgYgaQgZgcAAgdQAAgbATAAQAJAEAGAAQALAAAWgdQATgXAAgPQAAgKgBgKQgCgMAAgGQAAgdApAAgEgmhgGfQAXAAAUAOQAEgBAHgEQAjgVAUAAQA0AAAkAUQAgASAAAlQAAB2gLAVQgNAPggAAQgPAAgJgHQgaABgcADQgeADgMAAQg7gGgFgxQAAgJADgWQABgZAAgYQAAgWgKgPQgFgMAAgHQAAgaAWAAgEgkbgEaQABgSAAgWQAAgageAAQgIAAgXAOIgDAyQAAAPAPAAQALAAANgGQAOgFAKgCgEglJgAkQAbgFA4gOQgFgWgKgPQguAMgbAFQADATACAUgEgjzABLIABgwQgnAHgbAAQgIAAgHAAQAAABAAACQADAmA9AAQAHAAAJAAgEgj4ADkIACg6QghAHgSAAQgFAAgDgCQhoArAAASQAAATAWAAQAeAAA6gQQAagHAZgEgA8RAtQAEAAAEACQAGACAFAAQAXAAA/gKQFOgxDWAAQBJAAAsAWQApAWAAAXQAAAdgiAAQgcAAgegFQgkgCg1AAQjBAAjfAdQiFAQgvAAQgyAAgYgPQgUgPAAgIQAAgRAVgMQAXgMAQAAgEgiQgB8QACABABABQANAMAJAcQAZgDAWAAQARAAARACQAAgBAAgBQAAgwgtAAQgaAAgjAJgEgg5AAiQABgDABgEQAFgQACgOQgfACgeAEQAAAJAAALIAAATQAegHAWgBgA6XCFQAbgCAjgDQFUgiBYAAQBEAAAiAYQAkAaAABGQAAA3gTASQgOARgiAAQgGAAgGAAQAIABAIADQBTAYAAAcQAABDhTAAQgoAAhBglQhIgshHAAQhcAAhjApQhlAohEAAQgnAAgagWQgZgXAAgaQAAgWAIgRQALgWAYgIQgCgFAAgFIAAgwQAAgagGgNQgFgIAAgNQAAgtA6AAQAbAAASAJgA1cknQAJAAAZgQQAkgYAggRQgCABgCAAQg6AGgiAMQgeALAAAMQAAAPAYAAgA4sg9QALAGATAAQATAAAxgFQBygOBCgDQAAgGAAgGQAAgBAAgBQiEAGiSAYgA3rCpQgoADgtAFQggADgZACQACAJACALQA1gDBmgLQgDgFgIgJQgEgDgCgCgA6hFCQgCACgFABQgaACgMAHQgHAJAAANQAAATAtAAQAVAAAegSQAugZAqgRQhVAGgvABgA3ZDuQhcAKg9ACQADAQApAAQAYAABVgJgA1NCvQBXgGBFAAQgEgPgiAAQguAAhUAFQAHAIAFAIgAy0DmQABgHAAgJQhMAFhMAGIAAARQBfgJA4gDgAsyjRQAEAAAJACQAKACAHAAQAeAADTg9QgJgxgagoQgPgWAAgQQAAgpA4AAQA9AAA6AxQAZAYAMA4QA4gJAvAAQBhAABRApQA3AfAAAlQAAAyhpACQgXABgWACQBDBiAtCDQAtB6AABkQAABVhPAAQg6AAgcg8Qg4k5g8iXQgZADgYAEIAAGqQAACEhSAAQhEAAiOhaQgigUgXgQQgsBOg5AAQhPAAAAheQAAglASgQIAOgNQAcgXA8ihQAdhCAOg2QhBgDgpgVQgtgWAAgdQAAgTAYgRQAWgNAZAAgAprhcQADAUAAAYQAAB9hSCyQBxAeAOAAQAeAAAAgiIAAljQgrAIgjAEgABviFIAPAAQAFAAAdgVIAAiGQAAgVgPgcQgMgVAAgMQAAgmAtAAQAkAAAlAWQAsAcAAA8IAABmQAfAFAbARQAKAIAHAHQAAgHAAgIQAAghgMgbQgPgTAAgYQAAgVBxgjQAtgNAAgJQAAgNgLgLQgMgMAAgNQAAgIAOgKQAMgMAiAAQA0AAApAUQAqAWAAAdQAAAThBALQiYAYAAAgQAAACAAACIAHAAQALAAAkgMQCCgsBHAAQBPAAA1AhQAwAgAABAQAADLgQAhQgQAcgvAAQgEAAgDAAQAJADAKAFQAWAMAAAWQAAADgBABQAQAKAVARQAjAdAAAhQAAA4gtAAQAGAHAFAJQAmA1AAAiQAAAfghARQgmAVhlAAQhhAAglgmQgrgpAAhSIAAiWQAAgYgJgRQgIABgHACQAFAQAAAWQAABcg6B1QgxBjgyAAQgoAAgageQgXgfAAgwQAAghAWgGQgCAAAPgEQAZgGAhgzQAhgzAAgwQAAgVgDgOQgcgHgQgRQgfgmAAhHQAAgSABgPQgLADgNAAIglAMIAADJQAABPhLAAQgZAAgfgEQgcgEgOAAQgLAAAAAQQAAASAiAAQAUAAA0gQQBRgbBSgrQAWgLAFAAQAIAAAAAHQAAARghAtQgrA6hBArQg3AlglAAQg1AAgmghQgoggAAgtQAAghAUgVQAUgXAfgFQAmgGAAgkIAAiNQgzAAgggUQgagPAAgSQAAgRASgOQAYgUASAAgAHwiaQAYgGAtgOQgBgVgIgUQgVAIgXAHQgJAEgIACQACAKAAAKQAAALgBAJgAIxgYQAAgBAAAAIABgpQgUAEgPAAQgZAAgTgEQgBAIAAAGQAAAfA8AAQAJAAAKgDgARriKQAsg0A7g9QA2gyAAgRQAAgPgSAAQgfAAhjCyQgFAJgEAIgAVxgkIAAjWQAAgegSgnQAAgBAAAAQAAADAAADQAAA0gkA5QgPAXgbAeQAaAHAuA/QAPAYAJAWgAKkj4QAMASAAAZQAIAAAHAAQAYAAAVADQAAgKAAgMQAAgagwAAQgKAAgOACgALmg6QABgUABgWQgdAEgeAFIAAAnQAegFAbgBgAK4CsQAIgUAVgbQAMgPAAgIQAAgFgEgLQAAgdAiAAQAGAAAGABQgHgFgFgEQg1AAgpADQAXAYAAAogAMwCyQgKgQgIgMQgyAkAAAQQAAAUAPAAQALAAAVgWQANgMAIgKgAM8D5QgIAFgIAFQglAWgiAAQgWAAgSgXQgDgHgCgGIAAAVQAAAxA1AAQAkAAAYgLQAWgMAAgQQAAgPgDgMgAQRCSQARAAANAXQAYA7BABhQANAXAAATQAABIg8AAQggAAgehIQgghOAAhDQAAhMAXAAgAVxDwIAAioQgOAWgbAAQgZAAgMgkQgIAIgJAJQgFAEgFAEQAbA0BEBXQAHAJADAJgAUHggQgQg1gKgXQgCgCgBgCQguAuhBA6QgQAQAAALQAAASAQAAQAjAABphFg");
	this.shape_1.setTransform(0,0.025);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AQaFvQgghOAAhDQAAhMAWAAQASAAANAXQAYA7BABhQANAXAAATQAABIg8AAQggAAgehIgEgj8AFkIAAgVQg3AHgxAAQg+AAgggbQgegbAAghQgBgkBbgtQANgGAHgFQgQgJgLgLQgcgcgDgsQgDiJgIgeQgHgXAAgWQAAgpApAAQAWAAARATQAAAAABAAQAAAAAAgBQABAAAAAAQAAAAAAAAIAPAAQAOAAAagHQCqgqA4AAQBGAAA6AmQAsAjAAAvQABB1gWA3QAIALAAAMQAAAmg2AGQhIAAg+AGIgBAxQBGgKA2AAQAkAAAaAVQAcASAAAhQAAAzhDABIiWAHIgBAbQAABShHAAQhAAAAAhLgEgmZADsQAAATAWAAQAeAAA6gQQAagHAZgEIACg6QghAHgSAAQgEAAgEgCQhoArAAASgEglDAAlQADAmA9AAIAQAAIABgwQgnAHgbAAIgPAAIAAADgEghtAADIAAAUIAAATQAegHAXgBIABgHQAFgQADgOQgfACgfAEgEglOgBLIAGAnIBSgTQgFgWgKgPQguAMgbAFgEgiQgB8IADACQANAMAJAcQAZgDAWAAQARAAARACIAAgCQAAgwgtAAQgaAAgjAJgEgrMAFNQg8hSAAgPQAAgDADgBQACAAAiAbQAuAeAUAAQAVAAAmhXQAehLABgdQgDgIgRAAQgKAAgxAWQg8AfgQAAQg0gCAAgvQAAgTAnhMQANgcAIgUQgRgEgNgIQgWgMgBgQQAAgPAQgLQAVgSAQAAIAMAAQAHAAAmgYQAqgZApgIIACgJQAbhVAAgIQAAgagPAAQgOAAgfAkQg0A6gUAAQghAAgegZQgbgXAAgaQAAgVAUgMQAQgNARAAIATAIQALAABGg6QAoghAgAAQAuAAAnAdQAgAXAAAbQAAAmgnCKQAbAWAAAXQAAAmgtAAIiZAkQgHAZgUArQAAAIAFAAQBsgkAeAAQBUAAADBQQAAA9g1CKQhAClg4AAQgZAAhIhigEAmqAF5IgYgPQgbAjgSAAQgoAAgjgbQglgYAAgQQAAgLANgEQA0gVA7hPQApg3AAgRQAAgIgIAAQgEAAgXAMQgrAWgMAAQgtAAAAgqQAAgSANgXQARgTAMAAQALAEAHAAQAHAAAdgHQAbgHAVAAQAkAAAZAUIAFAEQgCgggTgaQgoAHgdAAQg1AAgYgaQgcggAAg9QAAglAFgTQAHgTAAglQAAgegYgWIgGgEQgIAcgTAeQgQAbgfAkQAYATAeArQAqA7AAA0QAABPg4AAQgcAAgPgxIgQARIgFAGQAiAtBWBMQASASAAAPQAAA5gtAAQgtAAgsg5Qgtg8gBg1IAAgIQgYAQgYAGQAhA1BNBWQARAUABASQgBA5gsAAQgsAAgphBQgrhHAAg+QAAgTACgMQhzgCAAhgQABgrBOhjQgKAIgNAAQgwAAAAhHQAAgnAPgwQATg3AAgpQgBgGgFgSQgGgOABgLQgBgeAiAAQAtAAAeAtQAIAPAHAAQAFAAAOgPQA1gwAlAAQAmAAAeAkQAVAbABAlQAegPBAgSQAwgNAAgJQAAgMgJgKQgKgJAAgLQAAgGAMgJQAKgIAcAAQAnAAAkAQQAhASAAAXQAAAThDAKQh6AWgYAYIAHAEQAJAAAmgOQCDgrBJAAQBLAAA0AbQAuAZABA1QAAB2gLAvQANAMAAAWQAAAtgpAAIgkAAQAPAHAWAOQAoAgAAAYQABAchAAcQgoATgfAMQAdASAiAcQBPBCAABMQAABGg8AAQgYAAgXguQghg8gdgvIAABiQAABGhDAAQgpAAhWgygEAnEAEZIgXAqIAiADQAWAAAAgZIAAhZQgMAggVAlgEApMgADQAYAWAGA8IAVgPQAcgWAAgcQABgRAGgGQgxABglAFgEAg9AAAQgOARAAAJQAAATAOAAQAdAABUg4QgNgwgJgbQgnAng0AvgEAmlgBZQAAAbBAAAQAmAABCgUQAegJAbgFIgBguQg6AIg7ANQg/ARgkAAIgHAAIgBAPgEAgkgCEIgFALQAsg2BChGQAzgyABgPQAAgPgTAAQghAAhpDBgEAmlgDoQALAPAAAQIAAALIBEgUQBCgWAuAAQARAAAOACIAAgRQgBgegsAAQgqAAiHAtgAfWFnQgfhLgBhCQABhLAWAAQAQAAAOAWQAYA5BABeQANAVAAATQAABHg8AAQggAAgehEgAJnGFQgrgpAAhSIAAiWQAAgYgKgRIgOADQAFAQAAAWQAABcg6B1QgxBjgyAAQgoAAgageQgYgfABgwQgBghAXgGIANgEQAYgGAigzQAhgzAAgwQAAgVgDgOQgcgHgQgRQgfgmgBhHQABgSABgPQgLADgNAAIglAMIAADJQAABPhMAAQgYAAgfgEQgcgEgOAAQgMAAAAAQQAAASAjAAQAUAAA0gQQBRgbBRgrQAXgLAFAAQAHAAABAHQAAARgiAtQgqA6hCArQg3AlgkAAQg1AAgmghQgpggAAgtQABghAUgVQAUgXAfgFQAmgGAAgkIAAiNQg0AAgfgUQgbgPAAgSQAAgRASgOQAZgUARAAIAQAAQAFAAAdgVIAAiGQAAgVgPgcQgMgVAAgMQAAgmAtAAQAjAAAmAWQArAcABA8IAABmQAfAFAaARQAKAIAIAHIAAgPQAAghgMgbQgPgTAAgYQAAgVBwgjQAugNgBgJQAAgNgLgLQgLgMAAgNQAAgIAOgKQAMgMAiAAQAzAAAqAUQAqAWAAAdQAAAThCALQiYAYAAAgIAAAEIAIAAQALAAAkgMQCCgsBHAAQBPAAA0AhQAxAgAABAQgBDLgQAhQgPAcgvAAIgHAAIATAIQAVAMABAWIgBAEQAQAKAVARQAjAdAAAhQAAA4gtAAIALAQQAlA1AAAiQABAfgiARQglAVhlAAQhiAAgkgmgAK3EKQABAxA1AAQAjAAAZgLQAWgMgBgQQAAgPgCgMIgQAKQglAWgjAAQgVAAgSgXIgGgNgALsDKQAAAUAPAAQAKAAAWgWQANgMAHgKIgSgcQgxAkAAAQgAKhA0QAXAYgBAoIAAA4QAJgUAUgbQANgPAAgIQAAgFgEgLQAAgdAiAAIAMABQgIgFgEgEQg1AAgpADgAHig0QAAAfA8AAQAJAAAJgDIAAgBIABgpQgTAEgPAAQgZAAgUgEIAAAOgAKthbIAAAnQAegFAagBIACgqIg6AJgAIAjIIgRAGQACAKAAAKIgBAUQAXgGAugOQgCgVgHgUIgsAPgALsjKIAAgWQAAgagwAAQgKAAgOACQAMASAAAZIAPAAQAYAAAVADgAqYFRQghgUgYgQQgsBOg5AAQhPAAAAheQAAglASgQIAOgNQAcgXA8ihQAdhCAOg2QhCgDgogVQgtgWAAgdQAAgTAYgRQAWgNAZAAIAMACQALACAGAAQAfAADTg9QgJgxgagoQgPgWAAgQQAAgpA4AAQA9AAA6AxQAYAYANA4QA4gJAvAAQBhAABRApQA3AfgBAlQAAAyhoACQgXABgWACQBDBiAtCDQAtB6AABkQAABVhPAAQg6AAgcg8Qg5k5g7iXQgZADgYAEIAAGqQAACEhTAAQhDAAiOhagAprhcQADAUAAAYQAAB9hTCyQByAeAOAAQAeAAAAgiIAAljQgrAIgjAEgAzLGGQhHgshHAAQhdAAhjApQhlAohDAAQgoAAgbgWQgYgXABgaQAAgWAHgRQALgWAXgIIgBgKIAAgwQAAgagGgNQgEgIAAgNQAAgtA4AAQAcAAASAJIA+gFQFUgiBYAAQBEAAAiAYQAkAaAABGQABA3gUASQgNARgjAAIgMAAQAIABAIADQBTAYgBAcQABBDhTAAQgoAAhBglgA6hFCQgCACgFABQgaACgMAHQgHAJAAANQAAATAtAAQAVAAAegSQAugZAqgRQhVAGgvABgA5yD6QADAQApAAQAYAABVgJIAAgTQhcAKg9ACgA1LDhIAAARQBfgJA4gDIABgQIiYALgA5ACxIg4AFIADAUQA1gDBmgLQgDgFgIgJIgGgFIhVAIgA1ZCfQAIAIAEAIQBXgGBFAAQgDgPgjAAQguAAhUAFgAWWF2QghgkgDg1QgJAeghAAQglAAgkg+QgkhCAAg8IAAgKQgcARgaAJIABADQAbA2BEBaQAOAVAAATQAAA8gwAAQgkAAgihCQgjhGAAg/QAAgaAEgPIgMAAQiAAAAAhiQABgwBlh5QgLAJgLAAQgyAAAAhDQAAgmAPguQAUg1gBgoQAAgFgHgQQgIgNABgLQgBgeAiAAQAtAAAdAuQAJAOAHAAQAFAAAMgNQAxgvAkAAQAlAAAeAmQAKAMAFAOQAIgOAWAAQAqAAAhAeIAGAHIAcgMQCAgwBGAAQBMAAAzBEQAuBDAACEQAAGjgOBHQgNA3goAAQgeAAgQgSQiYAXhUAAQg5AAgpgrgAXaEOQAAAlAeAAIAXAAIgBgGIAFjXIgFAAQgbAAgXgHgAaLBCIgFDfQAqgKAegDIAAjegAURBLIgJAIQAbA0BDBXQAIAJADAJIAAioQgOAWgbAAQgZAAgMgkIgSARgAR6gIQgQAQAAALQAAASAQAAQAkAABphFQgQg1gKgXIgDgEQguAuhCA6gAXxgHQAGAAAdgLIACi0QAAgcgFgUIgrASIgFACIgDDYIAEAAgAVfk6QgBA0gjA5QgQAXgaAeQAZAHAvA/QAOAYAKAWIAAjWQAAgegSgnIAAgBIAAAGgAbOgxIAAjGQAAgpgtAAQgMAAgWAFQAPAjAABMIgCB2IAZgBQAVAAAUAGgAR0ibIgKARQAtg0A7g9QA2gyAAgRQAAgPgSAAQgfAAhjCygA85BtQgUgPAAgIQAAgRAVgMQAXgMARAAQADAAAEACQAHACAFAAQAWAAA/gKQFOgxDWAAQBJAAArAWQApAWABAXQgBAdghAAQgdAAgdgFQgkgCg0AAQjCAAjgAdQiEAQguAAQgyAAgZgPgA6kgMQgMgNgFgRIgnACQgwAAgagOQgUgQAAgIQAAgRAUgMQAZgMAQAAIAGACQAHACAFAAQAOAAAigGQgBgNgCgGQgDgIAAgFQAAglAwAAQAlAAATAQQAPAKAIATQCjgeCAgLQgCgHAAgJQAAghApAAQAmAAAfAQQgCgGABgHIAAgHQAAgLgFgJIhJALQg/ANgkAAQgiAAgWgTQgTgTAAgTIAAgDQgJADgOAAIg6AKQAkAWAAAVQAABLg1AAQgdAAgSgkQgXgngWgaIgrAIIgCAAQgGAJgIAKQgoA4giAAQglAAgYgaQgZgcABgdQAAgbASAAQAJAEAGAAQALAAAWgdQAUgXgBgPQAAgKgBgKIgCgSQAAgdApAAQAcAAAbAWQASAOACAiIAEgDQBDgiBEAAQAlAAAdAUQAbAVAAAXIgBAJIAagPQAZgLAAgKQAAgNgXgKQgXgLABgOQAAgSASgLQARgJAVAAQBBAAApAbQAgAUABAVIgCAEQAygTAqAAQA6AAAsAbQAgAVABAXQAAAgg5AFIgPACIAAACQAAAbggAdQgVATgZAAQgLAAgIgCIAHAKQA7ADAlAWQArAXAAAXQAAAigiAAQgdAAgggEIgzgDQgHAOgJALIgDAGQALAKAAAOQAAAWgeACQjRAEiYAPQgoAFgWAAQgoAAgVgXgA4sg9QALAGAUAAQASAAAxgFQBygOBCgDIAAgMIAAgCQiDAGiTAYgAz6lfQg6AGgiAMQgeALAAAMQAAAPAXAAQAKAAAZgQQAkgYAhgRIgFABgEgkMgDNQgaABgcADQgeADgMAAQg6gGgGgxQAAgJADgWIABgxQAAgWgKgPQgFgMAAgHQAAgaAXAAQAWAAAVAOIALgFQAigVAUAAQA1AAAjAUQAgASAAAlQAAB2gLAVQgMAPghAAQgPAAgJgHgEglXgFOIgCAyQgBAPAPAAQALAAANgGIAZgHIABgoQAAgageAAQgJAAgXAOgEggNgDcQgZABgcAEIgrACQg7gGgFgyIACgbQACgXAAgVQAAgUgHgPQgFgLAAgHQABgZASAAQAPAAAQAGIALAAQACAAAKgFQAmgVAVAAQA0AAAkAUQAgASAAAlQAAB2gLAUQgMAQghAAQgTAAgJgLgEghcgFVIgCArQAAAOAPAAQALAAAPgFIAcgIQACgRAAgTQAAgageAAQgLAAgcASg");
	this.shape_2.setTransform(0,0.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.title, new cjs.Rectangle(-287.7,-47.8,575.4,95.69999999999999), null);


(lib.sliderButton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(3,1,1).p("ACCAAQAAA2gmAmQgmAmg2AAQg1AAgngmQglgmAAg2QAAg1AlgmQAngmA1AAQA2AAAmAmQAmAmAAA1g");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#666666").s().p("AhcBcQglgmAAg2QAAg1AlgmQAngmA1AAQA2AAAmAmQAmAmAAA1QAAA2gmAmQgmAmg2AAQg1AAgngmg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#00FFFF").ss(3,1,1).p("ACMAAQAAA6gpApQgpApg6AAQg5AAgqgpQgogpAAg6QAAg5AogpQAqgpA5AAQA6AAApApQApApAAA5g");

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0000FF").s().p("AhjBiQgogoAAg6QAAg5AogoQAqgqA5AAQA6AAAoAqQAqAoAAA5QAAA6gqAoQgoAqg6AAQg5AAgqgqg");

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#FFFF00").ss(3,1,1).p("ACCAAQAAA2gmAmQgmAmg2AAQg1AAgngmQglgmAAg2QAAg1AlgmQAngmA1AAQA2AAAmAmQAmAmAAA1g");

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF0000").s().p("AhcBcQglgmAAg2QAAg1AlgmQAngmA1AAQA2AAAmAmQAmAmAAA1QAAA2gmAmQgmAmg2AAQg1AAgngmg");

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF00FF").s().p("AhpBpQgsgrAAg+QAAg9AsgrQAsgtA9AAQA+AAArAtQAtArAAA9QAAA+gtArQgrAtg+AAQg9AAgsgtg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_3},{t:this.shape_2}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).to({state:[{t:this.shape_6}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-15.5,-15.5,31,31);


(lib.sliderBGLine = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(5,1,1).p("ArtAAIXbAA");
	this.shape.setTransform(75,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.sliderBGLine, new cjs.Rectangle(-2.5,-2.5,155,5), null);


(lib.btnSquare = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFF00").ss(1,1,1).p("AnznzIPnAAIAAPnIvnAAg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF00FF").s().p("AnzH0IAAvnIPnAAIAAPng");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},3).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-51,-51,102,102);


(lib.checker = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(8,1,1).p("AiLgIIA4AAIAfCFIDAj5");
	this.shape.setTransform(2.25,-4.25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.checker, new cjs.Rectangle(-15.7,-20.7,36,33), null);


(lib.btnUp = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhCD6IAAkzIhTAAICVjAICWDAIhSAAIAAEzg");

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},3).wait(1));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#00FFFF").ss(3,1,1).p("AjHkrIGPAAQBkAAAABkIAAGPQAABkhkAAImPAAQhkAAAAhkIAAmPQAAhkBkAAg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#000066","#0066FF"],[0,1],30,30,30,-29.9).s().p("AjHEsQhkAAAAhkIAAmPQAAhkBkAAIGPAAQBkAAAABkIAAGPQAABkhkAAg");

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#000066","#00FFFF"],[0,1],30,30,30,-29.9).s().p("AjHEsQhkAAAAhkIAAmPQAAhkBkAAIGPAAQBkAAAABkIAAGPQAABkhkAAg");

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#FF00FF").ss(3,1,1).p("AjHkrIGPAAQBkAAAABkIAAGPQAABkhkAAImPAAQhkAAAAhkIAAmPQAAhkBkAAg");

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF00FF").s().p("AjHEsQhkAAAAhkIAAmPQAAhkBkAAIGPAAQBkAAAABkIAAGPQAABkhkAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1,p:{rotation:0}}]}).to({state:[{t:this.shape_3,p:{rotation:0}},{t:this.shape_1,p:{rotation:0}}]},1).to({state:[{t:this.shape_3,p:{rotation:180}},{t:this.shape_1,p:{rotation:180}}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-31.5,-31.5,63,63);


(lib.btnRight = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhDD6IAAk0IhSAAICVi/ICWDAIhSAAIAAEzg");
	this.shape.setTransform(0,0,1,1,90);

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},3).wait(1));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#00FFFF").ss(3,1,1).p("AjHkrIGPAAQBkAAAABkIAAGPQAABkhkAAImPAAQhkAAAAhkIAAmPQAAhkBkAAg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#000066","#0066FF"],[0,1],30,30,30,-29.9).s().p("AjHEsQhkAAAAhkIAAmPQAAhkBkAAIGPAAQBkAAAABkIAAGPQAABkhkAAg");

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#000066","#00FFFF"],[0,1],30,30,30,-29.9).s().p("AjHEsQhkAAAAhkIAAmPQAAhkBkAAIGPAAQBkAAAABkIAAGPQAABkhkAAg");

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#FF00FF").ss(3,1,1).p("AjHkrIGPAAQBkAAAABkIAAGPQAABkhkAAImPAAQhkAAAAhkIAAmPQAAhkBkAAg");

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF00FF").s().p("AjHEsQhkAAAAhkIAAmPQAAhkBkAAIGPAAQBkAAAABkIAAGPQAABkhkAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1,p:{rotation:0}}]}).to({state:[{t:this.shape_3,p:{rotation:0}},{t:this.shape_1,p:{rotation:0}}]},1).to({state:[{t:this.shape_3,p:{rotation:180}},{t:this.shape_1,p:{rotation:180}}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-31.5,-31.5,63,63);


(lib.btnLeft = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhDD6IAAk0IhSAAICVi/ICWDAIhSAAIAAEzg");
	this.shape.setTransform(0,0,1,1,-90);

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},3).wait(1));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#00FFFF").ss(3,1,1).p("AjHkrIGPAAQBkAAAABkIAAGPQAABkhkAAImPAAQhkAAAAhkIAAmPQAAhkBkAAg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#000066","#0066FF"],[0,1],30,30,30,-29.9).s().p("AjHEsQhkAAAAhkIAAmPQAAhkBkAAIGPAAQBkAAAABkIAAGPQAABkhkAAg");

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#000066","#00FFFF"],[0,1],30,30,30,-29.9).s().p("AjHEsQhkAAAAhkIAAmPQAAhkBkAAIGPAAQBkAAAABkIAAGPQAABkhkAAg");

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#FF00FF").ss(3,1,1).p("AjHkrIGPAAQBkAAAABkIAAGPQAABkhkAAImPAAQhkAAAAhkIAAmPQAAhkBkAAg");

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF00FF").s().p("AjHEsQhkAAAAhkIAAmPQAAhkBkAAIGPAAQBkAAAABkIAAGPQAABkhkAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1,p:{rotation:0}}]}).to({state:[{t:this.shape_3,p:{rotation:0}},{t:this.shape_1,p:{rotation:0}}]},1).to({state:[{t:this.shape_3,p:{rotation:180}},{t:this.shape_1,p:{rotation:180}}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-31.5,-31.5,63,63);


(lib.btnDown = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhDD6IAAk0IhSAAICVi/ICWDAIhSAAIAAEzg");
	this.shape.setTransform(0,0,1,1,180);

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},3).wait(1));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#00FFFF").ss(3,1,1).p("AjHkrIGPAAQBkAAAABkIAAGPQAABkhkAAImPAAQhkAAAAhkIAAmPQAAhkBkAAg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#000066","#0066FF"],[0,1],30,30,30,-29.9).s().p("AjHEsQhkAAAAhkIAAmPQAAhkBkAAIGPAAQBkAAAABkIAAGPQAABkhkAAg");

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#000066","#00FFFF"],[0,1],30,30,30,-29.9).s().p("AjHEsQhkAAAAhkIAAmPQAAhkBkAAIGPAAQBkAAAABkIAAGPQAABkhkAAg");

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#FF00FF").ss(3,1,1).p("AjHkrIGPAAQBkAAAABkIAAGPQAABkhkAAImPAAQhkAAAAhkIAAmPQAAhkBkAAg");

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF00FF").s().p("AjHEsQhkAAAAhkIAAmPQAAhkBkAAIGPAAQBkAAAABkIAAGPQAABkhkAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1,p:{rotation:0}}]}).to({state:[{t:this.shape_3,p:{rotation:0}},{t:this.shape_1,p:{rotation:0}}]},1).to({state:[{t:this.shape_3,p:{rotation:180}},{t:this.shape_1,p:{rotation:180}}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-31.5,-31.5,63,63);


(lib.btn3D = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF00FF").s().p("Eh8/BGUMAAAiMnMD5/AAAMAAACMng");
	this.shape.setTransform(800,450);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,1600,900);


(lib.btn01 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.label = new cjs.Text("按鈕01", "26px 'Microsoft JhengHei'", "#FFFFFF");
	this.label.name = "label";
	this.label.textAlign = "center";
	this.label.lineHeight = 37;
	this.label.lineWidth = 100;
	this.label.parent = this;
	this.label.setTransform(0,-17.25);

	this.timeline.addTween(cjs.Tween.get(this.label).wait(4));

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#000066","#0066FF"],[0,1],0,30,0,-29.9).s("#00FFFF").ss(3,1,1).rr(-60,-30,120,60,10);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#000066","#00FFFF"],[0,1],0,30,0,-29.9).s("#00FFFF").ss(3,1,1).rr(-60,-30,120,60,10);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF00FF").s("#FF00FF").ss(3,1,1).rr(-60,-30,120,60,10);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1,p:{rotation:0}}]},1).to({state:[{t:this.shape_1,p:{rotation:180}}]},1).to({state:[{t:this.shape_2}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-61.5,-31.5,123,63);


(lib.textureAll = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層_4
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABFCxQgZgRAAgXQAAgSAQgPQAQgPA0gMQgSgLgFgHQgJgMAAgMQAAgTAQgQQAPgOAlgOQgcgLgNgSQgNgSAAgZQAAgZAPgWQAPgYAfgOQAegPAnAAQAZABATAFQAKADANAJIBOAAIgJAhIgpAAQAKARgBAPQAAAbgOAXQgPAWgcAOQgcANgjAAIgTgBIgZgEQgTAKgFAGQgDAEgBADQABAGAEADQAIAHAOAEQA8ANAUAHQAaALANARQANARAAAYQAAAlgiAbQghAchHAAQhHgBghgXgABrBqQgKAOAAAOQgBATAVAPQAUAQAsAAQAkAAARgOQAQgNAAgRQAAgQgPgLQgPgKgrgKIghgJQgbAKgKAMgADeiwQgQAOgMAiQgMAiAAAeQAAAPAIAIQAJAIAMAAQAMAAAJgIQAQgQAMgkQANgjAAgcQAAgOgIgHQgIgIgLAAQgOAAgKAJgAhJBBQgLgKAAgOQAAgMAHgZIAhhyQAHgYAAgFQAAgBAAAAQAAgBgBgBQAAAAAAgBQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAAAgBAAQAAgBgBAAQgEAAgEACQgGAEgKALQgMANgWAgQgWAggIARQgJASgHAcIgSA8IhLAAIA3i+QAEgQAAgFQAAgBAAAAQAAgBAAAAQAAgBgBgBQAAAAAAgBQgBAAAAAAQgBgBgBAAQAAAAgBAAQAAAAgBgBQgKABgXAcQglAsgdA+IgXBTIhLAAIA3i8QAIgbAAgMQAAgEgCgEQgDgEgFgBQgFgCgPAAIADgMIBkgRIARAAIglB+QAmg6ARgUQAZgdARgKQARgJAQAAQAUAAAIAMQAJAMAAANQgBAOgHAcIgOAvQAng6AQgUQAageATgKQANgHAOgBQAPAAALALQALAKAAARQgBASgIAfIggBtQgIAXAAAHQAAABABAAQAAABAAAAQAAABABAAQAAABAAABQABAAABAAQAAABABAAQAAAAABAAQAAABABAAQACAAADgCQAKgJALgRIAJgJIAJAGQgUAlgXASQgYARgVAAQgRAAgLgJg");
	this.shape.setTransform(49.95,49.75,1.2,1.2,0,0,0,0,-0.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF9900").s().p("AlKFmIAHgUQA2AAAYgUQAZgVAVhGICfoaQhTADg3AhQg3AhguBOIgVAAIA5jBII+AAIg2DBIgTAAIABgbQAAg2ghgfQgfgfhNgEIieIaQgNAsAAAXQAAATAQAMQAQAMAxABIgEAUg");
	this.shape_1.setTransform(50.075,50.075);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFF00").s().p("ADVDYQgGgHgGgeIgKgrIgVATIgTBBIgwAAIA/jXQADgMAAgFQAAgFgCgCQgBgDgEgBQgDgCgKAAIACgHIBAgLIAMAAIg0CzIA5g1QAHgHACgEIACgFQAAgEgEgDQgEgDgOgBIABgHIBOAAIgCAHQgOAEgIAEQgHADgKAHIgUASIgJAIIAMA0QAGAfAEAEQACADADAAQAHAAAJgPIADgGIAIAEQgPAbgSAOQgMAJgJAAQgKAAgHgHgAkrCvIADgLQAdAAANgLQANgKALglIBHjyQALgmABgLQgBgKgJgHQgIgIgcgBIADgLIFDAAIgaBpIgLAAQgCgggIgQQgIgQgUgJQgTgJgqAAIgzAAIgsCWQAugBANgDQAWgEARgOQASgPAMgZIALAAIgsCcIgMAAQADgPAAgJQAAgTgIgJQgHgLgMgEQgLgEg1gBIgrCUQgCAHABAHQAAAKADAGQAFAGAIADQAJAEAYAAIgDALg");
	this.shape_2.setTransform(49.9429,49.9641,1.4,1.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF6666").s().p("AARDtQgPgQAAgYQAAgUAQg4IAMgrQg7Bqg5ArQghAZgkAAQgxAAgWgoQgVgogBgyQAAhKAvhfQAshgBLg7QA9gwAzAAQAegBATASQAQARAKAtIAThBIB9gHIhyGIIgBAMQAAAGAEAFQAFAFAEAAQAMAAATgRQAIgIAegoIATAJQgmBEgqAgQgrAfgxAAQgeAAgQgPgAAHjKQgjAggpBlQgpBjABBIQAAAcAJANQAJANALAAQAYAAAYgcQAignAbg5QAyhiAAhNQAAgrgNgSQgJgOgQAAQgRAAgRAQg");
	this.shape_3.setTransform(50,50.05);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

	// 圖層_2
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(6,1,1).p("AFwjaIBeAAIgLAnIgxAAQALAVAAASQAAAggRAbQgSAbghAQQgiAQgqAAQgLAAgNgBQgNgCgPgDQgYAMgGAIQgEAEAAAFQAAAGAFAFQAJAHASAFQBIAPAXAJQAfANARAVQAPAUAAAdQAAAsgoAhQgoAghVAAQhWAAgogbQgdgVAAgcQAAgVATgTQATgSA/gOQgVgMgIgKQgKgNAAgOQAAgYATgSQASgSAtgRQgigNgPgVQgQgXAAgcQAAgfASgbQASgdAlgQQAjgRAvAAQAeAAAYAGQAMAEAPALgAEnjeQgRAAgMALQgTARgOAoQgPApAAAkQAAASAKAKQAKAJAPAAQAPAAAKgJQAUgTAPgrQAPgrAAgiQAAgPgKgKQgKgJgNAAgAkVjvIgtCXQAthGAVgYQAegkAUgLQAUgKAUAAQAXAAAKANQALAOAAAQQAAASgKAgIgQA6QAuhGAUgYQAfgkAXgNQAPgIASAAQASAAANAMQANAMAAAVQAAAWgLAjIgmCEQgJAcAAAIQAAADACADQADACACAAQADAAADgCQAMgKAOgUQAEgEAGgIIAMAHQgYAtgcAVQgdAVgZAAQgVAAgOgLQgMgMAAgQQAAgPAIgfIAoiIQAIgdAAgGQAAgDgCgCQgCgDgDAAQgFAAgEADQgHADgOAPQgOAPgaAmQgaAmgKAVQgKAWgKAhIgVBIIhZAAIBBjkQAGgTAAgHQAAgCgDgCQgCgDgCAAQgNAAgcAiQgrA1gjBLIgdBjIhZAAIBCjhQAJghAAgOQAAgGgCgEQgDgEgHgCQgGgDgSAAIAEgNIB4gUgACtBkQghANgMAPQgNAQAAARQAAAXAZASQAYATA1AAQAsAAAUgQQATgQAAgVQAAgUgRgMQgTgMg0gNQgXgGgQgFg");
	this.shape_4.setTransform(50,50.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("ABSDUQgegUABgcQgBgVAUgTQATgSA/gOQgWgMgHgKQgKgNAAgPQAAgXATgSQASgRAtgSQgigOgQgUQgPgXAAgdQAAgeATgbQASgcAkgRQAkgRAuAAQAeAAAYAGQAMADAPAMIBeAAIgMAnIgwAAQALAUAAATQAAAggRAbQgSAbghAQQgiAQgqAAIgYgBIgdgFQgXAMgGAIQgEAEAAAFQAAAGAFAFQAJAHASAEQBIAQAXAJQAfANARAVQAPAUAAAdQAAArgoAiQgpAghVAAQhVAAgogcgACACAQgMAPAAASQgBAWAZATQAYATA1AAQAsAAATgRQAUgPAAgWQAAgTgSgMQgSgMg0gNIgngLQghANgMAPgAEKjUQgUASgNAoQgPApAAAkQAAASAKAKQAKAJAPAAQAOAAALgJQAUgTAPgrQAOgrAAgiQABgPgKgKQgKgJgNAAQgSAAgLAKgAhZBNQgMgMAAgPQAAgPAIgfIAoiIQAIgdAAgGQAAgDgCgDQgCgCgDAAQgFAAgEACQgHAEgNAOQgPAPgaAnQgaAmgKAWQgKAUgKAhIgVBJIhZAAIBBjkQAGgTAAgHQAAgCgCgDQgDgCgCAAQgNAAgcAiQgrA1gjBLIgdBjIhZAAIBCjhQAJghAAgOQABgGgDgEQgDgEgGgCQgHgCgSAAIAEgOIB4gUIAVAAIgtCXQAthGAVgZQAfgjATgLQAUgKAUAAQAXAAAKANQALAOAAAQQAAASgKAgIgQA6QAuhHAUgXQAfgkAXgMQAPgKASABQASAAANAMQAMAMAAAVQAAAWgLAjIglCEQgKAcABAIQgBADADADQADACADAAQACAAADgCQAMgKAOgVIAKgLIAMAHQgYAtgcAVQgdAVgZAAQgVAAgOgMg");
	this.shape_5.setTransform(50,50.05);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#000000").ss(6,1,1).p("AjzllII+AAIg2DBIgTAAQABgQAAgLQAAg2ghgfQgfgfhNgEIieIaQgNAsAAAXQAAATAQAMQAQAMAxABIgEAUIliAAIAHgUQA2AAAYgUQAZgVAVhGICfoaQhTADg3AhQg3AhguBOIgVAAg");
	this.shape_6.setTransform(50.075,50.075);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FF9900").s().p("AlKFmIAHgUQA2AAAYgUQAZgVAVhGICfoaQhTADg3AhQg3AhguBOIgVAAIA5jBII+AAIg2DBIgTAAIABgbQAAg2ghgfQgfgfhNgEIieIaQgNAsAAAXQAAATAQAMQAQAMAxABIgEAUg");
	this.shape_7.setTransform(50.075,50.075);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#000000").ss(6,1,1).p("AE+g8IhKD7IBShLQAJgJADgHQACgDAAgEQAAgFgFgEQgGgEgVgBIADgKIBtAAIgDAKQgTAFgMAFQgJAEgOALQgUAQgIAIIgMAMIAPBJQAKArAFAGQADAEAEAAQAJAAAMgVQACgEAEgFIAKAGQgVAmgZATQgQANgOAAQgNAAgJgJQgJgKgJgqIgNg8IgeAaIgbBbIhEAAIBYktQAGgSAAgHQAAgGgCgDQgEgFgDgBQgFgCgPAAIADgKIBagPgAhMkXIg9DSQA/gBATgEQAegHAZgTQAYgVARgjIARAAIhADbIgQAAQAEgVAAgNQAAgagKgOQgLgPgQgGQgQgFhLgCIg7DQQgCAKAAAKQAAAOAFAJQAGAHAMAFQAMAFAjAAIgEAQIkWAAIAEgQQAoAAATgPQATgOAOgzIBjlUQAQg1ABgPQgBgPgNgKQgLgKgngCIAEgPIHGAAIglCTIgQAAQgCgtgMgXQgMgWgbgNQgbgMg8AAg");
	this.shape_8.setTransform(49.95,49.975);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFF00").s().p("AErEvQgJgKgJgqIgOg8IgdAaIgbBbIhEAAIBYktQAGgSAAgHQAAgGgCgDQgEgFgDgBQgGgCgNAAIACgKIBagPIARAAIhKD7IBShLQAIgJAEgHQACgDAAgEQAAgFgFgEQgGgEgUgBIACgKIBtAAIgDAKQgTAFgMAFQgJAEgOALQgUAQgIAIIgNAMIAQBJQAKArAFAGQADAEADAAQAKAAANgVIAFgJIAKAGQgVAmgYATQgSANgNAAQgNAAgJgJgAmjD1IAEgQQApAAASgPQATgOAPgzIBilUQAQg1ABgPQAAgPgNgKQgMgKgngCIAFgPIHFAAIgmCTIgPAAQgCgtgLgXQgNgWgbgNQgbgMg7AAIhHAAIg9DSQA/gBATgEQAegHAZgTQAYgVARgjIARAAIg/DbIgQAAQADgVAAgNQABgagLgOQgLgPgQgGQgQgFhLgCIg7DQQgCAKAAAKQAAAOAFAJQAGAHAMAFQAMAFAjAAIgEAQg");
	this.shape_9.setTransform(49.95,49.975);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#000000").ss(6,1,1).p("AD4jzIhxGIQgBAIAAAEQAAAGAFAFQAEAFAFAAQAKAAAUgRQAJgHAdgpIATAJQgmBFgqAfQgqAfgyAAQgdAAgRgPQgPgQAAgYQAAgUAQg4IAMgrQg7Bqg4ArQgiAZglAAQgwAAgWgoQgWgnAAgzQAAhJAuhgQAthgBKg7QA9gxA0AAQAeAAATASQAQARAKAtIAThBgABPiPQAAgrgNgSQgKgOgQAAQgPAAgTAQQgiAhgpBkQgoBjAABJQAAAbAJANQAJAMALAAQAZAAAXgbQAignAcg5QAxhiAAhNg");
	this.shape_10.setTransform(50,50.05);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FF6666").s().p("AARDtQgPgQAAgYQAAgUAQg4IAMgrQg7Bqg5ArQghAZgkAAQgxAAgWgoQgVgogBgyQAAhKAvhfQAshgBLg7QA9gwAzAAQAegBATASQAQARAKAtIAThBIB9gHIhyGIIgBAMQAAAGAEAFQAFAFAEAAQAMAAATgRQAIgIAegoIATAJQgmBEgqAgQgrAfgxAAQgeAAgQgPgAAHjKQgjAggpBlQgpBjABBIQAAAcAJANQAJANALAAQAYAAAYgcQAignAbg5QAyhiAAhNQAAgrgNgSQgJgOgQAAQgRAAgRAQg");
	this.shape_11.setTransform(50,50.05);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4}]}).to({state:[{t:this.shape_7},{t:this.shape_6}]},1).to({state:[{t:this.shape_9},{t:this.shape_8}]},1).to({state:[{t:this.shape_11},{t:this.shape_10}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.8,11.3,98.4,77.60000000000001);


(lib.btnReset = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABnCEIAAgLIjMAAIAAALIgaAAIAAj/QAAgJAIABIDuAAQAJgBAAAJIAAD/gAhlhmIAADFIDMAAIAAjFQAAgBAAgBQgBAAAAgBQgBAAAAAAQgBgBgBAAIjFAAQgFAAACAEgAhBA/QgEAAAAgEIAAh/QAAgBAAgBQABAAAAgBQABAAAAAAQABgBABAAICGAAQAEABAAADIAAB/QAAAEgEAAgAgrgtIAABRIABABIBYAAIACgBIAAhRIgCgBIhYAAQAAAAAAAAQAAAAAAAAQgBABAAAAQAAAAAAAAg");
	this.shape.setTransform(0.1,0,1.2,1.2,0,0,0,0.1,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(4));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#00FFFF").ss(3,1,1).p("AjHkrIGPAAQBkAAAABkIAAGPQAABkhkAAImPAAQhkAAAAhkIAAmPQAAhkBkAAg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#000066","#0066FF"],[0,1],30,30,30,-29.9).s().p("AjHEsQhkAAAAhkIAAmPQAAhkBkAAIGPAAQBkAAAABkIAAGPQAABkhkAAg");

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#000066","#00FFFF"],[0,1],30,30,30,-29.9).s().p("AjHEsQhkAAAAhkIAAmPQAAhkBkAAIGPAAQBkAAAABkIAAGPQAABkhkAAg");

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#FF00FF").ss(3,1,1).p("AjHkrIGPAAQBkAAAABkIAAGPQAABkhkAAImPAAQhkAAAAhkIAAmPQAAhkBkAAg");

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF00FF").s().p("AjHEsQhkAAAAhkIAAmPQAAhkBkAAIGPAAQBkAAAABkIAAGPQAABkhkAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1,p:{rotation:0}}]}).to({state:[{t:this.shape_3,p:{rotation:0}},{t:this.shape_1,p:{rotation:0}}]},1).to({state:[{t:this.shape_3,p:{rotation:180}},{t:this.shape_1,p:{rotation:180}}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-31.5,-31.5,63,63);


(lib.btnLessonC = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhYBYQgkgkAAg0QAAgyAkgmQAlgkAzAAQA0AAAkAkQAlAmAAAyQAAA0glAkQgkAlg0AAQgzAAglglg");
	this.shape.setTransform(-11,23.75);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhXBZQglglAAg0QAAgzAlgkQAlglAyAAQA0AAAkAlQAlAkAAAzQAAA0glAlQgkAkg0AAQgyAAglgkg");
	this.shape_1.setTransform(49,23.75);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FFFFFF").ss(2,1,1).p("AAAj5IAABLIBkAeIjHA9IDHA9IjHA8IDHA9IjHA+IBjAeIAAA7");
	this.shape_2.setTransform(-41.15,-33.45,0.726,1.0629,-28.7212,0,0,-0.1,-25.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ApXAZIAAgxISvAAIAAAxg");
	this.shape_3.setTransform(-1.5,-33.75);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#FFFFFF").ss(2,1,1).p("Ah2joIDtHR");
	this.shape_4.setTransform(30.9,-10.475);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(4));

	// Layer_1
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#00FFFF").ss(3,1,1).p("AqJuDIUTAAQBkAAAABkIAAY/QAABkhkAAI0TAAQhkAAAAhkIAA4/QAAhkBkAAg");

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["#000066","#0066FF"],[0,1],-15,-30,-15,-89.9).s().p("AqJOEQhkAAAAhkIAA4/QAAhkBkAAIUTAAQBkAAAABkIAAY/QAABkhkAAg");

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["#000066","#00FFFF"],[0,1],-15,-30,-15,-89.9).s().p("AqJOEQhkAAAAhkIAA4/QAAhkBkAAIUTAAQBkAAAABkIAAY/QAABkhkAAg");

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#FF00FF").ss(3,1,1).p("AqJuDIUTAAQBkAAAABkIAAY/QAABkhkAAI0TAAQhkAAAAhkIAA4/QAAhkBkAAg");

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FF00FF").s().p("AqJOEQhkAAAAhkIAA4/QAAhkBkAAIUTAAQBkAAAABkIAAY/QAABkhkAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5,p:{rotation:0}}]}).to({state:[{t:this.shape_7,p:{rotation:0}},{t:this.shape_5,p:{rotation:0}}]},1).to({state:[{t:this.shape_7,p:{rotation:180}},{t:this.shape_5,p:{rotation:180}}]},1).to({state:[{t:this.shape_9},{t:this.shape_8}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-76.5,-91.5,153,183);


(lib.btnLessonB = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(2,1,1).p("AAAj5IAAHz");
	this.shape.setTransform(-30,23.75);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFFFF").ss(2,1,1).p("AAAj5IAAHz");
	this.shape_1.setTransform(30,-51.25);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FFFFFF").ss(2,1,1).p("AAAj5IAAHz");
	this.shape_2.setTransform(30,23.75);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#FFFFFF").ss(2,1,1).p("AAAj5IAABLIBkAeIjHA9IDHA9IjHA8IDHA9IjHA+IBjAeIAAA7");
	this.shape_3.setTransform(-30,-53.0052,1,0.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("ApXAZIAAgxISvAAIAAAxg");
	this.shape_4.setTransform(0,-76.25);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AiVCWIAAkrIErAAIAAErg");
	this.shape_5.setTransform(30,-16.25);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AiVCWIAAkrIErAAIAAErg");
	this.shape_6.setTransform(30,63.75);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AiVCWIAAkrIErAAIAAErg");
	this.shape_7.setTransform(-30,63.75);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AiVCWIAAkrIErAAIAAErg");
	this.shape_8.setTransform(-30,-16.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(4));

	// Layer_1
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#00FFFF").ss(3,1,1).p("AqJuDIUTAAQBkAAAABkIAAY/QAABkhkAAI0TAAQhkAAAAhkIAA4/QAAhkBkAAg");

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.lf(["#000066","#0066FF"],[0,1],-15,-30,-15,-89.9).s().p("AqJOEQhkAAAAhkIAA4/QAAhkBkAAIUTAAQBkAAAABkIAAY/QAABkhkAAg");

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.lf(["#000066","#00FFFF"],[0,1],-15,-30,-15,-89.9).s().p("AqJOEQhkAAAAhkIAA4/QAAhkBkAAIUTAAQBkAAAABkIAAY/QAABkhkAAg");

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#FF00FF").ss(3,1,1).p("AqJuDIUTAAQBkAAAABkIAAY/QAABkhkAAI0TAAQhkAAAAhkIAA4/QAAhkBkAAg");

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FF00FF").s().p("AqJOEQhkAAAAhkIAA4/QAAhkBkAAIUTAAQBkAAAABkIAAY/QAABkhkAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9,p:{rotation:0}}]}).to({state:[{t:this.shape_11,p:{rotation:0}},{t:this.shape_9,p:{rotation:0}}]},1).to({state:[{t:this.shape_11,p:{rotation:180}},{t:this.shape_9,p:{rotation:180}}]},1).to({state:[{t:this.shape_13},{t:this.shape_12}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-76.5,-91.5,153,183);


(lib.btnLessonA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(2,1,1).p("AAAj5IAAHz");
	this.shape.setTransform(30,-51.25);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFFFF").ss(2,1,1).p("AAAj5IAAHz");
	this.shape_1.setTransform(-30,-51.25);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FFFFFF").ss(2,1,1).p("AAAj5IAAHz");
	this.shape_2.setTransform(30,23.75);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#FFFFFF").ss(2,1,1).p("AAAj5IAABLIBkAeIjHA9IDHA9IjHA8IDHA9IjHA+IBjAeIAAA7");
	this.shape_3.setTransform(-30,23.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("ApXAZIAAgxISvAAIAAAxg");
	this.shape_4.setTransform(0,-76.25);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AiVCWIAAkrIErAAIAAErg");
	this.shape_5.setTransform(30,-16.25);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AiVCWIAAkrIErAAIAAErg");
	this.shape_6.setTransform(30,63.75);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AiVCWIAAkrIErAAIAAErg");
	this.shape_7.setTransform(-30,63.75);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AiVCWIAAkrIErAAIAAErg");
	this.shape_8.setTransform(-30,-16.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(4));

	// Layer_1
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#00FFFF").ss(3,1,1).p("AqJuDIUTAAQBkAAAABkIAAY/QAABkhkAAI0TAAQhkAAAAhkIAA4/QAAhkBkAAg");

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.lf(["#000066","#0066FF"],[0,1],-15,-30,-15,-89.9).s().p("AqJOEQhkAAAAhkIAA4/QAAhkBkAAIUTAAQBkAAAABkIAAY/QAABkhkAAg");

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.lf(["#000066","#00FFFF"],[0,1],-15,-30,-15,-89.9).s().p("AqJOEQhkAAAAhkIAA4/QAAhkBkAAIUTAAQBkAAAABkIAAY/QAABkhkAAg");

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#FF00FF").ss(3,1,1).p("AqJuDIUTAAQBkAAAABkIAAY/QAABkhkAAI0TAAQhkAAAAhkIAA4/QAAhkBkAAg");

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FF00FF").s().p("AqJOEQhkAAAAhkIAA4/QAAhkBkAAIUTAAQBkAAAABkIAAY/QAABkhkAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9,p:{rotation:0}}]}).to({state:[{t:this.shape_11,p:{rotation:0}},{t:this.shape_9,p:{rotation:0}}]},1).to({state:[{t:this.shape_11,p:{rotation:180}},{t:this.shape_9,p:{rotation:180}}]},1).to({state:[{t:this.shape_13},{t:this.shape_12}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-76.5,-91.5,153,183);


(lib.btnCut = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAcCDIgCgeQAwAPALgLQALgHAFgSQAHgVABgvQABhrgBgFQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAAAgBAAIgtAAIAAAsQgCBPgYAuQgPAbgUAPQgXAQgqALIgQgWQAfgFAcgPQATgMANgVQAYgmABhRIAAgsIgzAAIAAgZICOAAIAGABQAEADAAAKQAABJgCA4QgDBegdAVQgKAGgSAAQgSAAgbgGgAhkBLQgFgFAAgIIAAhmIgYAEIgFgbIAdgEIAAhFIAaAAIAABDIBLgKIAEAbIhPAKIAABZQgBAFAEgCQAXgDAPgOQALgIABgHQABgHgBgVIAZADQABAZgDAKQgEAMgLAKQgKAKgXAKQgNAGgVAEQgIAAgHgFg");
	this.shape.setTransform(0.01,0.005,1.2,1.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(4));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#00FFFF").ss(3,1,1).p("AjHkrIGPAAQBkAAAABkIAAGPQAABkhkAAImPAAQhkAAAAhkIAAmPQAAhkBkAAg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#000066","#0066FF"],[0,1],30,30,30,-29.9).s().p("AjHEsQhkAAAAhkIAAmPQAAhkBkAAIGPAAQBkAAAABkIAAGPQAABkhkAAg");

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#000066","#00FFFF"],[0,1],30,30,30,-29.9).s().p("AjHEsQhkAAAAhkIAAmPQAAhkBkAAIGPAAQBkAAAABkIAAGPQAABkhkAAg");

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#FF00FF").ss(3,1,1).p("AjHkrIGPAAQBkAAAABkIAAGPQAABkhkAAImPAAQhkAAAAhkIAAmPQAAhkBkAAg");

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF00FF").s().p("AjHEsQhkAAAAhkIAAmPQAAhkBkAAIGPAAQBkAAAABkIAAGPQAABkhkAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1,p:{rotation:0}}]}).to({state:[{t:this.shape_3,p:{rotation:0}},{t:this.shape_1,p:{rotation:0}}]},1).to({state:[{t:this.shape_3,p:{rotation:180}},{t:this.shape_1,p:{rotation:180}}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-31.5,-31.5,63,63);


(lib.theSlider = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//老師寫的slider，不要修改
		//外部使用變數名稱
		//maximum    最大值number
		//minimum    最小值number
		//value      現在值number
		var sl=this;
		//內部變數
		sl.len = 150;
		sl.min = 0;
		sl.max = 100;
		sl.val = 0;
		sl.btnS.alpha=0;
		sl.digitN=0;
		//event
		sl.on('mousedown',function(e){
									//按下設值
									var localX = e.stageX - sl.x;
									setValue(sl,localX);
								});
		sl.on('pressmove',function(e){
									//拖曳設值
									var localX = e.stageX - sl.x;
									setValue(sl,localX);
								});
		//setValue from localX
		var setValue = function(who,localX){
			var lx=localX;
			if(lx<0){lx=0;}
			else if(lx>who.len){lx=who.len;}
			who.btn.x=lx;
			who.val = who.min+lx/who.len*(who.max-who.min);
			who.valueText.text = digitN(who.val , who.digitN);
		}
		//digitN 將數字取到小數點第N位，變成文字傳回
		var digitN = function( num, n){
			var pn=num<0?"-":"";
			num=Math.abs(num);
			if(n>0){
				var str = String(Math.round(num*Math.pow(10,n)));
				if(str.length<(n+1)){//補位數
					var tempN=n+1-str.length;
					for(var i=0;i<tempN;i++){
						str = "0"+str;
					}
				}
				str = pn+str.substr(0, str.length-n) + "." + str.substr(str.length-n);
			}else{
				var str = pn+String(Math.round(num));
			}
			return str;
		}
		//set value form js
		Object.defineProperty(sl, 'value', {
										    get: function() {
													return sl.val;
											    },
											set: function(_val) {
											        sl.val=_val;
												    if(sl.val>sl.max){sl.val=sl.max;}
												    else if(sl.val<sl.min){sl.val=sl.min;}
												    sl.btn.x=sl.len*(sl.val-sl.min)/(sl.max-sl.min);
													sl.valueText.text = digitN(sl.val , sl.digitN);
												}
									});
		//set length
		Object.defineProperty(sl, 'length', {
										    get: function() {
										        return sl.len;
										    },
										    set: function(_len) {
										        sl.len=_len;
										        sl.bgLine.scaleX=sl.len/150;
										        sl.btn.x=sl.len*(sl.val-sl.min)/(sl.max-sl.min);
										        //btnS
										        sl.btnS.scaleX=(sl.len+30)/100;
												sl.btnS.x=sl.len/2;
												sl.valueText.x = sl.len+20;
										    }
							});
		//set maximum
		Object.defineProperty(sl, 'maximum', {
										    get: function() {
										        return sl.max;
										    },
										    set: function(_max) {
										        sl.max=_max;
										        if(sl.val>sl.max){sl.val=sl.max;}
										        sl.btn.x=sl.len*(sl.val-sl.min)/(sl.max-sl.min);
												sl.valueText.text = digitN(sl.val , sl.digitN);
										    }
							});
		//set minimum
		Object.defineProperty(sl, 'minimum', {										
										    get: function() {
										        return sl.min;
										    },
										    set: function(_min) {
										        sl.min=_min;
										        if(sl.val<sl.min){sl.val=sl.min;}
										        sl.btn.x=sl.len*(sl.val-sl.min)/(sl.max-sl.min);
												sl.valueText.text = digitN(sl.val , sl.digitN);
										    }
							});
		//set valueText visible
		Object.defineProperty(sl, 'isValueText', {										
										    get: function() {
										        return sl.valueText.visible;
										    },
										    set: function(is) {
										        sl.valueText.visible=is;
										    }
							});
		//set label visible
		Object.defineProperty(sl, 'isLabel', {										
										    get: function() {
										        return sl.label.visible;
										    },
										    set: function(is) {
										        sl.label.visible=is;
										    }
							});
		//set label
		sl.setLabel = function(_text , _outline){
					sl.label.text = _text;
					sl.label.outline = _outline||0;
					}
		//sl help
		sl.help=function(){
			var str1="老師寫的slider，不要修改，\n外部使用變數名稱：\n maximum最大值number，\n minimum最小值number，\n value現在值number";
			var str2="\n length線長度 \n digitN顯示到小數點第N位(預設0) \n isLabel是否顯示文字標籤 \n isValueText是否顯示數字";
			var str3="\n 修改文字標籤：setLabel('文字',outline數字)"
			
			console.log(str1+str2+str3);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// text
	this.label = new cjs.Text("文字標籤", "26px 'Microsoft JhengHei'", "#FFFFFF");
	this.label.name = "label";
	this.label.textAlign = "right";
	this.label.lineHeight = 37;
	this.label.lineWidth = 146;
	this.label.parent = this;
	this.label.setTransform(-27,-17.25);

	this.valueText = new cjs.Text("0", "26px 'Arial'", "#FFFFFF");
	this.valueText.name = "valueText";
	this.valueText.lineHeight = 31;
	this.valueText.lineWidth = 100;
	this.valueText.parent = this;
	this.valueText.setTransform(172,-14.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.valueText},{t:this.label}]}).wait(1));

	// btn
	this.btn = new lib.sliderButton();
	this.btn.name = "btn";
	this.btn.parent = this;
	new cjs.ButtonHelper(this.btn, 0, 1, 2, false, new lib.sliderButton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn).wait(1));

	// btnS
	this.btnS = new lib.btnSquare();
	this.btnS.name = "btnS";
	this.btnS.parent = this;
	this.btnS.setTransform(74.95,0,1.8,0.3);
	new cjs.ButtonHelper(this.btnS, 0, 1, 2, false, new lib.btnSquare(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btnS).wait(1));

	// line
	this.bgLine = new lib.sliderBGLine();
	this.bgLine.name = "bgLine";
	this.bgLine.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.bgLine).wait(1));

}).prototype = getMCSymbolPrototype(lib.theSlider, new cjs.Rectangle(-175,-19.2,449,38.5), null);


(lib.theCheckbox = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//老師寫的checkBox，不要修改
		//外部可用變數：checked
		//修改文字標籤：setLabel("文字",outline數字)
		var ch=this;
		ch.stop();
		ch.ched=false;
		ch.checker.visible=ch.ched;
		ch.btnS.alpha=0;
		//click
		ch.on('click',function(e){
								//按下設值
								ch.ched=!ch.ched;
								ch.checker.visible=ch.ched;
							});
		//set label
		ch.setLabel = function(_text , _outline){
					ch.label.text = _text;
					ch.label.outline = _outline||0;
					
					var rect=ch.label.getBounds();
					ch.btnS.scaleX=(ch.label.x+rect.width+20)/100;
					ch.btnS.x=(ch.label.x+rect.width-20)/2;
					}
		
		//checked
		Object.defineProperty(this, 'checked', {
										    get: function() {
									        return ch.ched;
										    },
										    set: function(_ched) {
										        ch.ched=_ched;
										        ch.checker.visible=ch.ched;
										    }
								});
		//ch help
		ch.help = function(){
			var str="老師寫的checkBox，不要修改\n 外部可用變數：checked \n 修改文字標籤：setLabel('文字',outline數字)";
			console.log(str);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// btnS
	this.btnS = new lib.btnSquare();
	this.btnS.name = "btnS";
	this.btnS.parent = this;
	this.btnS.setTransform(59.2,0,1.6384,0.3399,0,0,0,0.1,0);
	new cjs.ButtonHelper(this.btnS, 0, 1, 2, false, new lib.btnSquare(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btnS).wait(1));

	// checker
	this.checker = new lib.checker();
	this.checker.name = "checker";
	this.checker.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.checker).wait(1));

	// box
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#CCCCCC").ss(3,1,1).p("AiViVIErAAIAAErIkrAAg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AiVCWIAAkrIErAAIAAErg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// label
	this.label = new cjs.Text("文字標籤", "26px 'Microsoft JhengHei'", "#FFFFFF");
	this.label.name = "label";
	this.label.lineHeight = 37;
	this.label.lineWidth = 132;
	this.label.parent = this;
	this.label.setTransform(24,-18.6);

	this.timeline.addTween(cjs.Tween.get(this.label).wait(1));

}).prototype = getMCSymbolPrototype(lib.theCheckbox, new cjs.Rectangle(-23.8,-20.7,181.9,38.7), null);


(lib.theButton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//老師寫的button，不要修改
		//外部使用變數名稱
		var bt=this;
		//set label
		bt.setLabel = function(_text){
					bt.btn.label.text = _text;
					}
		//bt help
		bt.help=function(){
			var str1="老師寫的button，不要修改，";
			var str2="\n 修改文字標籤：setLabel('文字');";
			
			console.log(str1+str2);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// 圖層_1
	this.btn = new lib.btn01();
	this.btn.name = "btn";
	this.btn.parent = this;
	new cjs.ButtonHelper(this.btn, 0, 1, 2, false, new lib.btn01(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn).wait(1));

}).prototype = getMCSymbolPrototype(lib.theButton, new cjs.Rectangle(-61.5,-31.5,123,63), null);


(lib.theBtnUp = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層_1
	this.btn = new lib.btnUp();
	this.btn.name = "btn";
	this.btn.parent = this;
	new cjs.ButtonHelper(this.btn, 0, 1, 2, false, new lib.btnUp(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn).wait(1));

}).prototype = getMCSymbolPrototype(lib.theBtnUp, new cjs.Rectangle(-31.5,-31.5,63,63), null);


(lib.theBtnRight = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層_1
	this.btn = new lib.btnRight();
	this.btn.name = "btn";
	this.btn.parent = this;
	new cjs.ButtonHelper(this.btn, 0, 1, 2, false, new lib.btnRight(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn).wait(1));

}).prototype = getMCSymbolPrototype(lib.theBtnRight, new cjs.Rectangle(-31.5,-31.5,63,63), null);


(lib.theBtnLeft = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層_1
	this.btn = new lib.btnLeft();
	this.btn.name = "btn";
	this.btn.parent = this;
	new cjs.ButtonHelper(this.btn, 0, 1, 2, false, new lib.btnLeft(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn).wait(1));

}).prototype = getMCSymbolPrototype(lib.theBtnLeft, new cjs.Rectangle(-31.5,-31.5,63,63), null);


(lib.theBtnDown = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層_1
	this.btn = new lib.btnDown();
	this.btn.name = "btn";
	this.btn.parent = this;
	new cjs.ButtonHelper(this.btn, 0, 1, 2, false, new lib.btnDown(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn).wait(1));

}).prototype = getMCSymbolPrototype(lib.theBtnDown, new cjs.Rectangle(-31.5,-31.5,63,63), null);


(lib.chSlow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//老師寫的checkBox，不要修改
		//外部可用變數：checked
		//修改文字標籤：setLabel("文字",outline數字)
		var ch=this;
		ch.stop();
		ch.ched=false;
		ch.checker.visible=ch.ched;
		ch.btnS.alpha=0;
		//click
		ch.on('click',function(e){
								//按下設值
								ch.ched=!ch.ched;
								ch.checker.visible=ch.ched;
							});
		//set label
		ch.setLabel = function(_text , _outline){
					ch.label.text = _text;
					ch.label.outline = _outline||0;
					
					var rect=ch.label.getBounds();
					ch.btnS.scaleX=(ch.label.x+rect.width+20)/100;
					ch.btnS.x=(ch.label.x+rect.width-20)/2;
					}
		
		//checked
		Object.defineProperty(this, 'checked', {
										    get: function() {
									        return ch.ched;
										    },
										    set: function(_ched) {
										        ch.ched=_ched;
										        ch.checker.visible=ch.ched;
										    }
								});
		//ch help
		ch.help = function(){
			var str="老師寫的checkBox，不要修改\n 外部可用變數：checked \n 修改文字標籤：setLabel('文字',outline數字)";
			console.log(str);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// btnS
	this.btnS = new lib.btnSquare();
	this.btnS.name = "btnS";
	this.btnS.parent = this;
	this.btnS.setTransform(59.2,0,1.6384,0.3399,0,0,0,0.1,0);
	new cjs.ButtonHelper(this.btnS, 0, 1, 2, false, new lib.btnSquare(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btnS).wait(1));

	// checker
	this.checker = new lib.checker();
	this.checker.name = "checker";
	this.checker.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.checker).wait(1));

	// box
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#CCCCCC").ss(3,1,1).p("AiViVIErAAIAAErIkrAAg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AiVCWIAAkrIErAAIAAErg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// label
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ADTCVIAAiiIgNASIgbgMQAwhBAJhLIAdAFIgTBIIAADbgAkVCCQgrARg5ACIgGgZQAkAAAagFQAFgDAIgBIgmgXIAOgUQAfAUAYAMQAKgEALgIQAYgLAMgMQAAgBAAAAQAAgBgBAAQAAAAgBgBQAAAAgBAAIiEAAIAAgYICjAAQAKAIAHAEQABAAAAABQAAAAAAABQAAAAAAABQAAAAgBAAQgUAegyAcQAgAHAtAAIgIAbQg4gDgtgQgAmvCVIAAkpIAZAAIAAEpgABDCRIgFgfQAiAIAHgHQAGgGAFgPQAFgTAAgpQAChegCgEIgDgDIgeAAIgEArQgFAwgJAqQgMA4gNAYIgbgFQAjhVAIh7IgaAAIAAgaIAcAAIAAgUIAAggIAbAAIAAAgQgBAJAAALIAyAAIAGABQAEADAAALIgBB1QgDBVgYASQgHAGgRAAQgMAAgQgDgAFSCTIAAjxIgdAAQgMA4gTAjIgdgJQAlhBABhEIAbABIgBAWICbAAIAAAcIhmAAIAAA+IBdAAIAAAcIhdAAIAAA7IBhAAIAAAbIhhAAIAABBgAiKB1IBHgFIAAgVIhCAAIAAgYIBCAAIAAgSIhBAAQgBAAAAgBQgBAAAAAAQAAgBgBgBQAAAAAAgBIAAhfIADgDIBBAAIAAgTIhFAAIAAgXIBFAAIAAgSQgmADgXAAIgEgYQBcAAA0gLIAEAXQgSAEgnAEIgBAAIAAATIBAAAIAAAXIhAAAIAAATIA7AAQABABABAAQAAAAABAAQAAABAAAAQABAAAAABIAABfQAAAEgEAAIg7AAIAAASIA7AAIAAAYIg7AAIAAATIA2gEIABAZIiUALgAgqAaIAlAAIACgBIAAgQIgnAAgAhuAaIArAAIAAgRIgrAAgAgqgNIAnAAIAAgRIgnAAgAhugNIArAAIAAgRIgrAAgAnTAeQAHgyAAg+IAWACQgDBQgFAggAltAeQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAhBQAAgBAAgBQABAAAAgBQAAAAABgBQAAAAAAAAIC+AAQAEAAAAAEIAABBQAAAEgEAAgAjmAJIAhAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAgBIAAgbQAAgBAAAAQAAAAAAAAQAAgBgBAAQAAAAAAAAIghAAgAkdAJIAeAAIAAgfIgeAAgAlWgUIAAAdIAgAAIAAgfIggAAQAAAAgBAAQAAAAAAABQAAAAAAAAQABAAAAABgAmNhUIAVgDIADBUIgWABgAlgg3QgBAAAAAAQgBgBAAAAQAAgBgBAAQAAgBAAgBIAAhRQABgBAAgBQAAgBABAAQAAgBAAAAQABAAAAAAICkAAQADAAAAAEIAABRQAAAEgDAAgAlKhNIB3AAIABgBIAAgMIh4AAgAlKh6IAAANIB4AAIAAgNIgBgBIh3AAQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAAAg");
	this.shape_2.setTransform(71.825,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

}).prototype = getMCSymbolPrototype(lib.chSlow, new cjs.Rectangle(-23.8,-20.7,165.8,38.7), null);


(lib.chFollow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//老師寫的checkBox，不要修改
		//外部可用變數：checked
		//修改文字標籤：setLabel("文字",outline數字)
		var ch=this;
		ch.stop();
		ch.ched=false;
		ch.checker.visible=ch.ched;
		ch.btnS.alpha=0;
		//click
		ch.on('click',function(e){
								//按下設值
								ch.ched=!ch.ched;
								ch.checker.visible=ch.ched;
							});
		//set label
		ch.setLabel = function(_text , _outline){
					ch.label.text = _text;
					ch.label.outline = _outline||0;
					
					var rect=ch.label.getBounds();
					ch.btnS.scaleX=(ch.label.x+rect.width+20)/100;
					ch.btnS.x=(ch.label.x+rect.width-20)/2;
					}
		
		//checked
		Object.defineProperty(this, 'checked', {
										    get: function() {
									        return ch.ched;
										    },
										    set: function(_ched) {
										        ch.ched=_ched;
										        ch.checker.visible=ch.ched;
										    }
								});
		//ch help
		ch.help = function(){
			var str="老師寫的checkBox，不要修改\n 外部可用變數：checked \n 修改文字標籤：setLabel('文字',outline數字)";
			console.log(str);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// btnS
	this.btnS = new lib.btnSquare();
	this.btnS.name = "btnS";
	this.btnS.parent = this;
	this.btnS.setTransform(59.2,0,1.6384,0.3399,0,0,0,0.1,0);
	new cjs.ButtonHelper(this.btnS, 0, 1, 2, false, new lib.btnSquare(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btnS).wait(1));

	// checker
	this.checker = new lib.checker();
	this.checker.name = "checker";
	this.checker.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.checker).wait(1));

	// box
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#CCCCCC").ss(3,1,1).p("AiViVIErAAIAAErIkrAAg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AiVCWIAAkrIErAAIAAErg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// label
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABKB+QAZgGAJgHQAJgJABgMIAAg+IgCgDIgOAAQAAAggNAMQgHAJgLABQgMAAgSgEIAABIIgZAAIAAkgQAAgBAAAAQAAgBAAAAQAAAAAAAAQAAgBABAAIACgBIA+AAIAQAKIgOBNQgEASAFAFQAJAVAFAOIAoAAQAGgBAAAIIAABQIAAACQACAHAHAHQAGAJAJADQAYAHB1gFIgGAbIhtAAQgtgCgPgWQgGAIgPAJQgPAKgPABgAAph1IAACkQALAKALAAQAGAAACgDQACgCAEgKQABgZgUg1QgBgDAAgHIAOhJIgdAAQAAAAgBAAQAAAAAAAAQAAABAAAAQAAAAAAABgAjUB8IAlgJIAAj4QAAgHAIAAICGAAQAHAAAAAIIAAB8QAAAIgJAAIg+AAQAFAdAJASQAlgWAUgSIAQAUQgZAWglAWQAQAeAuAcIgVASIgWgRQg5gygMhQIgaAAIAABrQAbgLAQgIIANAXQgoAWhFAQgAiUgZIBcAAQAEAAAAgEIAAgbIhgAAgAiUhsIAAAbIBgAAIAAgbQABgGgHAAIhUAAQgGACAAAEgAk0B1QAGgCAHAAIAAh7IAZAAIAAB0IASgHIAAiFIgoAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAgBAAgBIAAhkQAAgEAEAAIBgAAQAEAAAAAEIAABkQAAABAAABQgBAAAAABQgBAAAAAAQgBAAgBAAIgfAAIAAArIAjAAIAAAZIgjAAIAAA4IAegNIAKAXQgjAUhMAVgAkPg4IA1AAIABgBIAAg5Ig2AAgADxBxIgCgcQAbAGAFgDQAGgEAAgHIAAgIIhTAAIAAAoIgZAAIAAh7QAAgFAFAAIB6AAQAGAAAAAFIAABlQAAAOgNAIQgIAFgRAAQgKAAgNgBgADCAxIBTAAIAAgPIhTAAgADCABIAAANIBTAAIAAgNQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAgBAAIhOAAQgBAAAAAAQAAAAAAAAQgBABAAAAQAAAAAAAAgABZg2IASgSQAPAMAQAUIgRARQgTgWgNgJgACKgtQAdgbAUgjIghAAIAAgWIAsAAIAIgUIAXAJIgFALIBOAAIAAAWIhYAAIgIAQIBaAAIAAAUIgsAAIAAARIA0AAIAAAWIiCAAIAAgOIgPAQgAC1g2IAuAAIAAgRIghAAQgIAJgFAIgABmh1IARgRQARALAQAXIgUAQQgSgXgMgKg");
	this.shape_2.setTransform(55.925,0);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

}).prototype = getMCSymbolPrototype(lib.chFollow, new cjs.Rectangle(-23.8,-20.7,165.8,38.7), null);


(lib.chArrowF = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//老師寫的checkBox，不要修改
		//外部可用變數：checked
		//修改文字標籤：setLabel("文字",outline數字)
		var ch=this;
		ch.stop();
		ch.ched=false;
		ch.checker.visible=ch.ched;
		ch.btnS.alpha=0;
		//click
		ch.on('click',function(e){
								//按下設值
								ch.ched=!ch.ched;
								ch.checker.visible=ch.ched;
							});
		//set label
		ch.setLabel = function(_text , _outline){
					ch.label.text = _text;
					ch.label.outline = _outline||0;
					
					var rect=ch.label.getBounds();
					ch.btnS.scaleX=(ch.label.x+rect.width+20)/100;
					ch.btnS.x=(ch.label.x+rect.width-20)/2;
					}
		
		//checked
		Object.defineProperty(this, 'checked', {
										    get: function() {
									        return ch.ched;
										    },
										    set: function(_ched) {
										        ch.ched=_ched;
										        ch.checker.visible=ch.ched;
										    }
								});
		//ch help
		ch.help = function(){
			var str="老師寫的checkBox，不要修改\n 外部可用變數：checked \n 修改文字標籤：setLabel('文字',outline數字)";
			console.log(str);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// btnS
	this.btnS = new lib.btnSquare();
	this.btnS.name = "btnS";
	this.btnS.parent = this;
	this.btnS.setTransform(59.2,0,1.6384,0.3399,0,0,0,0.1,0);
	new cjs.ButtonHelper(this.btnS, 0, 1, 2, false, new lib.btnSquare(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btnS).wait(1));

	// checker
	this.checker = new lib.checker();
	this.checker.name = "checker";
	this.checker.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.checker).wait(1));

	// box
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#CCCCCC").ss(3,1,1).p("AiViVIErAAIAAErIkrAAg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AiVCWIAAkrIErAAIAAErg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// label
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AiBB3IACgGQARAAAIgHQAIgGAHgWIAqiRQAGgXABgGQAAgGgFgFQgGgEgRgBIACgGIDCAAIgQA/IgHAAQgBgUgEgJQgGgKgLgFQgMgGgZAAIgfAAIgZBaQAaAAAIgCQANgCALgJQAKgJAIgPIAHAAIgbBdIgIAAIACgOQAAgLgEgHQgFgGgHgCQgHgCgfgBIgZBZIgBAIQAAAGACAEQADAEAFACQAFACAPAAIgCAGg");
	this.shape_2.setTransform(110,0.025);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AimCPIAAgdQAgAKAIgFQACgEAAgFIAAgpIhZAAIAAgaIDJAAIAAAaIhVAAIAAAxQAAASgPAJQgGAEgLAAQgPAAgWgGgAkMCRIAAh/QgIAWgHAQIgagFQAcg0AIg5IggAAIAAgbIAlAAIAAg/IAbAAIAAA/IAaAAIAAAbIgaAAIAAAHIAlA7IgYAPIgNgbIAACVgAhOBpIARgWQAXAPAcAaIgSAUQgegagUgNgABVCFIABgdQAYAHAIACQAMADAIAAQAJAAAGgFQACgCAAgIIAAiGIiJAAIAAgbIEcAAIAAAbIh3AAIAACOQAAAUgOAJQgKAFgQAAQgXAAgjgKgAjnBzQAegLAYgaIAUASQgeAggbALgADjABIAagKQAhA7AYA9IgbAKQgahDgeg1gAAKBjQAugwARg+IAbAIQgZBKgnArgAi+AaIAAgZICiAAIAAAZgAjJgOQgDAAAAgEIAAhIQAAgBAAgBQAAgBABAAQAAAAABgBQABAAAAAAIAyAAIAAgTIg6AAIAAgZIDBAAIAAAZIg3AAIAAATIAwAAQAEAAAAAEIAABIQAAAEgEAAgAhHgnIAZAAIABgBIAAgdIgaAAgAh8gnIAaAAIAAgeIgaAAgAiygoQAAAAAAAAQAAABAAAAQABAAAAAAQAAAAAAAAIAaAAIAAgeIgbAAgAh8heIAaAAIAAgTIgaAAgAAwhvIAAgcIDjAAIAAAcg");
	this.shape_3.setTransform(56,0.0353);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.chArrowF, new cjs.Rectangle(-23.8,-20.7,165.8,38.7), null);


(lib.chArrowA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//老師寫的checkBox，不要修改
		//外部可用變數：checked
		//修改文字標籤：setLabel("文字",outline數字)
		var ch=this;
		ch.stop();
		ch.ched=false;
		ch.checker.visible=ch.ched;
		ch.btnS.alpha=0;
		//click
		ch.on('click',function(e){
								//按下設值
								ch.ched=!ch.ched;
								ch.checker.visible=ch.ched;
							});
		//set label
		ch.setLabel = function(_text , _outline){
					ch.label.text = _text;
					ch.label.outline = _outline||0;
					
					var rect=ch.label.getBounds();
					ch.btnS.scaleX=(ch.label.x+rect.width+20)/100;
					ch.btnS.x=(ch.label.x+rect.width-20)/2;
					}
		
		//checked
		Object.defineProperty(this, 'checked', {
										    get: function() {
									        return ch.ched;
										    },
										    set: function(_ched) {
										        ch.ched=_ched;
										        ch.checker.visible=ch.ched;
										    }
								});
		//ch help
		ch.help = function(){
			var str="老師寫的checkBox，不要修改\n 外部可用變數：checked \n 修改文字標籤：setLabel('文字',outline數字)";
			console.log(str);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// btnS
	this.btnS = new lib.btnSquare();
	this.btnS.name = "btnS";
	this.btnS.parent = this;
	this.btnS.setTransform(59.2,0,1.6384,0.3399,0,0,0,0.1,0);
	new cjs.ButtonHelper(this.btnS, 0, 1, 2, false, new lib.btnSquare(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btnS).wait(1));

	// checker
	this.checker = new lib.checker();
	this.checker.name = "checker";
	this.checker.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.checker).wait(1));

	// box
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#CCCCCC").ss(3,1,1).p("AiViVIErAAIAAErIkrAAg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AiVCWIAAkrIErAAIAAErg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// label
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAGBPQgGgFAAgJQAAgGAGgTIAEgOQgTAjgTAOQgLAJgMAAQgQAAgIgNQgHgNAAgSQAAgYAPgfQAQghAYgTQAUgQARAAQAKAAAGAGQAGAFADAPIAGgVIAqgCIgmCBIAAAFQAAAAAAAAQAAABAAAAQAAABABAAQAAABAAAAQABABAAAAQAAAAABABQAAAAABAAQAAAAAAAAQAEAAAGgGIANgQIAGADQgMAXgOAKQgPALgQAAQgKAAgFgFgAAChDQgLALgNAhQgOAhAAAYQAAAKADADQADAEAEABQAIgBAIgIQALgOAJgSQAQggAAgaQAAgOgEgHQgDgEgGAAQgFAAgGAFg");
	this.shape_2.setTransform(110.025,0);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AimCPIAAgdQAgAKAIgFQACgEAAgFIAAgpIhZAAIAAgaIDJAAIAAAaIhVAAIAAAxQAAASgPAJQgGAEgLAAQgPAAgWgGgAkMCRIAAh/QgIAWgHAQIgagFQAcg0AIg5IggAAIAAgbIAlAAIAAg/IAbAAIAAA/IAaAAIAAAbIgaAAIAAAHIAlA7IgYAPIgNgbIAACVgAhOBpIARgWQAXAPAcAaIgSAUQgegagUgNgABVCFIABgdQAYAHAIACQAMADAIAAQAJAAAGgFQACgCAAgIIAAiGIiJAAIAAgbIEcAAIAAAbIh3AAIAACOQAAAUgOAJQgKAFgQAAQgXAAgjgKgAjnBzQAegLAYgaIAUASQgeAggbALgADjABIAagKQAhA7AYA9IgbAKQgahDgeg1gAAKBjQAugwARg+IAbAIQgZBKgnArgAi+AaIAAgZICiAAIAAAZgAjJgOQgDAAAAgEIAAhIQAAgBAAgBQAAgBABAAQAAAAABgBQABAAAAAAIAyAAIAAgTIg6AAIAAgZIDBAAIAAAZIg3AAIAAATIAwAAQAEAAAAAEIAABIQAAAEgEAAgAhHgnIAZAAIABgBIAAgdIgaAAgAh8gnIAaAAIAAgeIgaAAgAiygoQAAAAAAAAQAAABAAAAQABAAAAAAQAAAAAAAAIAaAAIAAgeIgbAAgAh8heIAaAAIAAgTIgaAAgAAwhvIAAgcIDjAAIAAAcg");
	this.shape_3.setTransform(56,0.0353);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.chArrowA, new cjs.Rectangle(-23.8,-20.7,165.8,38.7), null);


// stage content:
(lib.myAnimate = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// helper
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("ADABJQgNgWAAg1QAAg1AMgRQAKgPASAAQARABALAOQANARAAA0QAAAygNAWQgKATgSAAQgSAAgJgPgADNg8QgIAPAAArQAAAwAIAPQAGAJAIAAQAJAAAGgKQAIgQAAgvQgBgqgIgPQgGgJgIAAQgJAAgFAJgAjvBJQgNgWAAg1QAAg1AMgRQAKgPASAAQARABALAOQANARAAA0QAAAygNAWQgKATgSAAQgSAAgJgPgAjig8QgIAPAAArQAAAwAIAPQAGAJAIAAQAJAAAGgKQAIgQAAgvQgBgqgIgPQgGgJgIAAQgJAAgFAJgAEiBVIAAgRIAcAAIAAiAIgdANIAAgSIAvgUIAACZIAcAAIAAARgAAOBVIAAgoIg7AAIAAgIIA1h6IAXAAIAAByIAUAAIAAAQIgUAAIAAAogAgYAdIAmAAIAAhWgAiTBVIAAgNQAAgfAkggQAhgbAAgVQAAgOgFgHQgHgJgJAAQgMAAgGAIQgJAKAAASIgRAAQAAgbAMgOQAMgNAUAAQARAAALANQALAMAAAXQAAAdgnAjQgeAbAAAQIBEAAIAAARgAlrBVIAAgNQAAgfAkggQAhgbAAgVQAAgOgFgHQgHgJgJAAQgMAAgGAIQgJAKAAASIgRAAQAAgbAMgOQAMgNAUAAQARAAALANQALAMAAAXQAAAdgnAjQgeAbAAAQIBEAAIAAARgABfBKIAAgZIAbAAIAAAZg");
	this.shape.setTransform(1555.4715,45.4794,0.8,0.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CCCCCC").s().p("AFmBlIAAhsIgJALIgSgHQAhgsAGgzIATAEIgNAwIAACTgACPBTIAZgBIAAgPQgZAJgVAAIgFgSQAqgEAmgQIhPAAIAAgRIBbAAIAAgKQgEgCgFAAIgBgRQASAFAFgEQAEgCAAgFIAAgDIgCgCIggAAIAAAbIgRAAIAAgbIgeAAIgBACIAAAXIgRAAIAAgkQAAgEAFAAIArAAIAAgKIgxAAIAAgQIAxAAIAAgJIgmAAIgNAJQgEgKgFgDQAPgLALgQIAOALIgEAFIAYAAIAAgPIARAAIAAAPIAwAAIAAAPIgwAAIAAAJIA0AAIAAAQIg0AAIAAAKIAvAAQAEAAAAAEIAAAXQAAAIgIAGQgEADgDABIAAAKIBWAAIAAARIgZAAIAIAMQgNAJgQAKQATAKAeADIgGASQg/gJgeguQgRAKgPAGIAAATQAbgDARgFIAEARQglAKgzACgADxAvIALAMIAhgVIgyAAIAGAJgAG8BkIAAiiIgUAAQgIAlgNAYIgTgGQAYgsABguIATABIgBAPIBpAAIAAATIhGAAIAAAqIBAAAIAAASIhAAAIAAAoIBCAAIAAASIhCAAIAAAsgAAaBiIgBgUQAfAGAHgGQAEgEAAgDIAAhHIhUAAIAAgQIB0AAIAAAQIgOAAIAABKQgBAHgDAGQgFAHgFACQgKADgOAAIgVgBgAk7BXQAcgYABg7IAAgFIgVAAIAAgSIBZAAIAAASIgPAAIAABCQAAAFADADQAEADADAAIBUAAQADAAACgDQACAAAAgVIARADQAAAdgDADQgIAHgFAAIhmAAQgHAAgGgGQgFgGAAgGIAAhNIgQAAIAAAFQAAA8ghAigAloBiIAAgHIhWAAIAAAHIgSAAIAAhVIgGADIgKgQQAmgLAVgSIg2AAIAAgRIAeAAQgHgKgGgFIANgMQAKAJAIAMIgGAGIAUAAIAAgeQgeACgUgBIgCgTQBFACAsgIIADASQgPAEgfABIgBAAIAAAfIAMAAIARgdIAPAIIgLAVIAdAAIAAARIg3AAQAXASAkAKIgKAPIgCgBIAABVgAmMBKIAkAAIAAgOIgkAAgAm+BKIAhAAIAAgOIghAAgAmMArIAkAAIAAgPQAAAAAAAAQgBgBAAAAQAAAAgBAAQAAAAgBAAIghAAgAm+AdIAAAOIAhAAIAAgQIgfAAQAAAAgBAAQAAAAgBAAQAAABAAAAQAAABAAAAgAlgAKQgWgJgWgOIAAAXIAsAAIAAAAgAmqgFQgCADgbAMIAqAAIAAgYIgNAJgAoTBYQAOgPAIgPQAJgRAGgVIARAFQgOAwgXAYgAhjBJIAhgCIAAhFIgcAAIAAgPIAcAAIAAgQIgTAAIAAgRIA6AAIAAARIgWAAIAAAQIAZAAIAAAPIgZAAIAABCIAdgHIAGARQgfAJgyAFgAjHBCIAAgUQAaAJAIgFQACgDAAgDIAAg/IgxAAIAAgTIAxAAIAAgWIASAAIAAAWIAaAAIAAATIgaAAIAABEQAAAMgKAGQgGADgJAAQgMAAgRgEgAgEBEQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAgBAAAAIAAgzQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAABAAIA6AAQAAAAABAAQABAAAAAAQAAAAABABQAAAAAAABIAAAzQAAAAAAABQgBAAAAABQAAAAgBAAQgBAAAAAAgAAJAdIAAAXIAeAAIABgBIAAgWIgBgBIgeAAQAAAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAgAhZA/QgCgbgDgUIAQgCQAFAcAAAVgAgrAzQAHgWABgQIAQAEIgIAmgAjQgCIAQgHQAMAVAIASIgRAHQgHgRgMgWgAEIAHIAAgRQAUAGAFgDQACgDAAgDIAAhVIASAAIAABZQgBALgIAFQgFADgJAAQgJAAgNgDgAoSgRIAKgQQAQAIAUARIgLAOQgVgPgOgIgAEAgTIAAhHIARAAIAABHgAAng7QgOAYggANIgMgPIAHgDQAcgNAIgOIglAAIAAgQIAqAAIAAgOIARgBIAAAPIAwAAIAAAQIgqAAQAPAWAeAIIgKAQQghgNgPgZgAkdgnIAAgSIA+AAIAAASgAiNg0IAFgTQAAAAAAgBQAAAAAAgBQgBAAAAAAQgBAAAAAAIiXAAQgBAAAAgBQAAAAAAABQgBAAAAAAQAAABAAAAIAAAaIgTAAIAAgqQAAgEAEAAICvAAIARAJQgBAPgIAWgAhjg9QAfgSAIgPIAQAAIgBADQAPAMAPAKIgNANIgYgWQgOAQgSANgAoPhMIAMgPQAPAKASASIgLANQgVgRgNgJg");
	this.shape_1.setTransform(1531.375,22.775);

	this.title = new lib.title();
	this.title.name = "title";
	this.title.parent = this;
	this.title.setTransform(279.95,79.95,0.8,0.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.title},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// UI
	this.chArrowF = new lib.chArrowF();
	this.chArrowF.name = "chArrowF";
	this.chArrowF.parent = this;
	this.chArrowF.setTransform(1396.95,347.8);

	this.btnLessonC = new lib.btnLessonC();
	this.btnLessonC.name = "btnLessonC";
	this.btnLessonC.parent = this;
	this.btnLessonC.setTransform(63.75,789,0.6,0.6,0,0,0,-0.1,0.1);
	new cjs.ButtonHelper(this.btnLessonC, 0, 1, 2, false, new lib.btnLessonC(), 3);

	this.btnLessonB = new lib.btnLessonB();
	this.btnLessonB.name = "btnLessonB";
	this.btnLessonB.parent = this;
	this.btnLessonB.setTransform(63.75,668.55,0.6,0.6,0,0,0,-0.1,0);
	new cjs.ButtonHelper(this.btnLessonB, 0, 1, 2, false, new lib.btnLessonB(), 3);

	this.btnLessonA = new lib.btnLessonA();
	this.btnLessonA.name = "btnLessonA";
	this.btnLessonA.parent = this;
	this.btnLessonA.setTransform(63.75,548.25,0.6,0.6,0,0,0,-0.1,0.1);
	new cjs.ButtonHelper(this.btnLessonA, 0, 1, 2, false, new lib.btnLessonA(), 3);

	this.instance = new lib.textureAll();
	this.instance.parent = this;
	this.instance.setTransform(-431.15,280.15);

	this.chArrowA = new lib.chArrowA();
	this.chArrowA.name = "chArrowA";
	this.chArrowA.parent = this;
	this.chArrowA.setTransform(1396.95,257.25);

	this.btnReset = new lib.btnReset();
	this.btnReset.name = "btnReset";
	this.btnReset.parent = this;
	this.btnReset.setTransform(1449.1,610,2.5,2.5);
	new cjs.ButtonHelper(this.btnReset, 0, 1, 2, false, new lib.btnReset(), 3);

	this.btnCut = new lib.btnCut();
	this.btnCut.name = "btnCut";
	this.btnCut.parent = this;
	this.btnCut.setTransform(1449.1,610,2.5,2.5);
	new cjs.ButtonHelper(this.btnCut, 0, 1, 2, false, new lib.btnCut(), 3);

	this.chFollow = new lib.chFollow();
	this.chFollow.name = "chFollow";
	this.chFollow.parent = this;
	this.chFollow.setTransform(1396.95,438.35);

	this.chSlow = new lib.chSlow();
	this.chSlow.name = "chSlow";
	this.chSlow.parent = this;
	this.chSlow.setTransform(1396.95,166.7);

	this.btnLeft = new lib.theBtnLeft();
	this.btnLeft.name = "btnLeft";
	this.btnLeft.parent = this;
	this.btnLeft.setTransform(1881.65,730);

	this.btnRight = new lib.theBtnRight();
	this.btnRight.name = "btnRight";
	this.btnRight.parent = this;
	this.btnRight.setTransform(2031.65,730);

	this.btnDown = new lib.theBtnDown();
	this.btnDown.name = "btnDown";
	this.btnDown.parent = this;
	this.btnDown.setTransform(1956.65,730);

	this.btnUp = new lib.theBtnUp();
	this.btnUp.name = "btnUp";
	this.btnUp.parent = this;
	this.btnUp.setTransform(1956.65,655);

	this.slCameraRR = new lib.theSlider();
	this.slCameraRR.name = "slCameraRR";
	this.slCameraRR.parent = this;
	this.slCameraRR.setTransform(1350,850);

	this.btn02 = new lib.theButton();
	this.btn02.name = "btn02";
	this.btn02.parent = this;
	this.btn02.setTransform(2031.65,550);

	this.btn01 = new lib.theButton();
	this.btn01.name = "btn01";
	this.btn01.parent = this;
	this.btn01.setTransform(1881.65,550);

	this.ch02 = new lib.theCheckbox();
	this.ch02.name = "ch02";
	this.ch02.parent = this;
	this.ch02.setTransform(1948.85,440.55,1,1,0,0,0,67.2,-1.4);

	this.ch01 = new lib.theCheckbox();
	this.ch01.name = "ch01";
	this.ch01.parent = this;
	this.ch01.setTransform(1948.85,368.4,1,1,0,0,0,67.2,-1.4);

	this.sl03 = new lib.theSlider();
	this.sl03.name = "sl03";
	this.sl03.parent = this;
	this.sl03.setTransform(1881.65,283.45);

	this.sl02 = new lib.theSlider();
	this.sl02.name = "sl02";
	this.sl02.parent = this;
	this.sl02.setTransform(1881.65,202.95);

	this.sl01 = new lib.theSlider();
	this.sl01.name = "sl01";
	this.sl01.parent = this;
	this.sl01.setTransform(1881.65,122.45);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.sl01},{t:this.sl02},{t:this.sl03},{t:this.ch01},{t:this.ch02},{t:this.btn01},{t:this.btn02},{t:this.slCameraRR},{t:this.btnUp},{t:this.btnDown},{t:this.btnRight},{t:this.btnLeft},{t:this.chSlow},{t:this.chFollow},{t:this.btnCut},{t:this.btnReset},{t:this.chArrowA},{t:this.instance},{t:this.btnLessonA},{t:this.btnLessonB},{t:this.btnLessonC},{t:this.chArrowF}]}).wait(1));

	// btn3D
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ACVCWQgWAAgbgNIAEgaQAZAOAXAAQANgEAEgJQACgKgFgQIiLAAIAAgaIB+AAIgQgUIAQAAIAsgTIh0AAIAAgYICRAAIAUAbIhCAeIAEAGIBsAAIAAAaIhhAAQACAEABAEQADAegQAPQgOALgSAAIgEAAgAGDCVIAAhaIgqARIgPgZQAjgLAWgLIAAhZIgUAAQgHApgFAPIgagEQAPgyAAg9IAAgSIAaAAIAAASIgBAfIASAAIAAg8IAcAAIAAA8IAbAAIAAAcIgbAAIAABMQAPgJAJgHIAQAWQgSAMgWALIAABogAmeCRIgFgfQAiAIAIgHQAFgGAFgPQAFgTABgpQABhegBgEIgEgDIgeAAIgEArQgFAwgJAqQgMA4gNAYIgbgFQAjhVAJh7IgbAAIAAgaIAcAAIAAgUIAAggIAbAAIAAAgQgBAJAAALIAyAAIAGABQAEADAAALIgBB1QgDBVgXASQgIAGgQAAQgMAAgRgDgArFBbQgPAagfAeIgXgRQAigYAXgtQgSgugFgsQgGAagFAMIgYgFIAACHIgaAAIAAgOIgoAAIAAAOIgbAAIAAikQAAgFAGAAIAaAAIAAg0IglAAIAAgZIAlAAIAAgoIAaAAIAAAoIAmAAIAAAZIgmAAIAAA0IAeAAQAFABAAAFIAAAYQAWg6ABhDIAAgWIAZAAIAAAWIgCAMIBRAAIAAAcIgPAAIAAAIQgCBFgaBIQASAjAZAmIgZAKIggg4gAtNAAIAABjIAoAAIAAhjQAAgEgEAAIghAAQgDAAAAAEgArFAZQAAABAAAAQAAABAAAAQABABAAAAQAAABAAAAQAOguACg8IAAgIIgeAAQABBEAMAqgAIKCMIgCghQAsAPALgIQAKgFAFgTQAGgVABgrQAChlgCgFIgDgCIgOAAQgBBAgcBAQgaA3g1AmIgVgUQBjg7AEiOIgUAAQgCATgDATQgOBAhABBIgYgPQAugtATglQAKgZAFgtIgWAAQgPArgQAYIgbgKQAmg5AHhBIAbAEQgCATgEAPIB6AAIAGABQAEADAAALIgBB8QgCBbgeAUQgKAGgQAAQgSAAgagHgAuVCSIAAifQgFAGgCAFIgZgIQAohDAFhEIAZACQgFAngHAbIAADfgAkwCOIAAgWIEhAAIAAAWgApsB1IBHgFIAAgVIhCAAIAAgYIBCAAIAAgSIhBAAQgBAAAAAAQgBgBAAAAQAAgBAAAAQgBgBAAgBIAAhfIADgDIBBAAIAAgTIhFAAIAAgXIBFAAIAAgSQglADgYAAIgEgYQBcAAA1gLIAEAXQgTAEgmAEIgCAAIAAATIBBAAIAAAXIhBAAIAAATIA8AAQABABABAAQAAAAABABQAAAAABAAQAAABAAAAIAABfQAAAEgEAAIg8AAIAAASIA8AAIAAAYIg8AAIAAATIA3gEIACAZIiWALgAoMAaIAmAAIABgBIAAgQIgnAAgApQAaIArAAIAAgRIgrAAgAoMgNIAnAAIAAgRIgnAAgApQgNIArAAIAAgRIgrAAgALrCLIAAgZIBYAAIAAgmIhIAAIAAgZIBIAAIAAgfIhGAAQgBAAgBAAQAAgBgBAAQAAAAAAgBQAAgBAAgBIAAiWQAAgBAAgBQAAAAAAgBQABAAAAAAQABgBABAAICoAAQADAAAAAEIAACWQAAAEgDAAIhHAAIAAAfIBLAAIAAAZIhLAAIAAAmIBYAAIAAAZgANegEIAvAAIABgBIAAgoIgwAAgAMTgFQAAAAABAAQAAABAAAAQAAAAAAAAQABAAAAAAIAuAAIAAgpIgwAAgANehGIAwAAIAAgrIgwAAgAMThGIAwAAIAAgrIgwAAgAKKBjIAogNIAAhfIghAAIAAgZIAhAAIAAhPIgjAAIAAgZIBgAAIAAAZIgiAAIAABPIAgAAIAAAZIggAAIAABWIAhgNIAMAZIgpAQQglAOgYAFgAkMBtQAAAAgBAAQAAgBAAAAQgBgBAAAAQAAgBAAgBIAAhRQAAgBABgBQAAgBAAAAQAAgBABAAQAAAAAAAAIDaAAQAEAAAAAEIAABRQAAAEgEAAgAiUBXIBMAAIABgBIAAgLIhNAAgAj1BXIBHAAIAAgMIhHAAgAiUA3IBNAAIAAgNIgBgBIhMAAgAj1AqIAAANIBHAAIAAgOIhHAAQAAAAgBAAQAAABAAAAQAAAAAAAAQABAAAAAAgAEQAYQAIgcAAgIQAAAAAAgBQAAgBgBAAQAAgBgBAAQgBAAAAAAIjqAAQgDgCAAAEIAAAnIgaAAIAAg9QABgFAEAAIAPAAIAAhhQABgGAFAAQAlABAegHIAIAWQgZAHgfAAQAAAAgBAAQAAABAAAAQAAAAAAABQABAAAAAAIAAAKIAtAAIAAAXIgtAAIAAALIAuAAIAAAWIguAAIAAAMIB9AAQgJgJgLgIQgTAKgUAFIgKgVIAcgHIgOgJIALgPQgJABgFAEIgLgUIAbgLQgNgHgEgBIALgUIAaAPQAMgHAIgJIAQAQIgOALIAPAKIgMATIAMAPIgPAKIARANIgNAPIBIAAIAAgNIgvAAIAAgWIAvAAIAAgKIgvAAIAAgXIAvAAIAAgKQAAAAAAgBQAAAAgBAAQAAgBgBAAQgBAAgBAAIgpAAIAAgXIBAAAQAGAAAAAFIAABiIACAAIAWALQgBAagLAigACQhhIAVAPQAKgGAJgHIgUgNQgEAEgQAHgAksALIAAgVIB+AAIAAgKIhrAAIAAgUIBrAAIAAgKIhlAAIAAgUIBlAAIAAgKIiCAAIAAgWICCAAIAAgIIhlAAIAAgUIBlAAIAAgRIAaAAIAAARIBjAAQAHABAAAFIAAAWIAbAAIAAAWIgbAAIAAAWQAAAIgHAAIhjAAIAAAKIBwAAIAAAUIhwAAIAAAKICBAAIAAAVgAiUhGIBPAAIACgDIAAgHIhRAAgAiUhmIBRAAIAAgHIgCgBIhPAAg");
	this.shape_2.setTransform(101.2,875.708);

	this.btn3D = new lib.btn3D();
	this.btn3D.name = "btn3D";
	this.btn3D.parent = this;
	new cjs.ButtonHelper(this.btn3D, 0, 1, 2, false, new lib.btn3D(), 3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.btn3D},{t:this.shape_2}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(369.7,450,1785.9999999999998,450);
// library properties:
lib.properties = {
	id: '98EA1A955B63F6489D0F00F6BFD1C4DE',
	width: 1600,
	height: 900,
	fps: 30,
	color: "#000000",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['98EA1A955B63F6489D0F00F6BFD1C4DE'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;